### ISSUE TITLE
How to use bmcweb

### ISSUE THREAD

**Issue by fengyd2018** [openbmc/bmcweb#1]
Hi,

Sorry to bother you.
I'm new to BMC.
I'm trying to integrate openbmc with bmcweb.
But I'm confused about how to use bmcweb.
Directory /usr/share/www/redfish can be found on the openbmc.
bmcweb only provides redfish service?

Thanks

**Comment by edtanous** [comment]
bmcweb provides a lot more than just Redfish.  In the README.md is a good rundown of what it provides.

bmcweb can be added to openbmc by adding the recipe to your target.  The recipe is in the openbmc/openbmc tree, and is named bmcweb.bb and starts bmcweb under port 883.

**Comment by fengyd2018** [comment]
bmcweb provides restful API?
How can I access the resources provided by bmcweb?

**Comment by edtanous** [comment]
Yes, bmcweb provides several APIs, it would depend on which one you're trying to access.

https://github.com/openbmc/docs/blob/master/REST-cheatsheet.md documents the /xyz dbus api.
phosphor-webui is UI driven, so documentation is a little light.

**Comment by edtanous** [comment]
Can this be closed?
