### ISSUE TITLE
BMC web Account service doesnt pass DMTF service validator check

### ISSUE THREAD

**Issue by gkeishin** [openbmc/bmcweb#104]
```
ERROR - 1 failNullCollection errors in /redfish/v1/AccountService/Roles/Callback
INFO - Counter({'pass': 3171, 'skipOptional': 2389, 'metadataNamespaces': 1047, 'passGet': 246, 'serviceNamespaces': 67, 'warningPresent': 26, 'invalidPropertyValue': 25, 'passAction': 6, 'optionalAction': 5, 'unverifiedComplexAdditional': 1, 'warnTrailingSlashLink': 1, 'failNullCollection': 1})
DEBUG - getSchemaDetails() -> CacheInfo(hits=2, misses=1348, maxsize=64, currsize=64)
DEBUG - callResourceURI() -> CacheInfo(hits=438, misses=349, maxsize=128, currsize=128)
ERROR - Validation has failed: 1 problems found
```

```
anil kumar appana (1):
      Fix remove callback user privilege access to login
```
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24712/

This one broke it perhaps 

@edtanous @gtmills @geissonator

**Comment by gkeishin** [comment]
Property Name | Value | Type | Exists | Result
-- | -- | -- | -- | --
@odata.context | /redfish/v1/$metadata#Role.Role | string | Yes | PASS
@odata.id | /redfish/v1/AccountService/Roles/Callback | string | Yes | PASS
@odata.type | #Role.v1_2_2.Role | string | Yes | PASS
RoleId | Callback | string | Yes | PASS
Actions | - | Role.v1_1_0.Actions | No | Optional
IsPredefined | TRUE | boolean | Yes | PASS
AssignedPrivileges | - | string (enum) | Yes | FAIL
OemPrivileges | Array (size: 0) | string | Yes | ...
Id | Callback | string | Yes | PASS
Description | Callback User Role | string | Yes | PASS
Name | User Role | string | Yes | PASS
Oem | - | Resource.Oem | No | Optional
ERROR   - AssignedPrivileges: Value of Collection property is null but Collections   cannot be null, only their entries

**Comment by gkeishin** [comment]
@anilkumarappana  can u check on this one.

**Comment by gtmills** [comment]
@gkeishin Still a problem?
