### ISSUE TITLE
How redirect HTTP web app to HTTPS

### ISSUE THREAD

**Issue by Journey-x** [openbmc/bmcweb#106]
When I login OpenBMC Web, I must input "https://10.0.15.43" instead of "10.0.15.43"

How to make OpenBMC Web automatically redirect  to HTTPS ?

**Comment by ratagupt** [comment]
@Journey-x Currently it is not supported. It is a kind of enhancement.

**Comment by geissonator** [comment]
This just got kicked off again on the mailing list as well via https://lists.ozlabs.org/pipermail/openbmc/2019-November/019246.html.

**Comment by mine260309** [comment]
We have a solution using nc to redirect http to https:
* https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/28015 enables nc server
* https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/28099 adds the scripts for nc to listen on 80 and redirect to 443
