### ISSUE TITLE
event log entries are also listed in the redfish/v1/UpdateService/FirmwareInventory

### ISSUE THREAD

**Issue by maxdog988** [openbmc/bmcweb#109]
I found that the event log entries are also listed in the redfish/v1/UpdateService/FirmwareInventory
"Members": [
        {
            "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/1"
        },
        {
            "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/2"
        },
        {
            "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/3d6fac2f"
        },
        {
            "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/e3437200"

Because the phosphor-logging also records the BMC version in the elog entry.
{
    "data": {
        "AdditionalData": [
            "CALLOUT_DEVICE_PATH=/sys/devices/platform/ahb/ahb:apb/f0082000.i2c/i2c-2/2-0058",
            "CALLOUT_ERRNO=6",
            "_PID=316"
        ],
        "Associations": [],
        "Id": 1,
        "Message": "xyz.openbmc_project.Sensor.Device.Error.ReadFailure",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
        "Resolved": false,
        "Severity": "xyz.openbmc_project.Logging.Entry.Level.Error",
        "Timestamp": 1571898300401,
        "Version": "2.8.0-dev-840-g59e312689-dirty"
    },
    "message": "200 OK",
    "status": "ok"
}

I think this situation is caused by this change.
https://github.com/openbmc/bmcweb/commit/49d734ff2f17f5f623e60e52a144d6304866aad3

Thanks,
Joseph

**Comment by geissonator** [comment]
Oh shoot, I just put a "fix" up for this but yeah, there was a reason we made this change. Will probably need some more discussion in review.

Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/28238

**Comment by gtmills** [comment]
@geissonator @maxdog988 28238 merged. Can we clsoe?

**Comment by geissonator** [comment]
Yep, fixed in https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/28238
