### ISSUE TITLE
Failure to upload image

### ISSUE THREAD

**Issue by mine260309** [openbmc/bmcweb#112]
On latest OpenBMC (`2.8.0-dev-1020-g90a837f71`), uploading image to BMC always results in below error:
```
$ curl -k  -H "X-Auth-Token: $token" -H "Content-Type: application/octet-stream" -X POST -T test.tar https://$bmc/upload/image
curl: (56) GnuTLS recv error (-54): Error in the pull function.
```

There should be something wrong with bmcweb handling the image upload.

**Comment by anoo1** [comment]
I removed the most recent bmcweb commit one at a time and found this is the one that breaks the upload method:
https://github.com/openbmc/bmcweb/commit/c00500bcb9c5145f5cacb78bbe3dd694fb85ba0a#diff-803ba410a868d281cec5495c502ba0de

With the commit before it (cac94c55c59a397524a04786f4d699e2bd7f21bf) the upload still works.

@jansow @feistjj could you take a look?

**Comment by anoo1** [comment]
Although I'm getting a different error:

```
$ curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/octet-stream" -X POST -T obmc-phosphor-image-witherspoon.ubi.mtd.tar https://${bmc}/upload/image
curl: (55) TCP connection reset by peer
```

**Comment by feistjj** [comment]
Checked that reverting c00500b does not fix the issue.. is there multiple bad commits?

**Comment by feistjj** [comment]
I reverted c00500b locally and it seems to work, I'll give @jansow the standard 24hrs to try to fix it, then we can revert it.

**Comment by jansow** [comment]
Fix is ready for review: [28294 ](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/28294) Increase HTTP connection timeout

Commit c00500b, among others, fixed HTTP deadline timer.
If payload transfer took more than 5 second connection was closed by bmcweb.
Increased timeout to 30 seconds which should address current cases.

**Comment by jansow** [comment]
Issue fixed by commit 2b5e08e.

**Comment by gtmills** [comment]
@mine260309 Can this be closed?

**Comment by mine260309** [comment]
Yup, issued fixed.
