### ISSUE TITLE
Enhance BMCWeb to present intermediate site identity certificates

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/bmcweb#116]
Enhance BMCWeb to present intermediate site identity certificates.
Document for the BMC Admin how to do it; for example, how to replace such certificates.

See discussion in the 2020-02-5 Agenda item 2:
https://docs.google.com/document/d/1b7x9BaxsfcukQDqbvZsU2ehMq4xoJRQvLxxsDUWmAOI

**Comment by edtanous** [comment]
I believe this has been long since closed.  bmcweb hosts whatever certificate phosphor-certificate-manager chooses to publish, which can be a set of intermediates.
