### ISSUE TITLE
Network Settings: Static IPv4 Configuration - PATCH doesn't return patch properties

### ISSUE THREAD

**Issue by dixsie** [openbmc/bmcweb#123]
## Expected Behavior
When submitting a PATCH expect PATCH to either return a 200 and the patched properties or a 204.

## Actual Behavior
Returns a 200 and only 1 property (host name in this case). Patch response should include IPv4 array.

Response payload: 
```
{
  "HostName": "witherspoon-YL10UF776031"
}
```

**Comment by dixsie** [comment]
@ratagupt @gtmills @derick-montague Can you help explain what the response should look like?

**Comment by edtanous** [comment]
In the intended design, this should be returning 204, and an empty payload.
