### ISSUE TITLE
Network Settings: Static IPv4 Configuration - PATCH 200 response does not persist

### ISSUE THREAD

**Issue by dixsie** [openbmc/bmcweb#124]
## Expected Behavior
Expect that sending a PATCH with updated properties for `IPv4StaticAddresses` should persist.

## Actual Behavior
Response is a 200 ok returning only HostName. Refreshing the page shows that the patch did not save successfully.

## References
Static IPv4 Addresses
- https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22940 @raviteja-b 
- https://github.com/openbmc/openbmc/issues/2163

**Comment by dixsie** [comment]
@ratagupt @gtmills @derick-montague Found an abandoned github issue around editing not working. Also found a Gerrit review showing that editing is working. Can someone help with this one?

**Comment by dixsie** [comment]
I am able to add and delete an IPv4 configuration, but unable to edit existing configs.

Example, when two objects in the array exist:

`"IPv4StaticAddresses": [
    {
      "Address": "10.0.0.0",
      "AddressOrigin": "Static",
      "Gateway": "0.0.0.0",
      "SubnetMask": "255.255.252.0"
    },
    {
      "Address": "10.0.0.2",
      "AddressOrigin": "Static",
      "Gateway": 0.0.0.0",
      "SubnetMask": "255.255.254.0"
    }
  ],`

and user edits the second object, changes do not persist: 

`curl -k -v -X PATCH -d '{"IPv4StaticAddresses": [{},{"Address": "10.6.6.1","Gateway": "0.0.0.0","SubnetMask": "255.255.254.0"}]}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0`

Passing in empty objects, passing in null, and adding a new config at the end of the array works as expected. Editing does not.

**Comment by dixsie** [comment]
Network Settings: Static IPv4 Configuration - PATCH doesn't return patch properties https://github.com/openbmc/bmcweb/issues/123

**Comment by ratagupt** [comment]
@prkatti1 : can you verify this?

**Comment by edtanous** [comment]
Is this bug still present?

**Comment by prkatti1** [comment]
It is fixed and working fine on latest build.
