### ISSUE TITLE
Need details on WebUI launching.

### ISSUE THREAD

**Issue by edineshkumar** [openbmc/bmcweb#131]
How I can read in BMC, either WebUI launched or else not?

If launched, also need which network(IP addr) was used for WebUI launching ?

**Comment by geissonator** [comment]
Should just be "https://<ip or hostname of bmc>"

**Comment by edineshkumar** [comment]
@geissonator thanks for your response, 

Actually my need is, after launching WebUI in URL, want to know WebUI is really launched  and also need IP address which is used for launching WebUI.

**Note**:
**These details and all must be get to know from BMC side**.

**Comment by edtanous** [comment]
Closing due to this not being a bug.  In general, please ask questions on the mailing list or discord, as the current bug template now recommends.
