### ISSUE TITLE
upload image：unable to upload image file

### ISSUE THREAD

**Issue by master882020** [openbmc/bmcweb#132]
hello！
Do image upload, bmcweb always gives below 400 error, even when the upload start.
![image](https://user-images.githubusercontent.com/61579998/87803967-cdf7dc00-c885-11ea-97af-e4e1bddce823.png)

**Comment by feistjj** [comment]
Please try uploading without using the web-ui (postman, python requests, etc), and post results

**Comment by master882020** [comment]
use cmd：

busctl set-property org.open_power.Software.Host.Updater /xyz/openbmc_project/software/<id> xyz.openbmc_project.Software.Activation RequestedActivation s xyz.openbmc_project.Software.Activation.RequestedActivations.Active

the error：

![image](https://user-images.githubusercontent.com/61579998/87678080-1a231d80-c7ad-11ea-88ef-3184ea2d4031.png)

**Comment by master882020** [comment]
@feistjj thank you！
the imaage is upload but can't update.
use cmd：
busctl set-property xyz.open_power.Software.BMC.Updater /xyz/openbmc_project/software/<id> xyz.openbmc_project.Software.Activation RequestedActivation s xyz.openbmc_project.Software.Activation.RequestedActivations.Active

the error：

![image](https://user-images.githubusercontent.com/61579998/87795031-13aea780-c87a-11ea-9075-083ed7f5b7d8.png)

**Comment by master882020** [comment]
> Please try uploading without using the web-ui (postman, python requests, etc), and post results

@feistjj hello！
use cmd：
busctl set-property xyz.open_power.Software.BMC.Updater /xyz/openbmc_project/software/<id> xyz.openbmc_project.Software.Activation RequestedActivation s xyz.openbmc_project.Software.Activation.RequestedActivations.Active

the error：

![image](https://user-images.githubusercontent.com/61579998/87795031-13aea780-c87a-11ea-9075-083ed7f5b7d8.png)

**Comment by feistjj** [comment]
Maintainers of phosphor-bmc-code-mgmt, any ideas? @anoo1 @gtmills @mine260309

**Comment by anoo1** [comment]
One possibility is that the uploaded image is the same one that's on the system.
Could you provide additional information:

- Journal:
Issue "journalctl -f &" then upload the file and post the journal messages that get printed during the upload command

- After upload:
You should see the 2 different versions, the running and the uploaded one:
busctl --no-pager tree xyz.openbmc_project.Software.BMC.Updater

Then let's display details on the uploaded one (assuming 9f08b58f is the uploaded version):
busctl --no-pager introspect xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software/9f08b58f

**Comment by master882020** [comment]
> One possibility is that the uploaded image is the same one that's on the system.
> Could you provide additional information:
> 
> * Journal:
>   Issue "journalctl -f &" then upload the file and post the journal messages that get printed during the upload command
> * After upload:
>   You should see the 2 different versions, the running and the uploaded one:
>   busctl --no-pager tree xyz.openbmc_project.Software.BMC.Updater
> 
> Then let's display details on the uploaded one (assuming 9f08b58f is the uploaded version):
> busctl --no-pager introspect xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software/9f08b58f

@anoo1  @feistjj  thanks！
the err is that the uploaded image is the same one that's on the system.
I can successfully upload the old image(2.8.0-dev...) and update it.

I suggest if  uploaded image is the same one,  it should be prompted: "uploaded image is the same one"! and Support upload the .all.tar file.

In addition, what configuration can I  changed  the version number, such as 2.9.0-dev to 2.9.1-dev, or can I specify  version? such as 1.0.0.

**Comment by anoo1** [comment]
> I suggest if uploaded image is the same one, it should be prompted: "uploaded image is the same one"!

The upload interface should print out a msg: "Software Object with the same version already exists"

> Support upload the *static.mtd.all.tar file.

Bright was working on adding the support but the review hasn't been updated in a few weeks. I might clean up it up so that we can merge it: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/27620

**Comment by master882020** [comment]
@anoo1 
> The upload interface should print out a msg: "Software Object with the same version already exists"
I thnik it should be prompted at webui like : "Errot: with the same version already exist", and not "Error:unable to upload image file"

> Bright was working on adding the support but the review hasn't been updated in a few weeks. I might clean up it up so that we can merge it: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/27620
Thank you very much. I hope it will merge soon.

**Comment by feistjj** [comment]
Closing as seems to not actually be an issue, please reopen if I am mistaken.
