### ISSUE TITLE
compile project failed,is it gcc version issue?thanks in advance!

### ISSUE THREAD

**Issue by zhangoneone** [openbmc/bmcweb#135]
git pull
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 10), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (14/14), 17.97 KiB | 766.00 KiB/s, done.
From https://github.com/openbmc/bmcweb
   62de0c6..72d566d  master     -> origin/master
Updating 62de0c6..72d566d
Fast-forward
 http/http_connection.h                  |  2 +
 redfish-core/include/utils/fw_utils.hpp | 92 +++++++++++++++++++++++----------
 redfish-core/lib/bios.hpp               |  6 ++-
 redfish-core/lib/managers.hpp           |  2 +-
 redfish-core/lib/systems.hpp            |  2 +-
 5 files changed, 73 insertions(+), 31 deletions(-)
zq@ubuntu:~/fucking/bmcweb$ ./build_x86.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11.1).
libpam0g-dev is already the newest version (1.3.1-5ubuntu4).
libssl-dev is already the newest version (1.1.1f-1ubuntu2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1).
autoconf-archive is already the newest version (20190106-2.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 205 not upgraded.
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/zq/fucking/bmcweb/build/3rdparty
[  2%] Performing update step for 'nlohmann-json'
[  5%] No configure step for 'nlohmann-json'
[  7%] No build step for 'nlohmann-json'
[ 10%] Performing install step for 'nlohmann-json'
[ 12%] Completed 'nlohmann-json'
[ 20%] Built target nlohmann-json
[ 40%] Built target Boost
[ 42%] Performing update step for 'gtest'
[ 45%] Performing configure step for 'gtest'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zq/fucking/bmcweb/build/googletest-build
[ 47%] Performing build step for 'gtest'
[ 25%] Built target gtest
[ 50%] Built target gmock
[ 75%] Built target gmock_main
[100%] Built target gtest_main
[ 50%] Performing install step for 'gtest'
[ 25%] Built target gtest
[ 50%] Built target gmock
[ 75%] Built target gmock_main
[100%] Built target gtest_main
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libgmock.a
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libgmock_main.a
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-actions.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-spec-builders.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-cardinalities.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-matchers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-actions.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-more-matchers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-function-mockers.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-actions.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-nice-strict.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-matchers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-more-actions.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-matchers.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-nice-strict.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/custom
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/custom/gmock-generated-actions.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/custom/gmock-port.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/custom/gmock-generated-actions.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/custom/gmock-matchers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/gmock-port.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/gmock-internal-utils.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/gmock-generated-internal-utils.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/internal/gmock-generated-internal-utils.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gmock/gmock-generated-function-mockers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/pkgconfig/gmock.pc
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/pkgconfig/gmock_main.pc
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libgtest.a
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libgtest_main.a
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-param-test.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-printers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest_prod.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-message.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest_pred_impl.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-param-test.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-spi.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-typed-test.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-port-arch.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/custom
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/custom/gtest-port.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/custom/gtest.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/custom/gtest-printers.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-port.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-type-util.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-tuple.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-type-util.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-tuple.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-param-util.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-string.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-param-util-generated.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-death-test-internal.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-param-util-generated.h.pump
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-filepath.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-internal.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/internal/gtest-linked_ptr.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-test-part.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/gtest/gtest-death-test.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/pkgconfig/gtest.pc
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/pkgconfig/gtest_main.pc
[ 52%] Completed 'gtest'
[ 60%] Built target gtest
[ 62%] Performing update step for 'tinyxml2'
[ 65%] Performing configure step for 'tinyxml2'
CMake Deprecation Warning at CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/zq/fucking/bmcweb/build/tinyxml2-build
[ 67%] Performing build step for 'tinyxml2'
[ 50%] Built target tinyxml2
[100%] Built target xmltest
[ 70%] Performing install step for 'tinyxml2'
[ 50%] Built target tinyxml2
[100%] Built target xmltest
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libtinyxml2.so.6.0.0
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libtinyxml2.so.6
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/libtinyxml2.so
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/include/tinyxml2.h
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/pkgconfig/tinyxml2.pc
-- Installing: /home/zq/fucking/bmcweb/build/prefix/lib/cmake/tinyxml2/tinyxml2Config.cmake
-- Up-to-date: /home/zq/fucking/bmcweb/build/prefix/lib/cmake/tinyxml2/tinyxml2Targets.cmake
-- Installing: /home/zq/fucking/bmcweb/build/prefix/lib/cmake/tinyxml2/tinyxml2Targets-noconfig.cmake
[ 72%] Completed 'tinyxml2'
[ 80%] Built target tinyxml2
[ 82%] Performing update step for 'sdbusplus-project'
[ 85%] No configure step for 'sdbusplus-project'
[ 87%] Performing build step for 'sdbusplus-project'
The Meson build system
Version: 0.53.2
Source dir: /home/zq/fucking/bmcweb/build/sdbusplus-src
Build dir: /home/zq/fucking/bmcweb/build/sdbusplus-src/build
Build type: native build
Project name: sdbusplus
Project version: 1.0.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libsystemd found: YES 245
Program sdbus++ found: YES (/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++)
Program sdbus++-gendir found: YES (/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++-gendir)
Run-time dependency Boost (coroutine) found: NO 
Run-time dependency threads found: YES

example/meson.build:26:0: ERROR: Command "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++-gendir --tool /home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++ --output /home/zq/fucking/bmcweb/build/sdbusplus-src/build/example net" failed with status 1.

A full log can be found at /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-logs/meson-log.txt
make[2]: *** [CMakeFiles/sdbusplus-project.dir/build.make:112: /home/zq/fucking/bmcweb/build/sdbusplus-project/src/sdbusplus-project-stamp/sdbusplus-project-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/sdbusplus-project.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
BOOST_VERSION=107300
OPENSSL_INCLUDE_DIR /usr/include
CMAKE_BUILD_TYPE=
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zq/fucking/bmcweb/build
Scanning dependencies of target bmcweb
[  8%] Building CXX object CMakeFiles/bmcweb.dir/src/webserver_main.cpp.o
[ 16%] Building CXX object CMakeFiles/bmcweb.dir/redfish-core/src/error_messages.cpp.o
[ 25%] Building CXX object CMakeFiles/bmcweb.dir/redfish-core/src/utils/json_utils.cpp.o
[ 33%] Linking CXX executable bmcweb
/usr/bin/ld: cannot find -lsdbusplus
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bmcweb.dir/build.make:118: bmcweb] Error 1
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/bmcweb.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by zhangoneone** [comment]
there are full compile log，as below:

Build started at 2020-07-25T02:07:10.183254
Main binary: /usr/bin/python3
Build Options: -Ddefault_library=static
Python system: Linux
The Meson build system
Version: 0.53.2
Source dir: /home/zq/fucking/bmcweb/build/sdbusplus-src
Build dir: /home/zq/fucking/bmcweb/build/sdbusplus-src/build
Build type: native build
Project name: sdbusplus
Project version: 1.0.0
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.c -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
No CXXFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.cc -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C++ linker for the build machine: c++ ld.bfd 2.34
No CFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.c -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
No CXXFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.cc -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.exe -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'libsystemd' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion libsystemd` -> 0
245
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags libsystemd` -> 0

PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config libsystemd --libs` -> 0
-L/lib/x86_64-linux-gnu -lsystemd
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config libsystemd --libs` -> 0
-lsystemd
Running compile:
Working directory:  /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpdmkziuh2
Command line:  c++ /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpdmkziuh2/testfile.cpp -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpdmkziuh2/output.exe -pipe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive 

Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        };
Compiler stdout:
 
Compiler stderr:
 
Program stdout:

8

Program stderr:


Running compile:
Working directory:  /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpr6b31ko_
Command line:  c++ /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpr6b31ko_/testfile.cpp -o /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmpr6b31ko_/output.obj -pipe -c -D_FILE_OFFSET_BITS=64 -O0 -fpermissive --print-search-dirs 

Code:
 
Compiler stdout:
 install: /usr/lib/gcc/x86_64-linux-gnu/9/
programs: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/9/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/9/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/

Compiler stderr:
 
Run-time dependency libsystemd found: YES 245
Program sdbus++ found: YES (/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++)
Program sdbus++-gendir found: YES (/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++-gendir)
Boost library root dir is None
Boost include directory is None
Running compile:
Working directory:  /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmp5zovsom1
Command line:  c++ /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmp5zovsom1/testfile.cpp -pipe -E -P -D_FILE_OFFSET_BITS=64 -P -O0 -fpermissive 

Code:
 
        #include <boost/version.hpp>
        #ifndef BOOST_LIB_VERSION
        # define BOOST_LIB_VERSION
        #endif
        "MESON_GET_DEFINE_DELIMITER"
BOOST_LIB_VERSION
Compiler stdout:
 
Compiler stderr:
 /home/zq/fucking/bmcweb/build/sdbusplus-src/build/meson-private/tmp5zovsom1/testfile.cpp:2:18: fatal error: boost/version.hpp: No such file or directory
    2 |         #include <boost/version.hpp>
      |                  ^~~~~~~~~~~~~~~~~~~
compilation terminated.

Run-time dependency Boost (coroutine) found: NO 
Run-time dependency threads found: YES
Running command: /home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++-gendir --tool /home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++ --output /home/zq/fucking/bmcweb/build/sdbusplus-src/build/example net
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++", line 2, in <module>
    import sdbusplus
  File "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbusplus/__init__.py", line 1, in <module>
    from sdbusplus.interface import Interface
  File "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbusplus/interface.py", line 3, in <module>
    from .namedelement import NamedElement
  File "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbusplus/namedelement.py", line 1, in <module>
    import inflection
ModuleNotFoundError: No module named 'inflection'



example/meson.build:26:0: ERROR: Command "/home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++-gendir --tool /home/zq/fucking/bmcweb/build/sdbusplus-src/tools/sdbus++ --output /home/zq/fucking/bmcweb/build/sdbusplus-src/build/example net" failed with status 1.

**Comment by feistjj** [comment]
> /usr/bin/ld: cannot find -lsdbusplus

sdbusplus recently changed to meson, and the out of tree build hasn't been fixed yet.

**Comment by zhangoneone** [comment]
> 
> 
> > /usr/bin/ld: cannot find -lsdbusplus
> 
> sdbusplus recently changed to meson, and the out of tree build hasn't been fixed yet.

is it a solution that add bmcweb project to openbmc project and build it by yocto?

**Comment by feistjj** [comment]
Yes, that or to use the openbmc-build-scripts repo docker container

**Comment by gtmills** [comment]
@zhangoneone Did this work? Can we close?

**Comment by edtanous** [comment]
If this is still an issue, please feel free to reopen.
