### ISSUE TITLE
Virtual Media Failed

### ISSUE THREAD

**Issue by chineweff** [openbmc/bmcweb#136]
I tried to upload images with virtual media and got errors from browser console.

![擷取](https://user-images.githubusercontent.com/22802902/88515446-4b59e400-d01e-11ea-8743-3bafeedf72a7.PNG)

And can curl or wscat commands do the same feature (virtual media)?

Does anyone have any ideas?

Thanks.

**Comment by aambroze** [comment]
Not sure what this error means but maybe you should start with basic checks...

Do you have https://github.com/openbmc/jsnbd set up in your system ? It sets up nbd-proxy application running in system as a backend for NBD device. 

Your kernel also needs to have Network Block Device and USB Gadget Mass Storage modules enabled. 

Also - bmcweb requires option BMCWEB_ENABLE_VM_WEBSOCKET enabled.

**Comment by chineweff** [comment]
Thanks for your help.

I have jsnbd in my system, bmcweb will run nbd-proxy (jsnbd) and my system has NBD devices in /dev folder.
I'm not sure how to check whether USB Gadget Mass Storage modules enabled.

I added some debug prints in jsnbd. After I started virtual media jsnbd received two sock_client events and then received SIGTERM event because of previous error in javascript (invalid option magic).

Should jsnbd receive udev events after I start virtual media?

**Comment by chineweff** [comment]
Thanks for your help.

I have jsnbd in my system, bmcweb will run nbd-proxy (jsnbd) and my system has NBD devices in /dev folder.

I add four lines in my kernel config to enable USB Gadget Mass Storage and Network Block Device.
CONFIG_USB_SUPPORT=y
CONFIG_USB_GADGET=y
CONFIG_USB_MASS_STORAGE=m
CONFIG_BLK_DEV_NBD=m

I added some debug prints in jsnbd. After I started virtual media jsnbd received two sock_client events and then received SIGTERM event because of previous error in javascript (invalid option magic).

Should jsnbd receive udev events after I start virtual media?

**Comment by aambroze** [comment]
@jk-ozlabs would you care to comment?

**Comment by edtanous** [comment]
Is this still an issue?

**Comment by gtmills** [comment]
No response. Closing. @aambroze @chineweff  Please reopen if still an issue. Thanks!
