### ISSUE TITLE
Dbus Interfaces for Inventory data like Dimms,Cpus,storage

### ISSUE THREAD

**Issue by chandu-tmba** [openbmc/bmcweb#137]
I want to test the system URI's like dimms,cpus,storage drives by manually setting dbus properties using interfaces defined in storage.hpp,cpudimm.hpp , Please let me know if any references available

**Comment by edtanous** [comment]
This is a question much better suited for the OpenBMC mailing list.  If this is still an issue, or there is a bug, please reopen and provide more details.
