### ISSUE TITLE
/Chassis/{id}/Thermal doesn't pass OCP Server Profile

### ISSUE THREAD

**Issue by hvu-ampere** [openbmc/bmcweb#143]
Hi,

When checking against OCP Server Profile, I got errors for /Chassis/{id}/Thermal as below:
```
(From InteropLog_*.txt)

*** /redfish/v1/Chassis/chassis/Thermal, Thermal
### Validating an InteropResource
### Validating PropertyRequirements for Temperatures
### Validating PropertyRequirements for Redundancy
38 of 45 tests passed.
Thermal.v1_6_2.Thermal, Counter({'totaltests': 45, 'pass': 38, 'fail.PhysicalContext.ReadRequirement': 6, 'passGet': 1, 'fail.Temperatures.Comparison': 1})
```

The `PhysicalContext` property is missing in Temperatures. This property is just recommended in OCP Baseline Hardware Profile but required by OCP Server Profile ([Link](https://www.opencompute.org/wiki/Hardware_Management/SpecsAndDesigns)).

Currently, I check in the code that `PhysicalContext` for Temperatures has not supported yet. How about adding a new field, e.g. physicalSensorEntity, in sensor configurations (`meta-*/recipes-phosphor/configuration/*/*-ipmi-sensor.yaml`)? Then, bmcweb can read this field for `PhysicalContext`.

Please let me know your opinions. Thank you.

**Comment by gtmills** [comment]
Redfish is replacing the Thermal and Power schemas with the ThermalSubsystem, PowerSubsystem, Fan, PowerSupply, etc scheams. 
See: https://www.dmtf.org/sites/default/files/Redfish_Release_2020.4_Overview.pdf

**Comment by edtanous** [comment]
No response from submitter.  Closing.
