### ISSUE TITLE
fatal error: sdbusplus/asio/connection.hpp: No such file or directory

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#162]
Hi,

After a totally new git clone, I get the following error with build_x86_docker.sh :-1: 

`
[7/17] Compiling C++ object dbus_utility_test.p/include_ut_dbus_utility_test.cpp.o
FAILED: dbus_utility_test.p/include_ut_dbus_utility_test.cpp.o 
c++ -Idbus_utility_test.p -I. -I.. -I../include -I../redfish-core/include -I../redfish-core/lib -I../http -I../subprojects/nlohmann/single_include -I../subprojects/nlohmann/single_include/nlohmann -I/usr/lib/x86_64-linux-gnu/pkgconfig/../../include -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -O2 -g -DBMCWEB_ENABLE_SSL -DBMCWEB_ENABLE_HOST_SERIAL_WEBSOCKET -DBMCWEB_ENABLE_KVM -DBMCWEB_ENABLE_MUTUAL_TLS_AUTHENTICATION -DWEBSERVER_ENABLE_PAM -DBMCWEB_ENABLE_REDFISH -DBMCWEB_ENABLE_DBUS_REST -DBMCWEB_ENABLE_STATIC_HOSTING -DBMCWEB_ENABLE_VM_WEBSOCKET -DBMCWEB_ENABLE_IBM_MANAGEMENT_CONSOLE -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wconversion -Wsign-conversion -Wno-attributes -Wno-stringop-overflow -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wunused-parameter -Wnull-dereference -Wdouble-promotion -Wformat=2 -fno-fat-lto-objects -fvisibility=hidden -fvisibility-inlines-hidden -DBMCWEB_ENABLE_LOGGING -DBMCWEB_ENABLE_DEBUG -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_ASIO_DISABLE_THREADS -DBOOST_BEAST_USE_STD_STRING_VIEW -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ALL_NO_LIB -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_URL_STANDALONE -DBOOST_URL_HEADER_ONLY -Wl,--start-group -lpthread -Wl,--end-group -DGTEST_HAS_PTHREAD=1 -isystem../subprojects/boost-url/include -isystem../subprojects/boost_1_73_0 -MD -MQ dbus_utility_test.p/include_ut_dbus_utility_test.cpp.o -MF dbus_utility_test.p/include_ut_dbus_utility_test.cpp.o.d -o dbus_utility_test.p/include_ut_dbus_utility_test.cpp.o -c ../include/ut/dbus_utility_test.cpp
In file included from ../include/ut/dbus_utility_test.cpp:3:
../include/dbus_singleton.hpp:2:10: fatal error: sdbusplus/asio/connection.hpp: No such file or directory
    2 | #include <sdbusplus/asio/connection.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[8/17] Compiling C++ object bmcweb.p/redfish-core_src_error_messages.cpp.o
[9/17] Compiling C++ object bmcweb.p/src_webserver_main.cpp.o
`
I will be pleased if you have any suggestion,
Francine

**Comment by manojkiraneda** [comment]
I have merged https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/37837 just now
can you clone the fresh changes and try again ?

**Comment by sathishvslabs** [comment]
Hi @manojkiraneda,
We are also seeing this problem. The Merge request you mentioned takes care of changes in redfish-core/ut/lock_test.cpp file. This error corresponds to dbus_utility_test.cpp file. We added sdbusplus as the "tests" dependencies. This make the build get pass this error.

**Comment by williamspatrick** [comment]
@sathishvslabs -would you mind pushing your fix to Gerrit so it can be merged?

**Comment by sathishvslabs** [comment]
@williamspatrick raised a Gerrit review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38729
