### ISSUE TITLE
Log message prints.

### ISSUE THREAD

**Issue by edineshkumar** [openbmc/bmcweb#169]
`BMCWEB_LOG_DEBUG << "This is my print message";`

Where I can see this print message in BMC ?

Is anything need to be enable for BMCWEB_LOG_DEBUG ????

**Comment by edtanous** [comment]
assuming you've enabled logging, they will end up in the journal.  Please see the meson_options for the logging option to enable.

**Comment by edineshkumar** [comment]
`CPPFLAGS +=" -DBMCWEB_ENABLE_LOGGING   -DBMCWEB_ENABLE_DEBUG "`

I have added above flags to bmcweb, even though  print messages are can not able to see in journalctl.

@edtanous, can you give more details on it ???

**Comment by edineshkumar** [comment]
add_definitions (-DBMCWEB_ENABLE_DEBUG)
    add_definitions (-DBMCWEB_ENABLE_LOGGING)

By these, I can able to achieve.
Closing the issue.
Thanks...!
