### ISSUE TITLE
Which module implements the back end by mounting ISO through redfish

### ISSUE THREAD

**Issue by wuzp-su** [openbmc/bmcweb#172]
The virtual_media.hpp call "xyz.openbmc_project.VirtualMedia.Legacy" "mount" method,  but  I didn't find out which module implement the method.

**Comment by tejas-patil20** [comment]
> The virtual_media.hpp call "xyz.openbmc_project.VirtualMedia.Legacy" "mount" method, but I didn't find out which module implement the method.

As per my understanding virtual-media package is responsible for media redirection from redfish.
The dbus interface "xyz.openbmc_project.VirtualMedia.Legacy" with "mount" and "unmount" methods will be created and handled by this package only.

You can check the recipe link for this :
https://github.com/Intel-BMC/openbmc/blob/c16fb8893b19075db4bcf3b5bf33c1db8c3ca2bd/meta-openbmc-mods/meta-common/recipes-phosphor/virtual-media/virtual-media.bb

Source code location:
https://github.com/Intel-BMC/provingground/tree/master/virtual-media

If this recipe is missing in your build then please try to add it manually and check once.

**Comment by wuzp-su** [comment]
thanks so much @tejas-patil20

**Comment by kapil1024** [comment]
@tejas-patil20 Are there any plans to add it (virtual-media package) to OpenBMC repo?

**Comment by tejas-patil20** [comment]
> @tejas-patil20 Are there any plans to add it (virtual-media package) to OpenBMC repo?

I am not sure, as I am not a responsible person for this. 
You can please check with respected module owners.

**Comment by kapil1024** [comment]
@aambroze I see your name in Git history of redfish-core for VM legacy mode. Do you own its back end (virtual-media package) as well?

**Comment by kapil1024** [comment]
@awiatrow Are there any plans to add virtual-media package to OpenBMC repo?

**Comment by kapil1024** [comment]
FYI, I see some development happening on this front
https://lists.ozlabs.org/pipermail/openbmc/2021-December/028502.html
https://gerrit.openbmc-project.xyz/c/openbmc/jsnbd/+/49944
