### ISSUE TITLE
Validator errors when LDAP is removed from the build 

### ISSUE THREAD

**Issue by gtmills** [openbmc/bmcweb#175]
LDAP was removed from Witherspoon here, https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/39353 
Removing LDAP introduced the following errors:
```
1 failProp errors in /redfish/v1/CertificateService
1 problemResource errors in /redfish/v1/CertificateService/CertificateLocations
1 failProp errors in /redfish/v1/AccountService
1 problemResource errors in /redfish/v1/AccountService/LDAP/Certificates
```

So the link to /redfish/v1/AccountService/LDAP/Certificates in the collection is hardcoded, always there:
https://github.com/openbmc/bmcweb/blob/88b3dd12851cd7bdd4b5c065ba99f40feafb775e/redfish-core/lib/account_service.hpp#L1189

when we are calling the ldap service we are getting an error
https://github.com/openbmc/bmcweb/blob/88b3dd12851cd7bdd4b5c065ba99f40feafb775e/redfish-core/lib/certificate_service.hpp#L1006
https://github.com/openbmc/bmcweb/blob/88b3dd12851cd7bdd4b5c065ba99f40feafb775e/redfish-core/lib/certificate_service.hpp#L1033
https://github.com/openbmc/bmcweb/blob/88b3dd12851cd7bdd4b5c065ba99f40feafb775e/redfish-core/lib/certificate_service.hpp#L1105

@ratagupt FYI

**Comment by geissonator** [comment]
Just an FYI, I've changed our HW CI jenkins job to not fail when the Redfish validation job fails because of this bug. This means we no longer have CI verifying there are no validation fails.

**Comment by edtanous** [comment]
@ratagupt

Can you look into this?

**Comment by geissonator** [comment]
I think Jonathan may have fixed this for us over in https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40204? I noticed a redfish validator run actually passed and saw this commit in the bmcweb bump.

**Comment by gtmills** [comment]
Reenable CI ?

**Comment by geissonator** [comment]
Yep, over night runs looked good that had this commit in it so I've re-enabled the Redfish validator to cause HW CI fails. Thanks @jonathan-doman!

**Comment by gtmills** [comment]
Closing. Please reopen if still a issue.
