### ISSUE TITLE
Not found error response with BMC dump URI

### ISSUE THREAD

**Issue by rahulmah** [openbmc/bmcweb#198]
**Describe the bug**
Started seeing "Not found" response with the recent master build(2.10.0-dev-836-g06dc92d6f) for BMC dump URIs.

**Environment**
This issue was seen on Witherspoon-Tacoma box and the openBMC version - 2.10.0-dev-836-g06dc92d6f.

**To Reproduce**
1. Run the command 'curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/Dump/Entries' to check BMC dump entries.

```
bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/Dump/Entries
Not Found

bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/Dump/
Not Found

bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/
{
  "@odata.id": "/redfish/v1/Managers/bmc/LogServices",
  "@odata.type": "#LogServiceCollection.LogServiceCollection",
  "Description": "Collection of LogServices for this Manager",
  "Members": [],
  "Members@odata.count": 0,
  "Name": "Open BMC Log Services Collection"
}

$ curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/Dump/Actions/Oem/OemLogService.CollectDiagnoticData -d '{"DiagnosticDataType" : "Manager", "OEMDiagnosticDataType": ""}'
Not Foundbash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${BMC_IP}/redfish/v1/Managers/bmc/LogServices/Dump/Actions/LogService.CollectDiagn -d '{"DiagnosticDataType":"Manager"}'
Not Foundbash-4.2
$
```

**Is this a regression**
This was working long back when we tested. We recently observed this failure while testing the master. So unsure about the commit which impacted it.

**Comment by edtanous** [comment]
I don't see anything obviously wrong with the code, and I don't have a system that supports the dump interface to test with;  Can you bisect and figure out what change broke this for you? then we can go from there.

**Comment by rahulmah** [comment]
Ed
@raviteja-b has analysed this while looking up https://github.com/openbmc/bmcweb/issues/194. 
As per him ```Bmcweb redfish-dump-log flag is disabled by default, this flag needs to be enabled for compiling Bmcweb with dump code.
seems in openbmc master Bmcweb recipe does not include this flag```

**Comment by gtmills** [comment]
@rahulmah If I am understanding this right, this doesn't sound like a bmcweb issue. If so, can you close? 
@raviteja-b Could you make a change so redfish-dump-log is enabled in like the meta-ibm layer?

**Comment by rahulmah** [comment]
@gtmills : Sure.
@raviteja-b : Can I open up this issue in meta-ibm as suggested above?

**Comment by gtmills** [comment]
@rahulmah Yes, let's do that. Closing.
