### ISSUE TITLE
multiple systems support

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#199]
Hi @ll
it could be better to have a /Systems/<str> Node parsing and host<instance> as a dbus target implementation in web operation(get, post...)
Inspur RMC/Rack implementation patches these parts 2 years ago, it could be a good evolution.

Regards,
Francine

**Comment by edtanous** [comment]
Please ask questions to the OpenBMC mailing list, per the instructions in the github templates instructions.

**Comment by frsauvage** [comment]
@edtanous , what do you mean by "OpenBMC mailing list" ?
Sorry for my ignorance ;-)

**Comment by williamspatrick** [comment]
> Sorry for my ignorance ;-)

np.

> what do you mean by "OpenBMC mailing list" ?

https://github.com/openbmc/docs#contact

Also, when you create an issue here (New Issue button) it has templates and one of them is Question which states:

>Please do not use GitHub issues for submitting questions.  Please submit your
> questions either to the OpenBMC mailing list, or to the OpenBMC discord channel.
>https://github.com/openbmc/docs/blob/master/README.md#contact

Unfortunately, not many people monitor our organization's github issues regularly, so you get a lot more visibility by using the more common communication avenues mentioned here (ML / Discord).
