### ISSUE TITLE
OEM Id schema need fix

### ISSUE THREAD

**Issue by gkeishin** [openbmc/bmcweb#20]
For the resource /redfish/v1/Managers/bmc/  I see the following
```
  "Oem": {
    "@odata.context": "/redfish/v1/$metadata#OemManager.Oem",
    "@odata.id": "/redfish/v1/Managers/bmc#/Oem",
    "@odata.type": "#OemManager.Oem",
    "OpenBmc": {
      "@odata.context": "/redfish/v1/$metadata#OemManager.OpenBmc",
      "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
      "@odata.type": "#OemManager.OpenBmc"
    }
  },
```

those `"@odata.id"` should be     `"@odata.id": "/redfish/v1/Managers/bmc/Oem",`and `"@odata.id": "/redfish/v1/Managers/bmc/Oem/OpenBmc"`

**Comment by feistjj** [comment]
Why do you think that? The # means it's on the same page, if it was as you suggest it would link to a new page which is incorrect.

**Comment by edtanous** [comment]
@gkeishin Based on what I'm seeing, that response looks correct, and (at least for a filled schema) passes the service validator no problem.  The reason it looks slightly confusing is that it's backed by entity-manager interfaces that I'm guessing your system doesn't have enabled, so you get a blank schema, as no configuration is present.

If you still think the # is wrong, it would be good if you could point to where in the specification you're looking at for that analysis.  The part of the specification I'm looking at is in 6.1.1 of Redfish the 1.6.0 spec
```
URIs, as described in RFC3986, may also contain a query (?query) and a frag (#frag) components.
Queries are addressed in the clause Query Parameters. Fragments (frag) shall be ignored by the server
when used as the URI for submitting an operation.
```

**Comment by gkeishin** [comment]
Thanks, @edtanous  for pointing out the RFC there.. 

So, the following fragment identifies a property of `OpenBmc` within `Oem`

```
"@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
```
and the property is defined as a reference property within the schema, the fragment needs to reference a `valid resource identifier` which doesn't seem to be the case here on our boxes or is it we haven't defined one for it Oem ? 

@gtmills ^^^

**Comment by edtanous** [comment]
You're close, but missing the fact that all of your resource identifiers seem to be valid.  /redfish/v1/Managers/bmc#/Oem/OpenBmc is a valid resource identifier for the object.

You may not have any fan control data populated, but an empty collection is still a valid one.

Have you tried running this through redfish service validator?  What does it say?

**Comment by gkeishin** [comment]
Couldnt run on latest master.. looks broken there https://github.com/openbmc/bmcweb/issues/21

**Comment by edtanous** [comment]
There have been no changes in that area jrecently.  The response should be the same.

**Comment by gkeishin** [comment]
sure thing then. Will close this one for now..
