### ISSUE TITLE
Extends Chassis actions ?

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#200]
Hi,
I need "Power on / Off" chassis actions.
Why is there only a "PowerCycle" and an error by default ?
The only way to add an action is to change the code, It would be less maintainable.

Why the other chassis reset types are not implemented like (in Systems.cpp) :
xyz.openbmc_project.State.Chassis.Transition.[Off - On - GracefulWarmReboot - Reboot ...]

Regards,
Francine

**Comment by edtanous** [comment]
Please ask questions to the OpenBMC mailing list, per the instructions in the github templates instructions.
