### ISSUE TITLE
bmcweb is crashing when built using sdk 

### ISSUE THREAD

**Issue by vinodchitrali** [openbmc/bmcweb#207]
**Describe the bug**
If the bmcweb is built using SDK, the process crashes with following message
```
root@romulus:~# journalctl -u bmcweb
...
Jun 02 15:02:30 romulus systemd[1]: Started Start bmcweb server.
Jun 02 15:02:30 romulus bmcweb[956]: terminate called after throwing an instance of 'std::logic_error'
Jun 02 15:02:30 romulus bmcweb[956]:   what():  basic_string::_M_construct null not valid
Jun 02 15:02:32 romulus systemd[1]: bmcweb.service: Main process exited, code=dumped, status=6/ABRT
Jun 02 15:02:32 romulus systemd[1]: bmcweb.service: Failed with result 'core-dump'.
root@romulus:~#
```

**Environment**
What OpenBMC platform was this found on?
       all , tried on romulus 
What specific OpenBMC versions did you use? 
      master 

**To Reproduce**
Steps
1) Build bmcweb from sdk and strip the binary (`arm-openbmc-linux-gnueabi-strip builddir/bmcweb`)
2) stop bmcweb service in qemu
3) Copy bmcweb to qemu 
4) restart bmcweb service

```
root@romulus:~# journalctl -u bmcweb
...
Jun 02 15:02:30 romulus systemd[1]: Started Start bmcweb server.
Jun 02 15:02:30 romulus bmcweb[956]: terminate called after throwing an instance of 'std::logic_error'
Jun 02 15:02:30 romulus bmcweb[956]:   what():  basic_string::_M_construct null not valid
Jun 02 15:02:32 romulus systemd[1]: bmcweb.service: Main process exited, code=dumped, status=6/ABRT
Jun 02 15:02:32 romulus systemd[1]: bmcweb.service: Failed with result 'core-dump'.
root@romulus:~#
```

**Is this a regression**
Has this behavior worked in the past?  If yes, on which commit did it work, and
what commit was broken?
       tried with couple of previous commits but no luck !

**Comment by edtanous** [comment]
This doesn't sound like a regression, which tells me this workflow never worked in the first place?  I've never used the SDK, so I don't have any help I can give aside from making sure that your SDK and BMC firmware are running on exactly the same version.  The error you're getting looks like it could be something to do with libc incompatibilities, but that's just a guess.

**Comment by edtanous** [comment]
Is this still an issue?

**Comment by edtanous** [comment]
Closing due to lack of response.
