### ISSUE TITLE
EthernetInterface under Manager should require ConfigureManager privilege

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/bmcweb#209]
**Describe the bug**
BMCWeb implements a Redfish `EthernetInterface` at URI /redfish/v1/Managers/bmc/EthernetInterfaces/eth0.
Permission to access this URI is controlled by Redfish [PrivilegeRegistry](https://redfish.dmtf.org/registries/Redfish_1.1.0_PrivilegeRegistry.json) entry for EthernetInterface which (for example) specifies the `ConfigureComponents` privilege is needed to perform the `PATCH` operation.
So BMCWeb hard-coded this into the [implementation of /redfish/v1/Managers/bmc/EthernetInterfaces/<str>](https://github.com/openbmc/bmcweb/blob/b282a4380670e5232e7b6f9a08234d3bdbadb5ff/redfish-core/lib/ethernet.hpp#L1880)

However, this permission value does not take into account the PrivilegeRegistry SubordinateOverride (Redfish spec DSP0266 > Security details > Authorization > Redfish service operation-to-privilege mapping > Subordinate override) which shows that when the `EthernetInterface` is subordinate to a `Manager->EthernetInterfaceCollection` then the PATCH operation shall require the `ConfigureManager` privilege.  In this case (referring to the URI above), the "bmc" is a `Manager`, and the `EthernetInterfaces` is an `EthernetInterfaceCollection`.

So, the various hard-coded permissions should be changed to match the PrivilegeRegistry (change several from `ConfigureComponents` to `ConfigureManager`).  When this is done, only a BMC Administrator will be able to modify the network interfaces.

**Environment**
What OpenBMC platform was this found on?
What specific OpenBMC versions did you use?

**To Reproduce**
Steps to reproduce the behavior: Not applicable.
Create an Administrator user and an Operator user, and try to work with an `EthernetInterface`.

**Is this a regression**
I believe this was the behavior from the beginning of time.

**Comment by gtmills** [comment]
Check out https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43939

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/45469/4/redfish-core/lib/ethernet.hpp should resolve this

**Comment by edtanous** [comment]
Believe the aforementioned patchset should've resolved this.  Closing as fixed.
