### ISSUE TITLE
BMC Web builds but doesn't run

### ISSUE THREAD

**Issue by paulnegz** [openbmc/bmcweb#210]
**Bug**
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  assign: Bad file descriptor
Aborted

**Environment**
OpenBMC platform on Ubuntu focal
OpenBMC current master branch?

**To Reproduce**
Ran sudo ./bmcweb
Similar to #148

**Comment by edtanous** [comment]
Do you have a valid dbus configuration on your system?  One source of this exception is when bmcweb can't connect to dbus on startup.

**Comment by paulnegz** [comment]
> Do you have a valid dbus configuration on your system? One source of this exception is when bmcweb can't connect to dbus on startup.

yeah. I found out it was a permissions issue. However, when I try to make redfish request to all API's that aren't whitelisted I get an internal service error.  I tried disabling authentication in the meson build but it still required log in credentials

**Comment by paulnegz** [comment]
![error](https://user-images.githubusercontent.com/37233089/122981690-a778d580-d35f-11eb-98e3-ac6535fee090.JPG)
![trace](https://user-images.githubusercontent.com/37233089/122981693-a778d580-d35f-11eb-9c0e-c0482009d5f1.JPG)

**Comment by edtanous** [comment]
Have you installed bmcweb, or just run it from the build folder?  There are pam configurations that the install script needs for authentication to work.  Alternatively you can just disable authentication altogether, but you haven't provided a lot of detail on what you're trying to accomplish, so I'm a little at a loss for how to help you more.

**Comment by paulnegz** [comment]
So I ran the build script `build_x86.sh` that created a builddir and inside of that directory I try to run `./bmcweb`. I am able to make redfish equest to whitelisted urls.

**Comment by paulnegz** [comment]
![whitelist](https://user-images.githubusercontent.com/37233089/122982464-85338780-d360-11eb-9d9a-085a18274a88.JPG)

**Comment by edtanous** [comment]
You need to run make/ninja install and restart PAM before pam will work on your machine.  Yes, whitelisted urls will work just fine because they don't require any authentication.

**Comment by paulnegz** [comment]
yeah, I just mentioned whitelisted urls working fine because I don't think it's a problem with the installation of bmcweb. I did run ninja install. 
![installBMC](https://user-images.githubusercontent.com/37233089/122987438-37218280-d366-11eb-8618-eaaf088eb4d5.JPG)

**Comment by edtanous** [comment]
That last file (installed into /etc/pam.d) is usually the one that causes this problem.  There's likely some incompatibility with your machines version of PAM.  As an easy first step, you might try compiling bmcweb with logging enabled to see the exact return code PAM is giving you, but I suspect you'll need to debug some.  If I had to guess, there's something messed up with your redfish group.

**Comment by paulnegz** [comment]
should the redfish group be set to root?
