### ISSUE TITLE
Segmentation fault when /subscribe request is called

### ISSUE THREAD

**Issue by esm** [openbmc/bmcweb#212]
**Describe the bug**
When I run webui-vue and login, I get the Proxy error in the image below which says that it cannot proxy the subscribe request from my webui-vue which runs on port 8000 to bmcweb which runs on port 18080. The error comes from line 1187 in  bmcweb/http/routing.hpp
**Environment**: Linux

**To Reproduce**
1. Run the command '....' ./bmcweb in builddir and run npm run serve in webui-vue
2. See error: Proxy error: Could not proxy request /subscribe from localhost:8000 to https://localhost:18080/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

3. Expected behavior was '....' no error

**Is this a regression**
Has this behavior worked in the past?   no it has not worked in the past

![webui-vuee](https://user-images.githubusercontent.com/71355487/123311642-66b2c500-d4f5-11eb-8421-54d8771a6baf.PNG)
![bmcweb_subscribe](https://user-images.githubusercontent.com/71355487/123311385-205d6600-d4f5-11eb-9988-a1edf1faca5f.PNG)

**Comment by edtanous** [comment]
Please use and fill out the bug template.  It contains information we’ll need to be able to help you.

**Comment by esm** [comment]
> Please use and fill out the bug template. It contains information we’ll need to be able to help you.

thanks, I just did

**Comment by edtanous** [comment]
I don’t see the issue having been updated with the questions in the template…..

**Comment by esm** [comment]
> I don’t see the issue having been updated with the questions in the template…..

Updated

**Comment by edtanous** [comment]
Ubuntu is not an openbmc platform, and “latest” is not a specific Sha1 version.  Please update with your actual environment.

**Comment by esm** [comment]
> Ubuntu is not an openbmc platform, and “latest” is not a specific Sha1 version. Please update with your actual environment.
I'm running bmcweb, not openbmc. I don't think it has a platform

**Comment by edtanous** [comment]
Bmcweb is not a standalone application.  It relies significantly on the OpenBmc environment.  If you are expecting it to function without OpenBMC, that’s possible in the architecture, but not something the current upstream bmcweb code supports well.

**Comment by esm** [comment]
Do you suggest I clone openbmc as a whole before trying to run bmcweb ?

**Comment by edtanous** [comment]
It’s hard to make a suggestion when you haven’t really talked about what you’re hoping to accomplish.

**Comment by esm** [comment]
I am trying to run webui-vue (front-end) and bmcweb (back-end) but I get the proxy error ( ```
Proxy error: Could not proxy request /subscribe from localhost:8000 to https://localhost:18080/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)
``` ) above when I log into webui-vue 
![webuii](https://user-images.githubusercontent.com/71355487/123320065-4425a980-d4ff-11eb-8993-b9a3cc9595ed.PNG)

**Comment by edtanous** [comment]
Webui-vue and bmcweb are designed to be run on a BMC.  As-is they would not be very useful on a desktop environment.  You still haven’t talked about what you’re hoping to accomplish by doing this.

**Comment by edtanous** [comment]
Closing from lack of discussion for the last month.  If you have new use cases you'd like to explore, please bring them to the OpenBMC discord channel, which is much more apt to discuss new use cases (ie running bmcweb and webui-vue in standalone mode).
