### ISSUE TITLE
Standalone docker build fails due to unsatisfied dependencies.

### ISSUE THREAD

**Issue by michalbielecki** [openbmc/bmcweb#214]
**Describe the bug**
If bmcweb is built using dedicated docker files or shell script it will fail due to unsatisfied dependency. This probably happens due to server running out of bandwidth near the end of the month.

**Environment**
What OpenBMC platform was this found on?
I don't think it's relevant.

What specific OpenBMC versions did you use?
Not sure if it's relevant since I'm trying to build bmcweb component in standalone mode.
SRCREV of bmcweb: b937830fe5a7adba40e63f6059bf2c543733de33

**To Reproduce**
1. Run 'build_x86_docker.sh'
2. Build fails with following message:

>Run-time dependency Boost found: NO
>Downloading boost source from https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz
>HTTP Error 403: Forbidden
>A fallback URL could be specified using source_fallback_url key in the wrap file
>could not get https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz is the internet available?
>Subproject  boost is buildable: NO (disabling)
>WARNING: include_directories sandbox violation!
>The project is trying to access the directory subprojects/boost_1_75_0/ which belongs to a different
>subproject. This is a problem as it hardcodes the relative paths of these two projeccts.
>This makes it impossible to compile the project in any other directory layout and also
>prevents the subproject from changing its own directory layout.
>Instead of poking directly at the internals the subproject should be executed and
>it should set a variable that the caller can then use. Something like:
>In subproject
>some_dep = declare_depencency(include_directories: include_directories('include'))
>In parent project
>some_dep = depencency('some')
>executable(..., dependencies: [some_dep])
>This warning will become a hard error in a future Meson release.
>meson.build:310:2: ERROR: Include dir subprojects/boost_1_75_0/ does not exist.

**Is this a regression**
Not sure.

**Comment by edtanous** [comment]
The docker build has never been well supported given its lack of use.  If you're interested in supporting it and maintaining, feel free to engage further on discord or the mailing list, and we can work on improving it, but we don't currently have a maintainer that relies on it, so it tends to break from time to time.

**Comment by manojkiraneda** [comment]
@michalbielecki this should be fixed with https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43405 , can you please retry with latest master. I was able to build bmcweb with docker.

**Comment by gtmills** [comment]
@michalbielecki Still a problem or can this be closed?

**Comment by edtanous** [comment]
No response from submitter, and patch to fix is merged.  Closing.
