### ISSUE TITLE
System log entries should be deleted by ipmi command.

### ISSUE THREAD

**Issue by ashwiniudupa1** [openbmc/bmcweb#216]
**Describe the bug**
Redfish SEL System log entries should be deleted by ipmi command. 
Also sel entries can't be deleted by redfish command.

**Environment**
What OpenBMC platform was this found on? 
All platforms
What specific OpenBMC versions did you use?
d7eca3aaccf58555fa5619465140d3b71204720c

**To Reproduce**
#Step 1 : Check sel list.
#Step 2 : Check Redfish System log entries
#Step 3 : Clear sel list by ipmi cmd.
#Step 4 : Check Redfish System log entries.      <<== Issue : The SEL entries should be deleted by ipmi command. 
#Step 5 : Check sel list.

#Step 1 : Check sel list
root@lina-virtual-machine:~# ipmitool -C 17 -I lanplus -H 10.6.141.69 -U root -P 0penBmc  sel list
   1 | 05/20/2021 | 15:24:45 | Temperature #0x30 | Upper Critical going high | Asserted
   2 | 05/20/2021 | 15:25:00 | Temperature #0x30 | Upper Critical going high | Asserted

#Step 2 : Check  Redfish System log entries
root@lina-virtual-machine:~# curl -basic -u root:0penBmc -X GET https://10.6.141.69/redfish/v1/Systems/system/LogServices/EventLog/Entries -k -i
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:
Content-Type: application/json
Date: Thu, 20 May 2021 15:42:02 GMT
Content-Length: 1231

{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "Collection of System Event Log Entries",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1621524285",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2021-05-20T15:24:45+00:00",
      "EntryType": "Event",
      "Id": "1621524285",
      "Message": "SEL Entry Added: 2C0401300109FFFF",
      "MessageArgs": [
        "2C0401300109FFFF"
      ],
      "MessageId": "OpenBMC.0.1.SELEntryAdded",
      "Name": "System Event Log Entry",
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1621524300",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2021-05-20T15:25:00+00:00",
      "EntryType": "Event",
      "Id": "1621524300",
      "Message": "SEL Entry Added: 2C0401300109FFFF",
      "MessageArgs": [
        "2C0401300109FFFF"
      ],
      "MessageId": "OpenBMC.0.1.SELEntryAdded",
      "Name": "System Event Log Entry",
      "Severity": "OK"
    }
  ],
  "Members@odata.count": 2,
  "Name": "System Event Log Entries"
}

#Step 3 : Clear sel list by ipmi cmd.
root@lina-virtual-machine:~#ipmitool -C 17 -I lanplus -H 10.6.141.69 -U root -P 0penBmc  sel  clear
Clearing SEL.  Please allow a few seconds to erase.

#Step 4 : Check  System log entries
root@lina-virtual-machine:~# curl -basic -u root:0penBmc -X GET https://10.6.141.69/redfish/v1/Systems/system/LogServices/EventLog/Entries -k -i
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:
Content-Type: application/json
Date: Thu, 20 May 2021 15:42:16 GMT
Content-Length: 1231

{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "Collection of System Event Log Entries",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1621524285",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2021-05-20T15:24:45+00:00",
      "EntryType": "Event",
      "Id": "1621524285",
      "Message": "SEL Entry Added: 2C0401300109FFFF",
      "MessageArgs": [
        "2C0401300109FFFF"
      ],
      "MessageId": "OpenBMC.0.1.SELEntryAdded",
      "Name": "System Event Log Entry",
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1621524300",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2021-05-20T15:25:00+00:00",
      "EntryType": "Event",
      "Id": "1621524300",
      "Message": "SEL Entry Added: 2C0401300109FFFF",
      "MessageArgs": [
        "2C0401300109FFFF"
      ],
      "MessageId": "OpenBMC.0.1.SELEntryAdded",
      "Name": "System Event Log Entry",
      "Severity": "OK"
    }
  ],
  "Members@odata.count": 2,                      <<== Issue: should be deleted by ipmi command. 
  "Name": "System Event Log Entries"
}

#Step 5 :Check sel list
root@lina-virtual-machine:~#ipmitool -C 17 -I lanplus -H 10.6.141.69 -U root -P 0penBmc  sel list
SEL has no entries                           <<== Correct

**Is this a regression**
No

**Comment by edtanous** [comment]
"All platforms" is not a platform, and because there's two implementations of this feature, it's important to know what platform you reproduced this on.

**Comment by edtanous** [comment]
closing due to lack of response from submitter
