### ISSUE TITLE
Internal Server Error when I try to make redfish requests to bmcweb IP 

### ISSUE THREAD

**Issue by esm** [openbmc/bmcweb#217]
**Describe the bug**
Internal Server Error when I try to make redfish requests to BMC IP 

**Environment**
What OpenBMC platform was this found on? romulus
What specific OpenBMC versions did you use? master

**To Reproduce**
1. Get request from POSTMAN https://{bmc_ip)/redfish/v1/AccountService
2. See error Internal Server Error 
3. Expected behavior was json response

**Is this a regression**
Has this behavior worked in the past?  not worked in the past

**Comment by edtanous** [comment]
Please enable debug logging on bmcweb and post the logs when running this test.  They will likely point to a specific failure on your system.

Based on your comment I'm assuming this was actually tested on a physical romulus system?  Or was this a qemu build?  Romulus was created long before Redfish, and could be missing some system components to make the whole stack work, so it's not surprising it has some issues.

**Comment by esm** [comment]
Debug statements:
(2021-07-26 19:52:08) [ERROR "http_connection.hpp":504] 0x563c760ed950 async_read_header 274 Bytes
(2021-07-26 19:52:08) [DEBUG "authorization.hpp":106] [AuthMiddleware] X-Auth-Token authentication
(2021-07-26 19:52:08) [DEBUG "authorization.hpp":123] [AuthMiddleware] Cookie authentication
(2021-07-26 19:52:08) [DEBUG "authorization.hpp":43] [AuthMiddleware] Basic authentication
(2021-07-26 19:52:08) [DEBUG "authorization.hpp":65] [AuthMiddleware] Authenticating user: eliane
(2021-07-26 19:52:08) [DEBUG "authorization.hpp":66] [AuthMiddleware] User IPAddress: 0.0.0.0
(2021-07-26 19:52:08) [DEBUG "timer_queue.hpp":53] timer add inside: 0x563c76042460 191
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":753] 0x563c760ed950 timer added: 0x563c76042460 191
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":563] Starting slow deadline
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":573] QueryParams: 
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":598] 0x563c760ed950 doRead
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":605] 0x563c760ed950 async_read 0 Bytes
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":699] 0x563c760ed950 timer cancelled: 0x563c76042460 191
(2021-07-26 19:52:08) [DEBUG "timer_queue.hpp":53] timer add inside: 0x563c76042460 192
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":753] 0x563c760ed950 timer added: 0x563c76042460 192
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":699] 0x563c760ed950 timer cancelled: 0x563c76042460 192
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":476] Fetch the client IP address
(2021-07-26 19:52:08) [INFO "http_connection.hpp":326] Request:  0x563c760ed950 HTTP/1.1 GET /redfish/v1/AccountService 127.0.0.1
(2021-07-26 19:52:08) [DEBUG "routing.hpp":1300] Matched rule '/redfish/v1/AccountService/' 2 / 4
(2021-07-26 19:52:08) [ERROR "routing.hpp":1318] GetUserInfo failed...
(2021-07-26 19:52:08) [DEBUG "http_response.hpp":120] calling completion handler
(2021-07-26 19:52:08) [DEBUG "http_response.hpp":123] completion handler was valid
(2021-07-26 19:52:08) [INFO "http_connection.hpp":411] Response: 0x563c760ed950 /redfish/v1/AccountService 500 keepalive=1
(2021-07-26 19:52:08) [DEBUG "timer_queue.hpp":53] timer add inside: 0x563c76042460 193
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":753] 0x563c760ed950 timer added: 0x563c76042460 193
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":657] 0x563c760ed950 doWrite
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":665] 0x563c760ed950 async_write 558 bytes
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":699] 0x563c760ed950 timer cancelled: 0x563c76042460 193
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":683] 0x563c760ed950 Clearing response
(2021-07-26 19:52:08) [DEBUG "http_response.hpp":101] 0x563c760efd58 Clearing response containers
(2021-07-26 19:52:08) [DEBUG "http_connection.hpp":496] 0x563c760ed950 doReadHeaders

**Comment by edtanous** [comment]
GetUserInfo failed... implies that your user management isn't set up or is non functional on your system.  This does not appear to be a bmcweb bug.

**Comment by esm** [comment]
Thanks. Is user management an entire different repo? How do I set it up?

**Comment by edtanous** [comment]
Can you please answer the questions posed previously.

Yes, user management is a different repo.  Setting them up is outside the scope of this bug tracker.  For the moment I'm going to close this as a setup issue.  Romulus predates Redfish, so it's unsurprising that it doesn't work, as it was never configured to work.  Feel free to engage people either on the mailing list or on discord if you need help setting things up.
