### ISSUE TITLE
Redfish: Manager bmc UUID is 'OpenBMC'

### ISSUE THREAD

**Issue by gtmills** [openbmc/bmcweb#22]
`curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc`
```
...
  "UUID": "OpenBmc"
```
Redfish-Service-Validator throws an error for this: 
ERROR - UUID: String 'OpenBmc' does not match pattern ''[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}''

Need a change here: https://github.com/openbmc/bmcweb/blob/1b6b96c570fdf7ca5c643f3d0776581656e78070/redfish-core/lib/managers.hpp#L698

**Comment by edtanous** [comment]
Should be resolved here: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/16792/
