### ISSUE TITLE
Implement ConfigureSelf for EventService Subscriptions

### ISSUE THREAD

**Issue by patelabhishek9893** [openbmc/bmcweb#220]
EventService-Subscriptions allow users to create and subscribe to events.

"ConfigureComponents" privilege allows the Operator and Administrator users to create a subscription. in addition, "ConfigureManager" has the ability to manage all subscriptions for all users, which gives the Administrator user ability to PATCH, POST, PUT and DELETE subscriptions for all user.

EventService-Subscriptions need "ConfigureSelf" Privilege implementation, allowing Operator users to PATCH, POST, PUT and DELETE only self subscriptions.

Basic Description:
bmcweb has EventServiceManager, which manage all subscription. EventServiceManager retrieves and saves all configurations into "/var/lib/bmcweb/eventservice_config.json" file.

implementation:

1) For each Operation PATCH, POST, PUT and DELETE, we need to implement if a user is "ConfigureSelf," then only they can perform the operation on their subscription.

2) For the "ConfigureSelf" implementation, we must map each user with its own subscription. Moreover, we need to save that info into eventservice_config.json too.

**Comment by edtanous** [comment]
Please see the bug template on "enhancements".  If this is a change you'd like to see, feel free to discuss on the mailing list or discord, but we generally do not use this bug tracker to track enhancements like this.
