### ISSUE TITLE
NTPServers are hard-coded for eth0

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/bmcweb#223]
**Describe the bug**
bmcweb is getting and patching NTPServers only from "/xyz/openbmc_project/network/eth0" object.

See
* https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/network_protocol.hpp#L46
* https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/network_protocol.hpp#L269

The code is using the hard-coded `/xyz/openbmc_project/network/eth0` DBus object to get and set the NTP servers.

So a BMC using a different ethernet device will have a broken NTP config on Redfish.

Probably we should config a global config for NTP servers?

**Comment by gtmills** [comment]
Was added here: https://github.com/openbmc/bmcweb/commit/20e6ea5dbfaa04f4298116281ddfb997847189ce
@raviteja-b FYI

**Comment by lxwinspur** [comment]
I hit the same error, we are using `eth1` instead of `eth0`. and when we run the `setNTP` method to asynchronous NTP, we can not receive any data, it will return `timeout`. 

If we change `/xyz/openbmc_project/network/eth0` to `/xyz/openbmc_project/network/eth1` manually, it works fine.

**Comment by edtanous** [comment]
Ideally this should be using the mapper to look up the NTP interface.  A gerrit review would be welcome to fix this.

**Comment by lxwinspur** [comment]
Fix this issue by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/4734

**Comment by edtanous** [comment]
Fixed on master.  Please reopen if you're still having issues.
