### ISSUE TITLE
Method patch not allowed

### ISSUE THREAD

**Issue by Abdelfel** [openbmc/bmcweb#229]
Hello,
If this is the wrong place to post this please let me know.
I am using the version of bmcweb with the classes.
I am trying to patch an attribute on Memory schema
Memory.hpp:
```
`class Memory : public Node
{
  public:
    /*
     * Default Constructor
     */
    Memory(App& app) :
        Node(app, "/redfish/v1/Systems/system/Memory/<str>/", std::string())
    {
        entityPrivileges = {
            {boost::beast::http::verb::get, {{"Login"}}},
            {boost::beast::http::verb::head, {{"Login"}}},
            {boost::beast::http::verb::patch, {{"ConfigureComponents"}}},
            {boost::beast::http::verb::put, {{"ConfigureComponents"}}},
            {boost::beast::http::verb::delete_, {{"ConfigureComponents"}}},
            {boost::beast::http::verb::post, {{"ConfigureComponents"}}}};
    }

  private:
    /**
     * Functions triggers appropriate requests on DBus
     */
    void doGet(crow::Response& res, const crow::Request&,
               const std::vector<std::string>& params) override
    {..}
void doPatch(crow::Response& res, const crow::Request& req,  //this is the function I added
                 const std::vector<std::string>& params) override
    {...}
`
```

when I try to pass the patch command, it says "Method not allowed"
![image](https://user-images.githubusercontent.com/69520785/146197270-e65d9c93-c8c2-4d45-9772-e7d28c1d3baa.png)

are we supposed to allow a certain method that didn't exist originally on a schema ?
thank you

**Comment by edtanous** [comment]
You've posted content that is clearly from an older version of bmcweb, as shown by the fact that you're using the node class.  Also, the bug template that you've ignored politely requests that you ask these kinds of questions on the openbmc discord or mailing list.  Please direct your questions there, although I suspect the first answer will be to re-test on master, given you're on a fairly old version of bmcweb.
