### ISSUE TITLE
How can process other redfish requests during the execution of doGet() function？

### ISSUE THREAD

**Issue by asdadjfh** [openbmc/bmcweb#230]
Excuse me?
1. When two redfish requests are sent at the same time, other requests cannot be executed during the execution of doGet() function. 
   Other redfish requests will be processed only after the execution of doGet()?
2. If I want to implement this function, that is can still continue to process other redfish requests during the execution of doGet() function, what needs to be done?

Thanks.

**Comment by edtanous** [comment]
You seem to have ignored the bug templates, which direct you to ask these types of questions on the OpenBMC discord or mailing list.  Please follow the directions, and there will likely be people that are able to help you with your questions.
