### ISSUE TITLE
Update Crow to last version ?

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#233]
Hi,
Recent versions of Crow have a App<Middleware> feature, allowing overriden before_handle / after_handle , that would be so helpful in bmcweb architecture !

Is there a roadmap to integrate and to follow new Crow versions ?

Kind Regards,
Francine

**Comment by edtanous** [comment]
Please follow the bug templates in place for question, which would've directed you to ask questions to the mailing list or to discord, not in github.  Happy to follow up in the correct forum.

**Comment by frsauvage** [comment]
I apologize,
Regards
