### ISSUE TITLE
Is it possible to Rename KVM to Virtual Console?

### ISSUE THREAD

**Issue by manojdesd** [openbmc/bmcweb#234]
Issue: Is it possible to rename KVM to Virtual Console?

OpenBMC version : 2.9

Can we rename KVM to virtual console as it is difficult for the users to understand the keyword "KVM"?
Virtual console be understandable and easy to configure for the users.

Please share your insights on this.

**Comment by edtanous** [comment]
Please follow the bug templates in place for question, which would've directed you to ask questions to the mailing list or to discord, not in github. Happy to follow up in the correct forum.
