### ISSUE TITLE
Unable to create the system dump type

### ISSUE THREAD

**Issue by nibin-chacko** [openbmc/bmcweb#235]
**Describe the bug**
Not able to create the logs for the dump type  "system"

**Environment**

We are running in the aspeed - 2500.
OpenBMC revision is 832fc9ab539ffb54ec1140db1239881a81daa034

**To Reproduce**

- Run curl command to create the task for the dump type "system".
- Give bmc IP,bmc username amd bmc password instead of bf_ip,bf_username and bf_password.
- It throws 500 internal error and does not create the task for the dump type "system"

```
curl -k -H "X-Auth-Token: $token" -H 'Content-Type: application/json' -X POST -d '{"DiagnosticDataType":"OEM",
"OEMDiagnosticDataType":"System;bf_ip=10.xx.xx.xx;bf_username=xxxxx;bf_password=xxxxxx"}'
[https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData]()
```
![image](https://user-images.githubusercontent.com/64701081/161307523-5f356750-a917-41cd-8733-8e7c4905afe9.png)

Please correct me if I gave the command as wrong.

**Comment by edtanous** [comment]
Please don't ignore the bug template as you've done above.  The fields in the bug template are there for a reason and help us to quickly help to triage issues without having to repeat the same requests.  Please update your bug with the fields that the template requests, and we can go from there.

**Comment by edtanous** [comment]
Thanks for getting your bug updated.

> We are running in the aspeed - 2500.

This isn't enough information to answer your questions.  What platform are you on.  If it's not one of the platforms that exists in upstream, or you've made local modifications it severely limits our ability to help triage bugs from you, and it would help a lot if you could reproduce on one of those platforms, without any local patches.

**Comment by edtanous** [comment]
No response from submitter.  Closing.
