### ISSUE TITLE
/redfish/v1/Systems/system/LogServices/PostCodes/Entries/BX-X format different to /redfish/v1/Systems/system/LogServices/EventLog/Entries/XXXX 

### ISSUE THREAD

**Issue by ecnickhuang** [openbmc/bmcweb#236]
[Describtion]
Use the DMTF Redfish-Interop-Validator test to test will have "PostCodes entries" fail problem.
 
[OpenBMC platform]

meta-ibm/conf/machine/witherspoon-tacoma.conf
  
and can not be tested in QEMU

[bmcweb versions master]

**To Reproduce**

1. Use the DMTF Baseline tool to test and create reports.

git clone https://github.com/DMTF/Redfish-Interop-Validator.git

git clone https://github.com/opencomputeproject/OCP-Profiles.git

Modify IP address in config.ini to OpenBMC correct one and use the command to start the test.  

**python3 RedfishInteropValidator.py  OCP-Profiles/OCPBaselineHardwareManagement.v1_0_1.json --debugging -c config.ini**

2. Check HTML report like the following screenshot

We can find "Failure" in redfish/v1/Systems/system/****LogServices/**PostCodes****/Entries/B1-1** 

![image](https://user-images.githubusercontent.com/76081972/173273722-17276050-fc95-48b4-8ed3-d95123162417.png)

"FAIL" one entry body
![image](https://user-images.githubusercontent.com/76081972/173273644-6d463eb0-e565-4c1d-93a3-8c87bf6b54a8.png)

4. Expected behavior like :

But in /redfish/v1/Systems/system/**LogServices/**EventLog/Entries**/15** is "PASS"

![image](https://user-images.githubusercontent.com/76081972/173273872-533a7ad8-6964-4bf4-9fe6-1ef936915d90.png)

"PASS" one entry body
![image](https://user-images.githubusercontent.com/76081972/173273982-fbb1ad71-ad41-4000-a749-84376c8b61d4.png)

The creation of PostCodes/B1-1 is not the same as event log entries/15 and causes the error testing result.

[Has this behavior worked in the past?]  
Not tested this item before.

**Comment by edtanous** [comment]
Please fill out the bug template that should've been presented when you started filling out the bug.  It is there to help us correctly triage issues in an efficient manner.

**Comment by edtanous** [comment]
Based on the screenshots given, it isn't clear how the postcodes as implemented on whitherspoon would be able to pass the OCP baseline profile, given that it implemented no message registry, so therefore bmcweb doesn't have the data available to publish message or severity.  Created and EntryType could be added.  I don't have a witherspoon to even test with, so gerrit reviews to fix the problem are welcome.

**Comment by edtanous** [comment]
Any more progress here?

**Comment by jiaqingz-intel** [comment]
I also found this issue, it's because currently `/redfish/v1/Systems/system/LogServices/PostCodes/Entries/B1-1` is misformatted and actually returns a LogEntryCollection. I've submmited a patch at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57773

**Comment by edtanous** [comment]
Aforementioned patch merged.  Closing.
