### ISSUE TITLE
meson builddir not available

### ISSUE THREAD

**Issue by fishermess** [openbmc/bmcweb#237]
![WKJ@_DN7XFH6DZN4D9J3PSK](https://user-images.githubusercontent.com/40992360/178180248-01a22621-f099-4642-9009-00323f4d176f.png)

**Comment by edtanous** [comment]
Please fill out the bug template as requested.  From the looks of it, you're trying to run a meson build from within a devtool modifiy copy of bmcweb.  If you want to build bmcweb locally, the commands are documented in the repo, if you want to build in yocto, that is done via bitbake, not meson.  Mixing the two is not something anyone within the project supports, but if there's patchsets to improve the behavior, feel free to submit them to code review and we will take a look, but building in a combo of yocto and local is not a building mechanism that any of the maintainers use, so it's likely it doesn't work or will regress often.

**Comment by fishermess** [comment]
> 

Thanks for your reply.I am sorry for that I didn't express what I want to ask for well.I just wonder why I cannot get pass 'meson 
builddir'(without option the result is same as it) locally, but in yocto it works well.

**Comment by gtmills** [comment]
@fishermess Can this issue be closed?

**Comment by edtanous** [comment]
No response from submitter;  Bug template has still not been filled out.  Closing.  Feel free to reopen if this is still and issue, and the bug template can be filled out.

**Comment by wosayttn** [comment]
Anyone can tell me how to do the native build using 'meson builddir && ninja -C builddir' command on x86_64 platform successfully? Is it available? or I miss some dependency?

![image](https://user-images.githubusercontent.com/15135795/215930963-e88ffe38-399c-4ec2-bb64-451a7486e05f.png)
[bmcweb_build.log](https://github.com/openbmc/bmcweb/files/10552764/bmcweb_build.log)

**Comment by williamspatrick** [comment]
> Anyone can tell me how to do the native build using 'meson builddir && ninja -C builddir' command on x86_64 platform successfully? Is it available? or I miss some dependency?
> 
> ![image](https://user-images.githubusercontent.com/15135795/215930963-e88ffe38-399c-4ec2-bb64-451a7486e05f.png) [bmcweb_build.log](https://github.com/openbmc/bmcweb/files/10552764/bmcweb_build.log)

Please don’t reply to already closed issues if you can’t tell they are similar problems. 

You need a newer GCC. Looks like you have 10 and we need 12.

**Comment by wosayttn** [comment]
@williamspatrick 

Sorry, I just correct related to meson build issue in same thread.
I upgraded my UBUNTU distro to 22.04 and upgrade g++12.
It's okay to build the bmcweb successfully. Thanks for your hint.
