### ISSUE TITLE
bmcweb's REST API doesn't support method return data

### ISSUE THREAD

**Issue by spinler** [openbmc/bmcweb#24]
Calling a D-Bus method via REST with /path/action/method needs to support returning the method data, if there is any.  It already has the introspection data, so it knows the signature.  It just needs to grab the data from the d-bus message and convert it to the proper form for the JSON response.

I plan on working on this.

**Comment by spinler** [comment]
@edtanous can you assign this to me?

**Comment by edtanous** [comment]
Done
