### ISSUE TITLE
User list is not displayed if any user is not in any of the OpenBMC groups

### ISSUE THREAD

**Issue by Kitsok** [openbmc/bmcweb#244]
For security reasons, I've restricted ADMIN user from being able to log in via SSH and restricted root from using IPMI, RedFish, etc.

This caused malfunction of "User management" subpage in web-interface, it became empty.
In the debug log I observe "Invalid user role" message.

It's caused by this block of code:
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/account_service.hpp#L1824

When a user is found with no membership in *-priv groups, the upper cycle is terminated and no output is provided to web-interface.

Here is the fix:
```diff --git a/redfish-core/lib/account_service.hpp b/redfish-core/lib/account_service.hpp
index 3a8ffbc9..e9a19a56 100644
--- a/redfish-core/lib/account_service.hpp
+++ b/redfish-core/lib/account_service.hpp
@@ -90,7 +90,7 @@ inline std::string getRoleIdFromPrivilege(std::string_view role)
     {
         return "Operator";
     }
-    return "";
+    return "NoAccess";
 }
 inline std::string getPrivilegeFromRoleId(std::string_view role)
 {
@@ -106,7 +106,7 @@ inline std::string getPrivilegeFromRoleId(std::string_view role)
     {
         return "priv-operator";
     }
-    return "";
+    return "NoAccess";
 }
 
 /**

```

**Comment by edtanous** [comment]
Per the bug template and developing guide, please submit these to gerrit, or start a discussion on the mailing list.

Based on the fact that you’ve modified other pieces of code in your build, please make sure you articulate in your commit message what the issue is, and what changes to which components are required to be changed.
