### ISSUE TITLE
ldap user can able to create an session with invalid group name but not able to delete it's session.

### ISSUE THREAD

**Issue by Ganesan149** [openbmc/bmcweb#246]
**Describe the bug** An authenticated ldap user with invalid group name can login but cannot log out.

**Environment** AST2600 SOC Related Platform, not in QEMU.

**To Reproduce** Steps to reproduce the behavior:

1. Configure LDAP with below role mapping.
          
       {'LDAP': {'RemoteRoleMapping': [{'LocalRole': 'Administrator', 'RemoteGroup': 'Invalid_LDAP_Group_Name'}]}}

   ->  Create session with LDAP user. 
           Method : POST
           URI : /redfish/v1/SessionService/Sessions/

    -> DELETE the ldap session.
           Method : Delete
           URI : /redfish/v1/SessionService/Sessions/<sessionid>

2. The logout fails with Forbidden(403)

3. Expect the logout would gets succeed, as login gets succeeds with invalid group name.

**Comment by prkatti1** [comment]
If login is allowed, logout also should be allowed.

**Comment by edtanous** [comment]
Please fill out the bug template as written.

**Comment by Ganesan149** [comment]
@edtanous 

where to get the template?

**Comment by Ganesan149** [comment]
@edtanous I have updated the bug as per template

**Comment by edtanous** [comment]
> @edtanous I have updated the bug as per template

Please don't delete the Environment section from the template.  it is important.

**Comment by Ganesan149** [comment]
> > @edtanous I have updated the bug as per template
> 
> Please don't delete the Environment section from the template. it is important.

@edtanous Added environment section in the bug.

**Comment by edtanous** [comment]
> Environment AST2600 SOC Related Platform, not in QEMU.

I'm going to assume based on you not listing the platform name that this isn't a supported platform, so it would appear that you've forked the OpenBMC project and added a new one.  While we appreciate bug reports, taking bug reports about forks is not something we have the capacity to handle at the moment, as we cannot know what changes you've made to the build tree.  If you reproduce this on an upstream platform, please reopen.
