### ISSUE TITLE
BMcweb.service: fail with result 'exit-code'

### ISSUE THREAD

**Issue by toravishivraj** [openbmc/bmcweb#247]

**Comment by edtanous** [comment]
Please fill out the bug template, as it gives us enough information to help triage the bug.  Alternatively, feel free to reach out to discord or email if you'd like more informal discussions about bugs.

**Comment by toravishivraj** [comment]
![Screenshot_2023-02-28-09-37-32-686_com microsoft teams](https://user-images.githubusercontent.com/36588075/221751871-e56f39ae-43b0-4d1a-85a1-1c0d3de61316.jpg)

**Comment by toravishivraj** [comment]
![IMG_20230228_093759](https://user-images.githubusercontent.com/36588075/221752492-2ee0f11c-5ee4-4509-8c02-e37d08ad9098.jpg)

**Comment by edtanous** [comment]
Again, please fill out the bug template.

**Comment by toravishivraj** [comment]
Please check the attached image for log.
I have added
 IMAGE _INSTALL_append +=" bmcweb"
In local.conf
& Added meta-webserver path in bblayers.conf

**Comment by edtanous** [comment]
> Please check the attached image for log.

this does not include all the information in the bug template.  Please include all the information in the bug template, or use one of the other more informal communication channels.

**Comment by toravishivraj** [comment]
Hi,
I am facing issues with starting bmcweb server

**Comment by edtanous** [comment]
Not enough information included to triage, and repeated requests to fill out the bug template have been ignored.  If you don’t have the bug information available, please engage on the openbmc mailing list or openbmc discord.
