### ISSUE TITLE
Internal Server Error when I try to make redfish requests In OpenBMC

### ISSUE THREAD

**Issue by toravishivraj** [openbmc/bmcweb#248]
Hi all 
Please check my below commands 

1) only this command works
 $ curl  -c cjar -k -X POST -H "Content-Type: application/json"  -d '{"data": ["root","password"] }'  https://bmcip/login
{
"data": "User 'root' logged in",
"message": "200" OK",
"status":"ok"
}

2) for token base auth it reply Internal Server Error
3) curl -k https://$bmc/redfish/v1 it reply with JSON but 
4) curl -k https://$bmc/redfish/v1/Manager or Chassis or System it reply with internal server error
5) how to take debug log
6) how to take IP address using redfish curl command from target device?
7) i am adding manually "css, img, js, index,favicon" in usr/share/www/ & add redfish Directory in var/log/ in final tar.xz image why? those not generated automatically in that directory of target image why?

My aim is get ip address from target device and show in network information on OpenBMC web page also tried with REST and Redfish curl command but it shows internal server error .
please reply 

Regard's
Toravi

**Comment by geissonator** [comment]
> curl -k https://$bmc/redfish/v1 it reply with JSON but
> curl -k https://$bmc/redfish/v1/Manager or Chassis or System it reply with internal server error

This implies your system doesn't support the Manager interface. Was it available under your initial redfish/v1 query?

It's not clear what configuration you're using. It may be best to start out with https://github.com/openbmc/docs/blob/master/development/dev-environment.md#download-and-start-qemu-session and boot a romulus session in QEMU. That model is run within OpenBMC CI and it's Redfish API's are tested.

You can look over https://github.com/openbmc/docs/blob/master/REDFISH-cheatsheet.md for relevant Redfish API's. Just be sure to set your "bmc" to include the port forward of the QEMU session when talking to it over curl.

**Comment by edtanous** [comment]
Please fill out the bug template.  It had information init that we need to triage your issue.

**Comment by toravishivraj** [comment]
Hi geissonator,
Thank you for Reply
1. This implies your system doesn't support the Manager interface--> how to verify it support or not
 2. Was it available under your initial redfish/v1 query?--> $ curl -k https://$bmc/redfish/v1 it reply with JSON it shows Manager or Chassis or System and etc 
3. my goal is display network information on on bmc web page for this which file from bmcweb and webui are required in final image? or how to add bmcweb and webui-vue in local config?
4. and also parallel i had build image for Romulus Qemu but it shows below error

   Verifying Hash Integrity ... sha256+ OK
   Booting using the fdt blob at 0x203706c8
   Loading Kernel Image ... OK
   Loading Ramdisk to 89e89000, end 89f91fe4 ... OK
   Loading Device Tree to 89e7d000, end 89e8849f ... OK
fdt_root: FDT_ERR_BADMAGIC
ERROR: root node setup failed
 - must RESET the board to recover.

FDT creation failed! hanging...### ERROR ### Please RESET the board ###

Please Reply

Regard's
Toravi

**Comment by edtanous** [comment]
No response from submitter in 2 weeks.  Based on the symptoms, my suspicion is that this was being deployed in a non-standard way, and bmcweb was having trouble connecting to the backends.  Given the lack of info, I’m closing this.  Feel free to engage on discord or the mailing list if you’re trying to accomplish something out of the ordinary.
