### ISSUE TITLE
(Redfish) Network IPMI (out-of-band IPMI) Toggle button : Taking 20 secs or more to change the state.

### ISSUE THREAD

**Issue by cvam0000** [openbmc/bmcweb#250]
**security-and-access/policies** This error does come in, but it looks like the enable-disable button does in fact work. The only caveat is that it takes 10-20 seconds to take effect. Looking into why this is the case.

**Comment by edtanous** [comment]
Please fill out the bug template.  It is there for a reason, and has information that will help us to triage faster.  A 2 sentence description doesn't convey what the issue is, and I'm having a lot of trouble understanding the above.
