### ISSUE TITLE
Redfish Protocol Validator report FAIL

### ISSUE THREAD

**Issue by hieuhuynh-ampere** [openbmc/bmcweb#252]
**Describe the bug**
Redfish Protocol Validator report FAIL in POST /redfish/v1/AccountService/Accounts

**Environment**
Redfish Protocol Validator Version: 1.1.6
https://github.com/DMTF/Redfish-Protocol-Validator

**To Reproduce**

1. Run Redfish Protocol Validator
   python3 rf_protocol_validator.py --user root --password 0penBmc \
   --rhost https://BMC_IP --no-cert-check --avoid-http-redirect
2. The tool will report
   Method POST
   Status code 400
   URI /redfish/v1/AccountService/Accounts
   Message POST request to URI /redfish/v1/AccountService/Accounts failed with 400; expected 405; extended error:

**Comment by edtanous** [comment]
Please fill out the template as requested, including openbmc SHA1 that you tested against, and which platform you tested against.
