### ISSUE TITLE
[UpdateService] bmcweb update_service.hpp do not support multiple firmware update processes simultaneously

### ISSUE THREAD

**Issue by yufangliwyc** [openbmc/bmcweb#257]
Hi, all,

My team is researching and using PLDM firmware update solution to update our devices in OpenBMC. We met the following situation and I think the update service do not support more than two applications to execute firmware update process simultaneously(BMC updater and PLDM firmware update).

When I execute Redfish POST method on UpdateService, to upload a non-tarball file for PLDM firmware update process, there is a 10% chance that the following situation will happen.

1.  The callback function of fwUpdateErrorMatcher is triggered firstly due to the wrong file format needed by BMC updater in 
    update_service.hpp. 
2.  In the callback function of fwUpdateErrorMatcher, this code will be executed, "fwAvailableTimer = nullptr"
3.  "fwAvailableTimer = nullptr" will trigger the callback of fwAvailableTimer
4.   In the callback of fwAvailableTimer, the cleanup function will be executed to reset the fwUpdateMatcher
5.  The callback of fwUpdateMatcher will not be triggered,  so the PLDM  firmware update process will not be started. 

Likely, when the callback of fwUpdateMatcher is triggered firstly, the callback of fwUpdateErrorMatcher is rarely triggered.
There's only a small number of cases that they'll both be triggered. Only when the callback of fwUpdateMatcher is triggered firstly, the callback of fwUpdateErrorMatcher may be triggered when the asynchronous operation of fwUpdateMatcher 's callback is waiting.

We also use dbus-monitor to monitor the InterfacesAdded member as the fwUpdateMatcher and fwUpdateErrorMatcher do, when InterfacesAdded happens, dbus-monitor will be triggered.  So would you consider fixing it to support multiple firmware update processes simultaneously?

**Comment by williamspatrick** [comment]
> We met the following situation and I think the update service do not support more than two applications to execute firmware update process simultaneously(BMC updater and PLDM firmware update).

What code is being used on the PLDM side?  It sounds like you have two “ImageManagers” on the dbus which isn’t compatible with the design in https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Software/README.md

**Comment by yufangliwyc** [comment]
hi, williamspatrick
Thanks for your kind reply. We use the PLDM source codes in OpenBMC repository, https://github.com/openbmc/pldm
You said the "ImageManagers", I think I should research the source code of "phosphor-bmc-code-mgmt".

**Comment by mdmillerii** [comment]
@yufangliwyc 

>  We use the PLDM source codes in OpenBMC repository, https://github.com/openbmc/pldm 

Can you give the specific entry point or executable you are invoking? 

Also there is some work going on to select which pldm endpoint is being communicated with.  My impression is having two responders to the same type is is not yet supported

**Comment by yufangliwyc** [comment]
hi, mdmillerii
we have modified the source codes of pldm to adapt our product, due to the company policy, we can not give you the executable file.
Sorry about that. You can use the lastest source codes of pldm in this URL, https://github.com/openbmc/pldm to check this issue.
PLDM also watches the /tmp/images file path and registers software interfaces as bmc updater does, so we use the SimpleUpdate action of UpdateService in bmcweb to trigger pldm firmware update.

Command： 
curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/json" -X POST https://${bmc}/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate -d '{"TransferProtocol":"TFTP","ImageURI":"xx.xx.xx.xx/<bin_file>"}'

**Comment by mdmillerii** [comment]
Sorry I didn't mean the executable binary but the line and file or function and file or at least the name of the executable and build build rule.   I'm just starting to learn that this area and don't intend to read the whole repository to search for the implementation.

**Comment by williamspatrick** [comment]
This bug should really be moved to OpenBMC/PLDM. The implementation there violates the software design. It isn’t surprising that bmcweb, which is attempting to follow the design, isn’t operating with a process that violates it.
