### ISSUE TITLE
After initial flash, network details get wrongly

### ISSUE THREAD

**Issue by sivaprabug** [openbmc/bmcweb#258]
**Describe the bug** 

After flashing initially we got the wrong Network details conflict between static and DHCP

## Environment
evb-ast2600, Not tested in QEMU

## Build steps
```shell
git clone https://github.com/openbmc/openbmc
cd openbmc
. setup evb-ast2600 ast_2600_build
time bitbake obmc-phosphor-image
```

**To Reproduce**

```shell
GET -> /redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```
```json
{
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_9_0.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": true,
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
  "DHCPv6": {
    "OperatingMode": "Stateful",
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
  "Description": "Management Network Interface",
  "EthernetInterfaceType": "Physical",
  "FQDN": "evb-ast2600",
  "HostName": "evb-ast2600",
  "IPv4Addresses": [
    {
      "Address": "10.0.96.78",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    }
  ],
  "IPv4StaticAddresses": [
    {
      "Address": "10.0.96.78",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    }
  ],
  "IPv6AddressPolicyTable": [],
  "IPv6Addresses": [
    {
      "Address": "fe80::f067:ffff:fe03:f1b4",
      "AddressOrigin": "LinkLocal",
      "PrefixLength": 64
    },
    {
      "Address": "3001:df24:df25:df26:f067:ffff:fe03:f1b4",
      "AddressOrigin": "SLAAC",
      "PrefixLength": 64
    }
  ],
  "IPv6DefaultGateway": "0:0:0:0:0:0:0:0",
  "IPv6StaticAddresses": [],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "LinkStatus": "LinkUp",
  "MACAddress": "f2:67:ff:03:f1:b4",
  "MTUSize": 1500,
  "Name": "Manager Ethernet Interface",
  "NameServers": [
    "10.0.0.31",
    "10.0.0.32"
  ],
  "SpeedMbps": 1000,
  "StaticNameServers": [],
  "Status": {
    "State": "Enabled"
  }
}
```

Here **DHCPEnabled: true** but in IPv4Addresses AddressOrigin is **Static** Mode

![image](https://github.com/openbmc/bmcweb/assets/2444608/e1d40306-47f9-48b0-a097-622d1b15a4e0)

In webui-vue:

![image](https://github.com/openbmc/bmcweb/assets/2444608/30e3af50-3360-45f2-9b7d-4c2980ed43de)

For example setting Static IP for eth1.

- Disable DHCP mode for eth1
- Add static ip
```shell
PATCH -> /redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```

```json
{
	"IPv4StaticAddresses": [{
		"Address": "10.0.98.151",
		"SubnetMask": "255.255.224.0",
		"Gateway": "10.0.96.1"
	}, {
		"Address": "10.0.198.153",
		"Gateway": "10.0.96.1",
		"SubnetMask": "255.255.224.0"
	}]
}
```

In GET call IPv4Addresses array Address value get the Gateway value.

```json
{
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth1",
  "@odata.type": "#EthernetInterface.v1_9_0.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": false,
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
  "DHCPv6": {
    "OperatingMode": "Stateful",
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
  "Description": "Management Network Interface",
  "EthernetInterfaceType": "Physical",
  "FQDN": "evb-ast2600",
  "HostName": "evb-ast2600",
  "IPv4Addresses": [
    {
      "Address": "10.0.96.1",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    },
    {
      "Address": "10.0.198.153",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    },
    {
      "Address": "169.254.160.2",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "0.0.0.0",
      "SubnetMask": "255.255.0.0"
    }
  ],
  "IPv4StaticAddresses": [
    {
      "Address": "10.0.96.1",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    },
    {
      "Address": "10.0.198.153",
      "AddressOrigin": "Static",
      "Gateway": "10.0.96.1",
      "SubnetMask": "255.255.224.0"
    }
  ],
  "IPv6AddressPolicyTable": [],
  "IPv6Addresses": [
    {
      "Address": "3001:df24:df25:df26:bcdf:76ff:feff:bfc3",
      "AddressOrigin": "SLAAC",
      "PrefixLength": 64
    },
    {
      "Address": "fe80::bcdf:76ff:feff:bfc3",
      "AddressOrigin": "LinkLocal",
      "PrefixLength": 64
    }
  ],
  "IPv6DefaultGateway": "0:0:0:0:0:0:0:0",
  "IPv6StaticAddresses": [],
  "Id": "eth1",
  "InterfaceEnabled": true,
  "LinkStatus": "LinkUp",
  "MACAddress": "be:df:76:ff:bf:c3",
  "MTUSize": 1500,
  "Name": "Manager Ethernet Interface",
  "NameServers": [
    "10.0.0.31",
    "10.0.0.32"
  ],
  "SpeedMbps": 1000,
  "StaticNameServers": [],
  "Status": {
    "State": "Enabled"
  }
}


```

Due to this scenario, Gateway IP assigned to IP address Network collapsed 

![image](https://github.com/openbmc/bmcweb/assets/2444608/31ec6cb1-5ecd-4dfd-96a6-fe1d8bace6a6)

**Is this a regression**

Not verified previously, now only looking at this module.

**Expected behavior was**

DHCP mode IP addresses AddressOrigin in DHCP mode only
Static mode IP addresses AddressOrigin in Static mode only

Kindly help to resolve this issue

**Comment by edtanous** [comment]
Please fill out the template as requested when filing bugs.

**Comment by sivaprabug** [comment]
> Please fill out the template as requested when filing bugs.

Thanks for the guidance. Followed the  requested template .

**Comment by edtanous** [comment]
@sunharis Can you please take a look at the above?

**Comment by sunharis** [comment]
> @sunharis Can you please take a look at the above?

Sure. Will check.

**Comment by sunharis** [comment]
@sivaprabug Can you please check if your networkd repo is pointing to the latest master? There is some recent fix for this issue.

https://github.com/openbmc/phosphor-networkd/commit/86c4f44d22fb0a7185dade081f780948b0eecc42

**Comment by sivaprabug** [comment]
> @sivaprabug Can you please check if your networkd repo is pointing to the latest master? There is some recent fix for this issue.
> 
> [openbmc/phosphor-networkd@86c4f44](https://github.com/openbmc/phosphor-networkd/commit/86c4f44d22fb0a7185dade081f780948b0eecc42)
> 
> You also need [openbmc/phosphor-networkd@c620120](https://github.com/openbmc/phosphor-networkd/commit/c6201207fc8523b3ccc53fa44ad28e44d38af02d)

Above commit changes available. While setting the second static ip we get the same  Gateway ip as the IP Address.

![image](https://github.com/openbmc/bmcweb/assets/2444608/089a5549-cea3-4946-aab2-e614c805ca81)

**Comment by sunharis** [comment]
OK. The fix which i mentioned was for `After flashing initially we got the wrong Network details conflict between static and DHCP`

But the issue you are talking about here is - After patching the static network, you see that it writes the gateway ip value on the address property. Have you checked what values are set at the dbus network objects?

**Comment by sivaprabug** [comment]
> OK. The fix which i mentioned was for `After flashing initially we got the wrong Network details conflict between static and DHCP`
> 
> But the issue you are talking about here is - After patching the static network, you see that it writes the gateway ip value on the address property. Have you checked what values are set at the dbus network objects?

Hi @sunharis 

```shell
/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```
Payload:
```json

{
    "IPv4StaticAddresses": [
        {
            "Address": "10.0.100.20",
            "SubnetMask": "255.255.224.0",
            "Gateway": "10.0.96.1"
        },
        {
            "Address": "10.0.100.21",
            "SubnetMask": "255.255.224.0",
            "Gateway": "10.0.96.1"
        }
    ]
}
```

Response from GET call:

```shell
/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```
![image](https://github.com/openbmc/bmcweb/assets/2444608/deb8bbdc-9d17-4697-ab2b-8f29f5333db4)

Verified in DBUS :

FYI:

![image](https://github.com/openbmc/bmcweb/assets/2444608/5749364f-0151-46fc-8a32-de6e7d25e6d7)

![image](https://github.com/openbmc/bmcweb/assets/2444608/cefcff2b-e282-4ce8-aeff-7932bd9b3ab0)

**Comment by raviteja-b** [comment]
@sivaprabug seems this is working as expected, can we close this defect

**Comment by sivaprabug** [comment]
> @sivaprabug seems this is working as expected, can we close this issue

Yes @raviteja-b now working as expected we can close this issue

![image](https://github.com/openbmc/bmcweb/assets/2444608/b662578e-c4b8-44f5-bd2b-37ef63ba64f2)
