### ISSUE TITLE
How to add circuit schema in redfish

### ISSUE THREAD

**Issue by toravishivraj** [openbmc/bmcweb#259]
Hi all,

I Build openbmc image for raspberrypi of Kirkstone Branch with
Yocto version:- 4.0.4
Openbmc Version :- 2.12.0
Redfish Version :-DSP8010_2021.4
Ubuntu:- 20.4

I Update File of Path:- OpenBMC-2.12.0/openbmc/build/temp/work/cortex.../bmcweb/1.0+gitAUTOINC+3d...-ro/git/scripts/update_schemas.py
in this script I have add 'Circuit' in include_list and ran the script, the effect of this is below.

1) Path:- OpenBMC-2.12.0/openbmc/build/temp/work/cortex.../bmcweb/1.0+gitAUTOINC+3d...-ro/git/static/
redfish/v1/$metadata/index.xml added <edmx:Include Namespace="circuit.v1_5_0....
2) Path:- OpenBMC-2.12.0/openbmc/build/temp/work/cortex.../bmcweb/1.0+gitAUTOINC+3d...-ro/git/static/
redfish/v1/JsonSchemas added Circuit Directory
3) Path:- OpenBMC-2.12.0/openbmc/build/temp/work/cortex.../bmcweb/1.0+gitAUTOINC+3d...-ro/git/static/
redfish/v1/schema added Circuit_v1

than i have rebuild hole image.

The problem is when i check final image in path OpenBMC-2.12.0/openbmc/build/temp/deploy/images/raspberrypi/obmc-.....rootfs.tar.xz with size 19.1MB 
with Modified as that current time of build but when I extract it, 
1) it shows with size =16 items and Modified= date of 9 mar 2018 why it not
     shows current date?
2) when i open the file, 
   a) in path usr/share/www/redfish/v1/$metadata circuit class is absent 
   b) in path usr/share/www/redfish/v1/jsonSchemas circuit Directory is absent
   c) in path usr/share/www/redfish/v1/Schema circuit .xml is absent
      means it rebuild with it deafult redfish schema why?
3) After Adding the Circuit class in update_schemas.py & ran script it only effect on that path not adds in final image why?
4) Is their any another mathod for adding circuit class and absent schema of that redfish version?
5) I also want to reflact the change in final image (in rootfs.tar.xz image) and why Modified date shows 9 mar 2018 not current build 
     time?

   Please Suggest ASAP,

  Regard's
  Toravi S.

**Comment by williamspatrick** [comment]
You cannot randomly modify files in temp/build of Yocto and expect it to do anything useful. Please look into `devtool` if you want to make modifications to the code of any repo, such as bmcweb.
