### ISSUE TITLE
REST:  GET /foo  could use a full error response

### ISSUE THREAD

**Issue by spinler** [openbmc/bmcweb#26]
Continuing with issue #15, when doing a GET on a completely invalid path that doesn't start with /xyz or /org, it would be nice to get the full 
```
{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found"
  },
  "message": "404 Not Found",
  "status": "error"
}
```
instead of just:
```
Not Found
```

**Comment by edtanous** [comment]
@mspinler I'm assuming this is something you're looking at, so I've assigned it to you.  If it's something you'd like me to tackle, let me know, and I'll add it to the backlog.

**Comment by spinler** [comment]
Yea, me or someone on my team will do it in our quest to get the number of testcase fails as low as possible.

**Comment by spinler** [comment]
This also shows up on PUTs
