### ISSUE TITLE
how to create Circuit.hpp file

### ISSUE THREAD

**Issue by toravishivraj** [openbmc/bmcweb#260]
Hi All,
I am using DSP8010_2022.1 schema bundle, i added circuit class by using update_schemas.py script in our bmcweb.
My question is,  where is  circuit.hpp, power_Distribution.hpp , power_supply.hpp and oem.hpp file or need to add in bmcweb/redfish-core/lib directory or if not available than how to write ?
my question is related to circuit.hpp, power_Distribution.hpp , power_supply.hpp and custom_oem.hpp schema file are not available than how to write and how to add?

Please replay ASAP,

Regard's
Toravi S. N.

**Comment by edtanous** [comment]
> if not available than how to write ?

As documented, Github is not an appropriate place for questions.  Please direct yourself to the mailing list or discord.

Closing.
