### ISSUE TITLE
Patch request for any URI with If-Match with value of Etag in request header causes the BMCWEB to crash 

### ISSUE THREAD

**Issue by arunthomasbaby** [openbmc/bmcweb#262]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

Patch request to Redfish URI's with If-Match header in the request body with value of etag header causes the BMCWEB to crash. 
Steps to reproduce:
PATCH a property under SessionService.

Step 1:  Get the current etag for the resource from the response header of the Get method.  

![etag-value](https://github.com/openbmc/bmcweb/assets/138849124/70d41bf2-f7be-4c99-a2ed-2dd3350b9e84)

Step 2: Issued a PATCH request with If-Match header in the request body with the value of etag fetched from step 1.
![etag-curl-requst-failure](https://github.com/openbmc/bmcweb/assets/138849124/ffa28b80-4000-44ce-9a8c-74d0c91b04f1)

This causes the BMCWEB to crash. 

![core-dump](https://github.com/openbmc/bmcweb/assets/138849124/6285f2b0-63e0-4174-a4db-391d42fb9066)

Step 3: Issued a PATCH request with If-Match header in the request body with the value of * .

![if-match-with-star](https://github.com/openbmc/bmcweb/assets/138849124/67a6c10b-f1c9-4870-a8b0-b70fef66e736)

The PATCH gets success in this case.

Step 4: Issued a PATCH request with If-Match header in the request body with a random value.

![wrong-etag](https://github.com/openbmc/bmcweb/assets/138849124/ef8361a8-9a96-4d6b-8c3a-fdf3a96e6ef2)

This works as expected.  

Failure observed only in step 2.

### Version

```Text
root@evb-ast2600:~# cat /etc/os-release
ID=openbmc-phosphor
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.15.0-dev"
VERSION_ID=2.15.0-dev-944-g3596dc23c5
VERSION_CODENAME="mickledore"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.15.0-dev"
CPE_NAME="cpe:/o:openembedded:openbmc-phosphor:2.15.0-dev-944-g3596dc23c5"
BUILD_ID="20230901120024"
OPENBMC_TARGET_MACHINE="evb-ast2600"
EXTENDED_VERSION="2.15.0-dev-944-g3596dc23c5"
```

### Additional Information

This issue causes the Redfish Protocol validator to fail

**Comment by raviteja-b** [comment]
I think in step2 there is " \" included in the input,  Is it necessary?
can you please try without "\"?
like  -H 'If-Match: "B71CF5AE"'

**Comment by arunthomasbaby** [comment]
> I think in step2 there is \ included in the input, Is it necessary? can you please try without \ ? like -H 'If-Match: "B71CF5AE"'

I tried without \ and still its causing the BMCWEB to crash. What I observed is, when etag is supplied as request header for a Patch request , its creating a new req for the same URI with GET method to calculate the current etag for the resource. [(Link to code.)](https://github.com/openbmc/bmcweb/blob/e1bf8bb6a843a2a53d74d74f410b5fe053c2d222/redfish-core/include/query.hpp#L87)  .When the new req is created internally for GET method  , req.session of the Patch request is assigned to the new request and calls app.handle() [(Link to code.)](https://github.com/openbmc/bmcweb/blob/e1bf8bb6a843a2a53d74d74f410b5fe053c2d222/redfish-core/include/query.hpp#L97) Since the req.session is not nil for the new request, validatePrivilege() in router.hpp which will authenticate the incoming request and assign user privilege will cause the bmcweb to crash in the function populateUserInfo(). [(Link to code)](https://github.com/openbmc/bmcweb/blob/e1bf8bb6a843a2a53d74d74f410b5fe053c2d222/include/dbus_privileges.hpp#L86)   

For the new request internally framed for calculating the etag, is it necessary to have authentication again? Since the incoming Patch request is already authenticated and same req.session is assigned to new req, its an extra overhead to authenticate it again with the same credentials. When I bypassed authentication for the new request and when current req is restarted after etag comparison [(Link to code)](https://github.com/openbmc/bmcweb/blob/e1bf8bb6a843a2a53d74d74f410b5fe053c2d222/redfish-core/include/query.hpp#L51) its working fine.

**Comment by raviteja-b** [comment]
@arunthomasbaby ok, got it
have you pushed code changes for bypassed authentication for the new request to Gerrit?

**Comment by arunthomasbaby** [comment]
> @arunthomasbaby ok, got it have you pushed code changes Gerrit?

yes, https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66685

**Comment by gtmills** [comment]
This was reported when running the redfishtool 
https://github.com/DMTF/Redfishtool/blob/ff18b735189bcab5d7c86186fa36baabebe55971/redfishtoollib/redfishtoolTransport.py#L1207

**Comment by shawnw-smc** [comment]
I've encountered a similar issue lately. I'm wondering if it could be related to the variable's life cycle. In [routing.hpp#L153](https://github.com/openbmc/bmcweb/blob/522377dcb85082da598403e104a44d621b4c2bb4/include/dbus_privileges.hpp#L153C10-L153C14), an asynchronous method is used, but it captures the variable by reference.This could mean the variable leaves its scope, making `callback(req)` potentially access an illegal address.

**Comment by n5c** [comment]
I came across this problem as well when running the Redfish-Protocol-Validator. The RPV showed:
```
Traceback (most recent call last):
  File "/opt/Redfish-Protocol-Validator/venv/bin/rf_protocol_validator", line 9, in <module>
    sys.exit(main())
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/redfish_protocol_validator/console_scripts.py", line 92, in main
    resources.data_modification_requests(sut)
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/redfish_protocol_validator/resources.py", line 299, in data_modification_requests
    patch_session(sut, new_session_uri)             
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/redfish_protocol_validator/resources.py", line 274, in patch_session
    response = sut.patch(session_uri, json=payload, headers=headers)
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/redfish_protocol_validator/system_under_test.py", line 478, in patch
    response = self._session.patch(self.rhost + uri, json=json, headers=headers)
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/requests/sessions.py", line 661, in patch
    return self.request("PATCH", url, data=data, **kwargs)
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)             
  File "/opt/Redfish-Protocol-Validator/venv/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

This problem  can be reproduced by CURL:
```shell
# login to create a session and get the token
$ curl -v -k -H "Content-Type: application/json" -X POST https://192.168.0.29/login -d '{"username" :  "root", "password" :  "0penBmc"}'
...
"token": "njmPcooiSOrNNBbTYf3T"

# GET any sessions to get the ETAG
$ curl -v -k -H "X-Auth-Token: njmPcooiSOrNNBbTYf3T" -X GET https://192.168.0.29/redfish/v1/SessionService/Sessions/g74ncruONv
...
ETag: "7572B8C2"

# PATCH the session
$ curl -v -k -H "X-Auth-Token: njmPcooiSOrNNBbTYf3T" -H "If-Match: \"7572B8C2\"" -X PATCH https://192.168.0.29/redfish/v1/SessionService/Sessions/g74ncruONv -d {"UserName": "pRoToVal"}
```

Trace the bmcweb we can find:
1. the PATCH request match the rule: "Matched rule '/redfish/\<path\>' 4 / 256"
2. then, it invoked: "redfish405" -> "redfish::setUpRedfishRoute" -> "handleIfMatch"
3. and the following code was executed:
```cpp
inline void handleIfMatch(...) {
...
    crow::Request newReq(
        {boost::beast::http::verb::get, req.url().encoded_path(), 11}, ec);
...
}
```
4. then, the local variable newReq would be passed by reference into the async function in validatePrivilege(...)
```cpp
    template <typename CallbackFn>
    void validatePrivilege(Request& req,
                                  ^^^^^^
                           const std::shared_ptr<bmcweb::AsyncResp>& asyncResp,
                           BaseRule& rule, CallbackFn&& callback)
    {
        if (req.session == nullptr)
        {
            return;
        }
        std::string username = req.session->username;
        crow::connections::systemBus->async_method_call(
            [this, &req, asyncResp, &rule,
                   ^^^^^^
             callback(std::forward<CallbackFn>(callback))](
                const boost::system::error_code& ec,
                const dbus::utility::DBusPropertiesMap& userInfoMap) mutable {
            afterGetUserInfo(req, asyncResp, rule,
                            ^^^^^
                             std::forward<CallbackFn>(callback), ec,
                             userInfoMap);
            },
            "xyz.openbmc_project.User.Manager", "/xyz/openbmc_project/user",
            "xyz.openbmc_project.User.Manager", "GetUserInfo", username);
    }
```

5. finally, it crashed in populateUserInfo() (mostly here, but sometimes it crashed in other places)
```cpp
static bool populateUserInfo(...) {
...
        if (userRolePtr != nullptr)
        {
            req.session->userRole = *userRolePtr; // <-------------- HERE
            BMCWEB_LOG_DEBUG << "userName = " << req.session->username
                             << " userRole = " << *userRolePtr;
        }
...
}
```




My bmcweb commit is: [982dd79d371c48f48ea1e3462545ac4e2a8b4f93](https://github.com/openbmc/bmcweb/tree/982dd79d371c48f48ea1e3462545ac4e2a8b4f93)

**Comment by arunthomasbaby** [comment]
@n5c  Same is the case what I also faced. I am wondering if we can bypass authentication and privilege check for the request which are framed internally to get the etag. Already authentication and privilege check has been done for the actual patch request. Also if we trigger the same patch request without If-Match header , it will succeed. So in my opinion, authentication  for the internal requests might not be necessary.

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69702 should have fixed this. Closing. Please reopen if still a problem.
