### ISSUE TITLE
Misusage of deleteAndCreateIPAddress function

### ISSUE THREAD

**Issue by Lin-TommySC** [openbmc/bmcweb#263]
The address parameter should come first before gateway when calling deleteAndCreateIPAddress function.

https://github.com/openbmc/bmcweb/blob/f5f8eaa88e5857cb0f01fa9e48e75d40274c91bd/redfish-core/lib/ethernet.hpp#L1368

Current code:
~~~
                deleteAndCreateIPAddress(IpVersion::IpV4, ifaceId,
                                         nicIpEntry->id, prefixLength, *gateway,
                                         *address, asyncResp);
~~~
Should be replaced with:
~~~
                deleteAndCreateIPAddress(IpVersion::IpV4, ifaceId,
                                         nicIpEntry->id, prefixLength, *address,
                                         *gateway, asyncResp);
~~~

**Comment by edtanous** [comment]
Looks like a problem introduced with 9c5e585c3faa73941cedcc70cdff680f403c17bc

Can you please test https://gerrit.openbmc.org/c/openbmc/bmcweb/+/66475 and report if it works for you?

**Comment by Lin-TommySC** [comment]
It does work for me. And I forgot to mention the same error code exists here as well:
https://github.com/openbmc/bmcweb/blob/f5f8eaa88e5857cb0f01fa9e48e75d40274c91bd/redfish-core/lib/ethernet.hpp#L1502
