### ISSUE TITLE
IPAddresses have field's value 0.0.0.0

### ISSUE THREAD

**Issue by hieuhuynh-ampere** [openbmc/bmcweb#269]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

Run Redfish GET

- curl -X GET --user root:0penBmc -H "Content-Type: application/json" --insecure https://bmc_ip/redfish/v1/Managers/bmc/EthernetInterfaces/eth1
```
"IPv4Addresses": [
{
"Gateway": "0.0.0.0",
}
],
```
- curl -X GET --user root:0penBmc -H "Content-Type: application/json" --insecure https://bmc_ip/redfish/v1/Managers/bmc/EthernetInterfaces/usb0
```
"IPv4Addresses": [
{
"Gateway": "0.0.0.0",
}
],
"IPv4StaticAddresses": [
{
"Gateway": "0.0.0.0",
}
],
```
**Expected result:**

If there is no data setting for IP addresses/gateways, the value should be null.

**Actual result:**

Value display 0.0.0.0 is a wrong and meaningless IP

This make test of Redfish-Usecase-Compliance NetworkManager failed https://github.com/DMTF/Redfish-Usecase-Checkers
```
$ python3 manager_ethernet_interface/manager_ethernet_interface_check.py -r bmc_ip:443 -u root -p 0penBmc -S Always
Found 1 manager instances
Found 3 Ethernet interface instances in manager 'bmc'
Testing interface 'eth0'
Testing interface 'eth1'
ERROR: 'IPv4Addresses' contains an empty string, 0.0.0.0, or :: rather than null in manager 'bmc' interface 'eth1'
Testing interface 'usb0'
ERROR: 'IPv4Addresses' contains an empty string, 0.0.0.0, or :: rather than null in manager 'bmc' interface 'usb0'
ERROR: 'IPv4StaticAddresses' contains an empty string, 0.0.0.0, or :: rather than null in manager 'bmc' interface 'usb0'
```

### Version

```Text
Openbmc SHA1: 0bb38d152cd28e699f21cf6d240f1f9ba886be5e
Platform: mtmitchell-dcscm
```

### Additional Information

bmcweb set the default Gateway to '0.0.0.0' is this value is empty https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/ethernet.hpp#L1660

**Comment by gtmills** [comment]
What should bmcweb do instead? Just leave the property off?

**Comment by edtanous** [comment]
> the value should be null.

From the description.

**Comment by hieuhuynh-ampere** [comment]
Hi @edtanous, could I have a MR to update these fields to null?

**Comment by gtmills** [comment]
> Hi @edtanous, could I have a MR to update these fields to null?"

Feel free to push something to https://gerrit.openbmc.org/q/project:openbmc/bmcweb+status:open  

Be sure to follow our documentation https://github.com/openbmc/bmcweb/blob/master/DEVELOPING.md

**Comment by edtanous** [comment]
> Hi @edtanous, could I have a MR to update these fields to null?

What is an MR?

**Comment by hieuhuynh-ampere** [comment]
Hi @edtanous,
> What is an MR?

From this: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69864

**Comment by edtanous** [comment]
What does "MR" mean?

**Comment by hieuhuynh-ampere** [comment]
I mean a Gerrit review.

**Comment by edtanous** [comment]
It looks like we may have been doing this correctly.  I filed an issue with DMTF, and they are going to amend the wording to specifically call out the unconfigured case for ipv6 and ipv4

**Comment by edtanous** [comment]
Closing, per discussion in DMTF, this behavior of using 0.0.0.0 for unset ipv4 addresses seems to be correct (even if not explicitly defined in the spec).  Redfish usecase checker seems to be in the wrong here.  Feel free to file a bug against it.
