### ISSUE TITLE
URL arg number assert should contain 5

### ISSUE THREAD

**Issue by 1208372113** [openbmc/bmcweb#270]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

URL arg number assert should contain 5

[http/routing.hpp](https://github.com/openbmc/bmcweb/blob/master/http/routing.hpp)
![image](https://github.com/openbmc/bmcweb/assets/82940313/0f777523-89b7-4a0b-b712-db19080adb6a)

Should be
`static_assert(numArgs <= 5, "Max number of args supported is 5");`

### Version

```Text
https://github.com/openbmc/bmcweb/http/routing.hpp
```

**Comment by edtanous** [comment]
have you submitted your change?

**Comment by gtmills** [comment]
Fixed by https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70126

**Comment by 1208372113** [comment]
sorry，I don't know how to standardize submission。I haven't used gerrit。

**Comment by gtmills** [comment]
No worries. https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md for next time.

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70126 merged so closing
