### ISSUE TITLE
Json content-type "application/json;charset=utf-8" without space separator is not allowed

### ISSUE THREAD

**Issue by AleksandrParamonov** [openbmc/bmcweb#271]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

Redfish requests without space separator between **application/json;** and **charset=utf-8** in content-type in header are considered incorrect.. Code inside parsing.hpp (https://github.com/openbmc/bmcweb/blob/master/http/parsing.hpp#L20) only accepts content-type with space separator:
`inline bool isJsonContentType(std::string_view contentType)
{
    return bmcweb::asciiIEquals(contentType, "application/json") ||
           bmcweb::asciiIEquals(contentType, "application/json; charset=utf-8");
}`
Shoudln't **"application/json;charset=utf-8"** be valid?

### Version

```Text
b2896149c39967dd9d1ee79357bdc53537cfabd7
```

### Additional Information

I've met warning message "Failed to parse content type on request"  during communication with AMI BIOS. AMI BIOS forms without space separator so some requests are considered invalid.

**Comment by edtanous** [comment]
It looks like most http examples have the space, but the redfish spec does not.  Seems like we could just accept either.  Please put up a patch in Gerrit for that behavior.

**Comment by edtanous** [comment]
Can you please test if https://gerrit.openbmc.org/c/openbmc/bmcweb/+/70112 solves your bug?

**Comment by AleksandrParamonov** [comment]
The issue is fixed and BIOS requests are no longer rejected.

**Comment by edtanous** [comment]
Reopening, the above review isn't merged yet.
