### ISSUE TITLE
Redfish Protocol Validator fails for SSE request

### ISSUE THREAD

**Issue by chandramohan83** [openbmc/bmcweb#278]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

When I run Protocol validator it fails for the test case below

SERV_SSE_UNSUCCESSFUL_RESPONSE  GET     404     /redfish/v1/EventService/SSE    FAIL    No Content-Type header in response from GET request to URL /redfish/v1/EventService/SSE; expected application/json or application/json;charset=utf-8    Server-sent events: Unsuccessful resource responses for SSE shall return an HTTP status code of 400 or greater, have a Content-Type header set as application/json or application/json;charset=utf-8, and contain a JSON object in the response body, as described in Error responses, which details the error or errors. 

Basically here the protocol validator looking for Content-Type header in the GET response of http://127.0.0.1/redfish/v1/EventService/SSE and which is not present.

### Version

```Text
Author: Andrew Geissler <openbmcbump-github@yahoo.com>
Date:   Fri May 31 11:20:17 2024 -0500

    google-misc: srcrev bump 4dba220d36..b47ca0dfa3

    Yuxiao Zhang (1):
          ncsid: reconfigure gateway when default route is missing

    Change-Id: I97cf09a76e685dc1a48d837b99e1640244ebd008
    Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>
```

### Additional Information

I discussed with Ed regarding this issue and concluded that, The issue being discussed doesn't impact current functionality, so a bug report will be opened for now while focusing on making the feature work. The bmcweb router can't register both an HTTP and SSE route to the same URI, and adding this capability would be challenging. The requirement for a JSON error code is noted, and there's a desire to change the standard as it seems unnecessary.

**Comment by chandramohan83** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71765 MR is created to address this issue.

**Comment by edtanous** [comment]
Fixed in aformentioned commit.
