### ISSUE TITLE
Login Web Cant redirect

### ISSUE THREAD

**Issue by Xxfore** [openbmc/bmcweb#279]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

Clone and build Openbmc for board evb-ast2600 , then use chrome or firefox cant access https://127.0.0.1:2443

1. clone git@github.com:openbmc/openbmc.git with master branch
2. . setup evb-ast2600
3. bitbake obmc-phosphor-image
4. runqemu nographic slirp (Add hostfwd like : hostfwd=:127.0.0.1:2443-:443 hostfwd=udp:127.0.0.1:2623-:623 )
5. Open Chrome or Firefox to access https://127.0.0.1:2443 , then it will redirect to https://127.0.0.1:2443/?next=/#/login
and shows "This site cant be reached" (From chrome develop tools, seems it has so many 307 redirect request)

https://127.0.0.1:2443/redfish/v1 can be access, each sub links can not be access in redfish
ipmitools and ssh can connect normally.

More details please refer attached capture.
![image](https://github.com/openbmc/bmcweb/assets/9338816/1c5b88d4-b199-4f23-ae97-2eb2e4f7b8ce)

### Version

```Text
root@evb-ast2600:~# cat /etc/os-release 
ID=openbmc-phosphor
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.16.0-dev"
VERSION_ID=2.16.0-dev-1105-gab31aaff7a
VERSION_CODENAME="scarthgap"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.16.0-dev"
CPE_NAME="cpe:/o:openembedded:openbmc-phosphor:2.16.0-dev-1105-gab31aaff7a"
BUILD_ID="20240611080038"
OPENBMC_TARGET_MACHINE="evb-ast2600"
EXTENDED_VERSION="2.16.0-dev-1105-gab31aaff7a"
```

**Comment by jtru** [comment]
FTR, I can confirm this commit fixes the reported problem :) Thanks!
