### ISSUE TITLE
Redfish: Account service does not implement account lockout or PrivilegeMap features

### ISSUE THREAD

**Issue by omar-ocampo** [openbmc/bmcweb#28]
BMCWeb seems to be using AccountService.v1_1_0.

According to https://redfish.dmtf.org/schemas/v1/AccountService.v1_1_0.json the next fields are not implemented in the BMCWeb account_service.hpp:

Status
AuthFailureLoggingThreshold
MinPasswordLength
AccountLockoutThreshold
AccountLockoutDuration
AccountLockoutCounterResetAfter
PrivilegeMap

Are those planned to be implemented in future versions?

**Comment by edtanous** [comment]
I've updated the title to reflect what I believe the status is.  Let me know if you think I'm incorrect.

**Comment by omar-ocampo** [comment]
Should MinPasswordLength, AccountLockoutThreshold and AccountLockoutDuration appear on the GET request for account service?

I do agree with the change of the title.

**Comment by edtanous** [comment]
If you have the appropriate features enabled in phosphor-user-manager, yes, those properties should show up

**Comment by gtmills** [comment]
No response. Closing. Please reopen if still an issue.
