### ISSUE TITLE
Redfish SessionService/Sessions POST returns empty string for Role

### ISSUE THREAD

**Issue by edtanous** [openbmc/bmcweb#280]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

When POSTing to SessionCollection, Role is being returned empty:
```
❯ curl --insecure -H "Content-Type: application/json" -X POST -D headers.txt https://192.168.7.2/redfish/v1/SessionService/Sessions -d    '{"UserName":"root", "Password":"0penBmc"}'
{
  ......
  "Roles": [
    ""
  ],
}%
```

Subsequent requests to the newly created URI produce the Role correctly.

### Version

```Text
BMCWEB commit ce22f6099e7e28ae26591348bf484ebedbc1ed42 appears to have added this regression.

https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71771
```

**Comment by gtmills** [comment]
> BMCWEB commit ce22f6099e7e28ae26591348bf484ebedbc1ed42 appears to have added this regression.

ce22f60 (https://gerrit.openbmc.org/c/openbmc/bmcweb/+/71771/2//COMMIT_MSG) added roles, but it sounded like it only worked in some situations?

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/72421 is the fix
