### ISSUE TITLE
Disable certificate validation

### ISSUE THREAD

**Issue by awan119** [openbmc/bmcweb#286]
Is bmcweb able to disable certificate validation for https connection?

I am working on push-style subscription with https://github.com/DMTF/Redfish-Event-Listener/.

Now http works fine, but I hope to use https without certificate validation, so that we could skip validating digital certificates.

Thank you.

**Comment by edtanous** [comment]
This is a question, not a bug, and ignored the bug template.  Please direct questions to the appropriate forum.
