### ISSUE TITLE
Building with debug enabled causes lots of warnings

### ISSUE THREAD

**Issue by geissonator** [openbmc/bmcweb#29]
I assume something to do with our recent gcc upgrade? Or maybe it's just been here for a bit. When you do a "cmake ./ -DCMAKE_BUILD_TYPE:type=Debug" you end up with all these warnings due to the tracing.

```
...
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc: In member function \u2018BasicJsonType* nlohmann::detail::json_sax_dom_parser<BasicJsonType>::handle_value(Value&&) [with Value = nlohmann::detail::value_t; BasicJsonType = nlohmann::basic_json<>]\u2019:
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc:109:4: note: parameter passing for argument of type \u2018__gnu_cxx::__normal_iterator<nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >\u2019 changed in GCC 7.1
    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
    ^~~~~~~~~~~~~~~~~
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc: In member function \u2018void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = nlohmann::basic_json<>; _Alloc = std::allocator<nlohmann::basic_json<> >]\u2019:
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc:413:7: note: parameter passing for argument of type \u2018std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > >::iterator\u2019 {aka \u2018__gnu_cxx::__normal_iterator<nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >\u2019} changed in GCC 7.1
       vector<_Tp, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc: In member function \u2018bool nlohmann::detail::parser<BasicJsonType>::sax_parse_internal(SAX*) [with SAX = nlohmann::detail::json_sax_dom_parser<nlohmann::basic_json<> >; BasicJsonType = nlohmann::basic_json<>]\u2019:
/esw/san5/openbmc/sdk/witherspoon/latest/sysroots/armv6-openbmc-linux-gnueabi/usr/include/c++/8.2.0/bits/vector.tcc:109:4: note: parameter passing for argument of type \u2018__gnu_cxx::__normal_iterator<nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >\u2019 changed in GCC 7.1
    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
...
```

**Comment by edtanous** [comment]
Yep.  This is an example of poor maintainership on my part.  -Werror isn't enabled on release builds because we didn't want to break with every new gcc version, but the hope was that people built with debug enough to find these, and we could get them resolved.

That assumption hasn't turned out to be as true as I'd like it to be.  Fixing these warnings is on my list, but I'm happy to accept any incremental patches that fix some of them.

**Comment by edtanous** [comment]
Partially resolved:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18345

**Comment by geissonator** [comment]
nlohman seems to cause some of the verbosity as well:

https://github.com/nlohmann/json/issues/658
https://stackoverflow.com/questions/52020305/what-exactly-does-gccs-wpsabi-option-do-what-are-the-implications-of-supressi

**Comment by edtanous** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23410

Should resolve a lot of it.

**Comment by gtmills** [comment]
@edtanous @geissonator Still an issue or can we close?

**Comment by geissonator** [comment]
> @edtanous @geissonator Still an issue or can we close?
Not sure, sounds like Ed put in some good changes above. I'll leave it up to him if he'd like to just call it on this one or not.

**Comment by edtanous** [comment]
I think most of this is solved and -werror is turned on for master builds.  Unless there's something here that's explicitly messy or terrible that we should fix, I'm going to close this, but happy to open a new one if there's another warning type that's biting us, but the warning explicitly mentioned has been solved along with a bunch of others.
