### ISSUE TITLE
Wrong type of MemberId in SubmitTestEvent

### ISSUE THREAD

**Issue by ifel** [openbmc/bmcweb#290]
Hello, 

According to the scheme https://redfish.dmtf.org/schemas/v1/Event.v1_4_0.json, they type of the MemberId is string, but in the code it's int:
https://github.com/openbmc/bmcweb/blob/6fe8751c46d7086e49977b68e74262927b4a7d39/redfish-core/include/event_service_manager.hpp#L316

So, clients written in typed languages cannot deserialize the response.

**Comment by edtanous** [comment]
Yep, this does appear to be incorrectly typed in code.  Feel free to send patches to fix.

**Comment by ifel** [comment]
@edtanous already done - https://github.com/openbmc/bmcweb/pull/291

**Comment by edtanous** [comment]
Patches need to be submitted to gerrit.  Also FYI, there's two lines that need fixed, one for TestEvent and one for normal Event path.

**Comment by ifel** [comment]
Thanks, it took some time to recall how to use Gerrit, but I made it :) 

https://gerrit.openbmc.org/c/openbmc/bmcweb/+/75269

You're right, there is also the second place, modified it as well.
