### ISSUE TITLE
OpenBMC+ 2.00: SSH to OSM, URI "redfish/v1/SessionService/Sessions" doesn't report the session

### ISSUE THREAD

**Issue by FarahRasheed1** [openbmc/bmcweb#292]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

When connecting via SSH to OpenBMC (reproduced on QEMU, see logs below), and then running a GET request on the URI "redfish/v1/SessionService/Sessions", the actively connected SSH session is not reported in the session list in the response.

Expected Behavior:

The URI "redfish/v1/SessionService/Sessions" is expected to report the actively connected SSH session.

Steps to Reproduce:

Connect to OpenBMC via SSH on a terminal and leave the connection open.
Run the GET request on the URI "redfish/v1/SessionService/Sessions" from another terminal or a tool like Postman while making sure that SSH connection to openbmc is open.

Observed Behavior:

The session is not reported when running the GET request on the URI "redfish/v1/SessionService/Sessions".

Logs showing the active SSH connection:

romulus systemd[1]: Started SSH Per-Connection Server (10.0.2.2:32940).
romulus dropbear[335]: Child connection from ::ffff:10.0.2.2:32940
romulus dropbear[335]: PAM password auth succeeded for 'root' from ::ffff:10.0.2.2:32940
romulus bmcweb[182]: pam_succeed_if(webserver:auth): requirement "user ingroup redfish" was met by user "root"

Redfish response:

curl -k -u root:0penBmc https://localhost:2443/redfish/v1/SessionService/Sessions

{   "@odata.id": "/redfish/v1/SessionService/Sessions/",   "@odata.type": "#SessionCollection.SessionCollection",   "Description": "Session Collection",   "Members": [],   "Members@odata.count": 0,   "Name": "Session Collection" }

### Version

```Text
cat /etc/os-release
ID=openbmc-openpower
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.14.0"
VERSION_ID=2.14.0
VERSION_CODENAME="langdale"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.14.0"
BUILD_ID="20241016205038"
OPENBMC_TARGET_MACHINE="romulus"
EXTENDED_VERSION="2.14.0
```

**Comment by edtanous** [comment]
Why do you expect this behavior?  To my knowledge ssh sessions have never been accessible through Redfish.  Are you sure this isn’t a new feature?

**Comment by FarahRasheed1** [comment]
My bad. You are correct, an SSH session will not appear as a Redfish session. Closing the bug.
