### ISSUE TITLE
Debug difficult waste too much time

### ISSUE THREAD

**Issue by fishermess** [openbmc/bmcweb#295]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use OpenBMC
- [X] This is not a bug in an OpenBMC fork or a bug in code still under code review.
- [X] This is not a request for a new feature.

### Bug Description

Each time debuging a funcion of one line code will cost me too much time.
1.type "bitbake bmcweb",this action will cost me 5 minutes.
2.Replace bmcweb binary file.
3.reboot bmcweb.

This seriers of actions cost me too much time.I can't believe it is a right develop flow as a web engineer, please show me right way.

The second question is that I didn't find any action relate with "meson setup buildder && ninja " in bmcweb.bb.How does it work?how can I use “Incremental Implementation” to decrease waste time in action "bitbake bmcweb" which cost me too much time.

I am sorry to use this channel because I don't know will to talk with project manager for asking question, would u like to show me right way to talk with PM?

### Version

```Text
123
```

### Additional Information

Thanks for help.

**Comment by fishermess** [comment]
Dose bmcweb have Hot Deployment method?

**Comment by edtanous** [comment]
> I am sorry to use this channel because I don't know will to talk with project manager for asking question, would u like to show me right way to talk with PM?

Sorry, but you knew this was the wrong place to ask this question, and you did it anyway.  There's certainly things that can improve and speed up your workflow, but you need to ask the questions in the right place so I'm not having to take time out to respond to questions in github bugs, and so that others can see your question and respond.

When you do ask this in the right forum (mailing list), I would highly recommend revisiting the tone of your questions.  bmcweb is free software, if there's something you don't like about the workflow, feel free to engineer a faster application/process.  You should probably also list an appropriate version (not 123) and the specs of your build machine if you're hoping to compare development performance.

**Comment by fishermess** [comment]
Dose bmcweb have Hot Deployment method?Dose bmcweb have Hot Deployment method?

> > I am sorry to use this channel because I don't know will to talk with project manager for asking question, would u like to show me right way to talk with PM?
> 
> Sorry, but you knew this was the wrong place to ask this question, and you did it anyway. There's certainly things that can improve and speed up your workflow, but you need to ask the questions in the right place so I'm not having to take time out to respond to questions in github bugs, and so that others can see your question and respond.
> 
> When you do ask this in the right forum (mailing list), I would highly recommend revisiting the tone of your questions. bmcweb is free software, if there's something you don't like about the workflow, feel free to engineer a faster application/process. You should probably also list an appropriate version (not 123) and the specs of your build machine if you're hoping to compare development performance.

Hello，pm，I'm sorry to use this place to ask these questions.My tone is okay in my view,probably because my English is not good enough,sorry.I just wanna ask you how can I study and debug bmcweb,project.this work flow is too hard for me to study,Could u do me a favor?
And, where can I talk to you and other engineers more conveniently?I didn't find forum.

**Comment by mdmillerii** [comment]
As Ed said it's off topic for GitHub.  As an alternative to email we also have discord server.  Be mindful we are an international collaboration and many are doing this as portion of their job.

Bmcweb is packaged to be started via it's [systemd socket and service](https://github.com/openbmc/bmcweb/blob/5fe4ef35821f946c91d9c20cee01e632d6d3ffd4/config/meson.build#L100) 
and and integrated via [bitbake](https://github.com/openbmc/openbmc/blob/e81f073e0441dfd5b70f93b46d13470bb13fa12f/meta-phosphor/recipes-phosphor/interfaces/bmcweb_git.bb). 

There are ways to incrementally edit the src and build just the package then deploy the changed package (s) ,or build with meson and the included subprojects then just copy  the executable and hopefully run on a different socket or even a developer machine if you are willing to have the extra dbus- services and permission.

Further discussion per project documentation 

https://github.com/openbmc/docs/tree/46902afd6ebd20d1148379df99fe2c0c591f56ba?tab=readme-ov-file#contact

https://github.com/openbmc/docs/blob/46902afd6ebd20d1148379df99fe2c0c591f56ba/code-of-conduct.md

https://github.com/openbmc/docs/blob/46902afd6ebd20d1148379df99fe2c0c591f56ba/discord-rules.md

**Comment by edtanous** [comment]
The openbmc mailing list or openbmc discord is where you should go for general development questions like this.

**Comment by fishermess** [comment]
> The openbmc mailing list or openbmc discord is where you should go for general development questions like this.

Thank u!

**Comment by fishermess** [comment]
> As Ed said it's off topic for GitHub. As an alternative to email we also have discord server. Be mindful we are an international collaboration and many are doing this as portion of their job.
> 
> Bmcweb is packaged to be started via it's [systemd socket and service](https://github.com/openbmc/bmcweb/blob/5fe4ef35821f946c91d9c20cee01e632d6d3ffd4/config/meson.build#L100) and and integrated via [bitbake](https://github.com/openbmc/openbmc/blob/e81f073e0441dfd5b70f93b46d13470bb13fa12f/meta-phosphor/recipes-phosphor/interfaces/bmcweb_git.bb).
> 
> There are ways to incrementally edit the src and build just the package then deploy the changed package (s) ,or build with meson and the included subprojects then just copy the executable and hopefully run on a different socket or even a developer machine if you are willing to have the extra dbus- services and permission.
> 
> Further discussion per project documentation
> 
> https://github.com/openbmc/docs/tree/46902afd6ebd20d1148379df99fe2c0c591f56ba?tab=readme-ov-file#contact
> 
> https://github.com/openbmc/docs/blob/46902afd6ebd20d1148379df99fe2c0c591f56ba/code-of-conduct.md
> 
> https://github.com/openbmc/docs/blob/46902afd6ebd20d1148379df99fe2c0c591f56ba/discord-rules.md

Thanks a lot! I will research more about this.Sorry for bother.
