### ISSUE TITLE
Unable to configure new IP address on eth interface

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#36]
Unable to configure new IP address on eth interface via redfish.
Following command is run:
```
}bash-4.1$curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"IPv4Addresses": [{"Address": "10.7.7.7","AddressOrigin": "Static","SubnetMask": "255.255.0.0","Gateway":"10.7.7.1"},{"Address": "x.x.x.x","AddressOrigin": "Static","SubnetMask": "255.255.255.0","Gateway":"x.x.x.1"}]}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

When we run to get configured results: it replaces link local address:
```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_2_0.EthernetInterface",
  "Description": "Management Network Interface",
  "IPv4Addresses": [
    {
      "Address": "10.7.7.7",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "0.0.0.0",
      "SubnetMask": "255.255.0.0"
    },
    {
      "Address": "x.x.x.x",
      "AddressOrigin": "Static",
      "Gateway": "x.x.x.1",
      "SubnetMask": "255.255.255.0"
    }
  ],
  "Id": "eth0",
  "MACAddress": "x.x.x.x.x.x",
  "Name": "Manager Ethernet Interface",
  "SpeedMbps": 0,
  "VLAN": {
    "VLANEnable": false,
    "VLANId": 0
```

But on system using ip addr:

```root@witherspoon:/tmp# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether x.x.x.x.x.x.x brd ff:ff:ff:ff:ff:ff
    inet 169.254.245.177/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet x.x.x.x/24 brd x.x.x.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::72e2:84ffxx:xx/64 scope link
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
```

**Comment by prkatti1** [comment]
@ratagupt FYI...

**Comment by prkatti1** [comment]
@edtanous could you Pls take a look into it.

**Comment by edtanous** [comment]
Bad gateway makes it sound like bmcweb is crashing.  I don't have the time to look into it this moment, but it would help a lot if you could dump the logs from journalctl.

**Comment by gkeishin** [comment]
@prkatti1 Can u provide the data here for @edtanous to take a look. Thanks

**Comment by prkatti1** [comment]
@edtanous Pls find journald logs as requested.

Feb 04 05:55:27 witherspoon login[1187]: pam_unix(login:session): session opened for user root by LOGIN(uid=0)
Feb 04 05:55:27 witherspoon login[1412]: ROOT LOGIN  on '/dev/ttyS4'





Feb 04 05:56:25 witherspoon systemd[1]: Started BMC Redfish Server (bmcweb).
Feb 04 05:57:54 witherspoon bmcweb[1418]: terminate called after throwing an instance of 'nlohmann::detail::type_error'
Feb 04 05:57:54 witherspoon bmcweb[1418]:   what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array
Feb 04 05:57:54 witherspoon nginx[1144]: 2019/02/04 05:57:54 [error] 1146#1146: *3 upstream prematurely closed connection while reading response header from upstream, client: 9.3.62.216, server: 127.0.0.1, request: "PATCH /redfish/v1/Managers/bmc/EthernetInterfaces/eth0 HTTP/1.1", upstream: "http://127.0.0.1:8082/redfish/v1/Managers/bmc/EthernetInterfaces/eth0", host: "bmchost"
Feb 04 05:57:54 witherspoon systemd[1]: bmcweb.service: Main process exited, code=killed, status=6/ABRT
Feb 04 05:57:54 witherspoon systemd[1]: bmcweb.service: Failed with result 'signal'.
Feb 04 05:57:55 witherspoon systemd[1]: bmcweb.service: Service RestartSec=1s expired, scheduling restart.
Feb 04 05:57:55 witherspoon systemd[1]: bmcweb.service: Scheduled restart job, restart counter is at 1.
Feb 04 05:57:55 witherspoon systemd[1]: Stopped BMC Redfish Server (bmcweb).
Feb 04 05:57:55 witherspoon systemd[1]: Started BMC Redfish Server (bmcweb).

**Comment by edtanous** [comment]
This looks like it's in the area where we already have a patchset in progress.  Can you pull it down and try it?

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/16596

**Comment by prkatti1** [comment]
@edtanous  CI build is not there anymore can u rebase ?

**Comment by prkatti1** [comment]
@edtanous could you Pls update on this?

**Comment by gkeishin** [comment]
@prkatti1 Can u bit bake image and run the test perhaps and confirm if it works

**Comment by bjwyman** [comment]
Random find from e-mail miss-click.
Should this be closed if https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/16596 is merged?

**Comment by prkatti1** [comment]
Working on latest master, clsoing this issue
