### ISSUE TITLE
Issue building with openbmc SDK - sdbusplus

### ISSUE THREAD

**Issue by JesusPhish** [openbmc/bmcweb#37]
I've seen these issues - https://github.com/openbmc/bmcweb/issues/2  and https://github.com/openbmc/bmcweb/issues/3 - but I believe it to be different from what I'm seeing now. 

Here is my process

- Source into SDK ". /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/environment-setup-armv6-openbmc-linux-gnueabi"
- Fresh checkout of latest bmcweb
- CD into repo
- Run build_x86.sh ". build_x86.sh"

When the script finishes I get the following

> -- Build files have been written to: /home/ircadmin/OpenBMCTutorials/Code/bmcweb/build
> Scanning dependencies of target bmcweb
> [ 16%] Building CXX object CMakeFiles/bmcweb.dir/src/webserver_main.cpp.o
> In file included from /home/ircadmin/OpenBMCTutorials/Code/bmcweb/build/sdbusplus-src/sdbusplus/asio/detail/async_send_handler.hpp:21,
>                  from /home/ircadmin/OpenBMCTutorials/Code/bmcweb/build/sdbusplus-src/sdbusplus/asio/connection.hpp:23,
>                  from /home/ircadmin/OpenBMCTutorials/Code/bmcweb/include/dbus_singleton.hpp:2,
>                  from /home/ircadmin/OpenBMCTutorials/Code/bmcweb/include/dbus_monitor.hpp:7,
>                  from /home/ircadmin/OpenBMCTutorials/Code/bmcweb/src/webserver_main.cpp:5:
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp: In member function ‘void sdbusplus::bus::bus::set_should_close(bool)’:
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp:156:34: error: ‘sd_bus_flush_close_unref’ is not a member of ‘sdbusplus::SdBusInterface’
>                  &SdBusInterface::sd_bus_flush_close_unref;
>                                   ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp: In member function ‘void sdbusplus::bus::bus::flush()’:
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp:173:24: error: ‘class sdbusplus::SdBusInterface’ has no member named ‘sd_bus_flush’; did you mean ‘sd_bus_call’?
>          int r = _intf->sd_bus_flush(_bus.get());
>                         ^~~~~~~~~~~~
>                         sd_bus_call
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp: In member function ‘void sdbusplus::bus::bus::close()’:
> /home/ircadmin/OpenBMCTutorials/SDK/romulus-2019-02-04/sysroots/armv6-openbmc-linux-gnueabi/usr/include/sdbusplus/bus.hpp:183:16: error: ‘class sdbusplus::SdBusInterface’ has no member named ‘sd_bus_close’; did you mean ‘sd_bus_call’?
>          _intf->sd_bus_close(_bus.get());
>                 ^~~~~~~~~~~~
>                 sd_bus_call
> CMakeFiles/bmcweb.dir/build.make:62: recipe for target 'CMakeFiles/bmcweb.dir/src/webserver_main.cpp.o' failed
> make[2]: *** [CMakeFiles/bmcweb.dir/src/webserver_main.cpp.o] Error 1
> CMakeFiles/Makefile2:936: recipe for target 'CMakeFiles/bmcweb.dir/all' failed
> make[1]: *** [CMakeFiles/bmcweb.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

[CMakeOutput.log](https://github.com/openbmc/bmcweb/files/2832414/CMakeOutput.log)

**Comment by JesusPhish** [comment]
Just to add to this, if I wipe the build directory, then set YOCTO_DEPENDENCIES to ON and re-run the build script, bmcweb builds ok.

**Comment by edtanous** [comment]
when using the SDK, YOCTO_DEPENDENCIES is the correct flag to use as you've found.  Closing.
