### ISSUE TITLE
bmc web /redfish/v1/Managers/bmc  Version mismatch

### ISSUE THREAD

**Issue by gkeishin** [openbmc/bmcweb#38]
There are two BMC images on the flash,
```
"Version": "2.6.0-rc1-150-ge14eac3",  Active  (Priority 0, currently running)
"Version": "2.6.0-rc1-151-gf8d0724"    Active (Priority 1, active but not running)

```
Now the /redfish/v1/Managers/bmc/ shows the Active but not the running one here.

"FirmwareVersion": "2.6.0-rc1-151-gf8d0724",

Verify BMC Firmware Version :: Get firmware version from BMC manager. | FAIL |
2.6.0-rc1-151-gf8d0724 != 2.6.0-rc1-150-ge14eac3

So I believe this needs to be fixed ?  @edtanous @anoo1

**Comment by sivassrr** [comment]
@rfrandse BMC manager version and cat /etc/os-version of latest master not matching

```root@wsbmc014.aus.stglabs.ibm.com's password: 
root@witherspoon:~# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.7.0-dev"
VERSION_ID="2.7.0-dev-48-gd22bc9b"    <======
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.7.0-dev"
BUILD_ID="2.7.0-dev"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~#``` 

```Redfish output curl -k -H "X-Auth-Token: itgT4Q5W4qozEu7vw5oE" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc
{
  "@odata.context": "/redfish/v1/$metadata#Manager.Manager",
  "@odata.id": "/redfish/v1/Managers/bmc",
  "@odata.type": "#Manager.v1_3_0.Manager",
  "Actions": {
    "#Manager.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "GracefulRestart"
      ],
      "target": "/redfish/v1/Managers/bmc/Actions/Manager.Reset"
    }
  },
  "DateTime": "2019-03-08T09:58:27+00:00",
  "Description": "Baseboard Management Controller",
  "EthernetInterfaces": {
    "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces"
  },
  "FirmwareVersion": "2.7.0-dev-9-g0d3201c", <====```

**Comment by geissonator** [comment]
Hopefully can use a new function I created in this area to find the functional firmware to fix this one (https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18521/8/redfish-core/include/utils/fw_utils.hpp)

**Comment by gkeishin** [comment]
We are still seeing this one . @ssombar reported on latest Master too.

**Comment by geissonator** [comment]
Fix up here - https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23199

**Comment by gkeishin** [comment]
> Fix up here - https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23199

Awesome. .Thanks @andrew
