### ISSUE TITLE
gateway field for the link local address is not there in redfish

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#39]
gateway field for the link local address is not there.

curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_2_0.EthernetInterface",
  "Description": "Management Network Interface",
  "IPv4Addresses": [
    {
      "Address": "169.254.xx.xx",
      "AddressOrigin": "IPv4LinkLocal",
      "SubnetMask": "255.255.0.0"
    },
    {
      "Address": "xx.xx.xx.xx",
      "AddressOrigin": "Static",
      "Gateway": "xx.xx.xx.1",
      "SubnetMask": "xx.xx.xx.0"
    }
  ],
  "Id": "eth0",
  "MACAddress": "xx.xx.xx.xx.xx.xx",
  "Name": "Manager Ethernet Interface",
  "SpeedMbps": 0,
  "VLAN": {
    "VLANEnable": false,
    "VLANId": 0
  }

Where as REST will give this output:
{
  "data": {
    "/xyz/openbmc_project/network/eth0/ipv4/44da1a5": {
      "Address": "xx.xx.xx.xx",
      "Gateway": "xx.xx.xx.1",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": xx,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0/ipv4/c6760cb6": {
      "Address": "169.254.xx.xx",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
      "PrefixLength": xx,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }
  },
  "message": "200 OK",
  "status": "ok"

**Comment by prkatti1** [comment]
@edtanous ca you Pls have look and update.

**Comment by maximyep** [comment]
Some details:
**1. Route deleted and added non-default**
Expected: Gateway 1.2.3.4
Actual  : Gateway 0.0.0.0

> root@romulus:~# ip route del 169.254.0.0/16
> root@romulus:~# ip route add 169.254.0.0/16 via 1.2.3.4
> 
> root@romulus:~# ip route
> default dev eth0 scope link  metric 2048 
> 169.254.0.0/16 via 1.2.3.4 dev eth0 
> 192.168.122.0/24 dev eth0 scope link  src 192.168.122.52 

max@max-VirtualBox:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://192.168.122.52/xyz/openbmc_project/network/eth0/ipv4/807091b4
{
  "data": {
    "Address": "169.254.40.210",
    "Gateway": "0.0.0.0",
    "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
    "PrefixLength": 16,
    "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
  },
  "message": "200 OK",
  "status": "ok"


**2. Added IPv4 address and gateway become correct**

> root@romulus:~# ip add add 1.2.3.4/24 dev eth0
> root@romulus:~# ip ro
> default dev eth0 scope link  metric 2048 
> 1.2.3.0/24 dev eth0 scope link  src 1.2.3.4 
> 169.254.0.0/16 via 1.2.3.4 dev eth0 
![2019-02-18 12_00_38-bmc running - oracle vm virtualbox](https://user-images.githubusercontent.com/3142364/52943031-e1db9d80-3374-11e9-9783-d2d8ed6fdcd4.png)

> 192.168.122.0/24 dev eth0 scope link  src 192.168.122.52 

max@max-VirtualBox:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://192.168.122.52/xyz/openbmc_project/network/eth0/ipv4/f66d02f
{
  "data": {
    "Address": "169.254.40.210",
    "Gateway": "1.2.3.4",
    "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
    "PrefixLength": 16,
    "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
  },
  "message": "200 OK",
  "status": "ok"

Finally: If a valid configuration is done - Gateway is correct.

**Comment by prkatti1** [comment]
closing this as it is workin gin latest build.
