### ISSUE TITLE
SNMP: allowed to configure manager with out of range port value > 65535

### ISSUE THREAD

**Issue by maximyep** [openbmc/bmcweb#42]
Steps to reproduce
**Sent to QEMU:**

curl -X POST -k -H 'Authorization: Basic cm9vdDowcGVuQm1j' -i 'https://127.0.0.1/xyz/openbmc_project/network/snmp/manager/action/Client' --data '{"data":["3.3.3.8", 65536]}'
Actual: HTTP/1.1 200 OK
Expected: HTTP/1.1 400 (OR Other error)
![2019-02-11 15_04_32-bmc running - oracle vm virtualbox](https://user-images.githubusercontent.com/3142364/52791284-4515b900-3071-11e9-9c34-0d202a06cbd3.png)

**Or Configure via WEB:** Server Configuration -> SNMP Settings -> Add SNMP manager

![2019-02-11 11_38_02-bmc running - oracle vm virtualbox](https://user-images.githubusercontent.com/3142364/52791329-5ced3d00-3071-11e9-974e-e6a8dddba6ee.png)

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18240/ 

@maximyep  made changes in test code which caught this.

**Comment by edtanous** [comment]
Based on the reproduction, this looks to be a missing range check in networkd.  We should probably open the bug there.

**Comment by maximyep** [comment]
@edtanous **Do I need to raise a new one? This one is not enough?**

**Comment by edtanous** [comment]
This bug appears to be fixed along with #101.  Please reopen if this is still an issue on a current build.
