### ISSUE TITLE
Unable to modify MAC address

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#43]
Unable to modify MAC address. Tried both PATCH and PUT methods.
PATCH gives 400 error
PUT gives 200 OK, but MAC address is not getting changed.

PUT method output:
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PUT -D put.txt -d '{"MACAddress": "x2:xx:xx:xx:xx:xx"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
bash-4.1$ cat put.txt
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Server: iBMC
Date: Fri, 15 Feb 2019 10:53:45 GMT
Content-Length: 0

PATCH method:
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"MACAddress": "x2:xx:xx:xx:xx:xx"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "MACAddress@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "The property MACAddress is not in the list of valid properties for the resource.",
      "MessageArgs": [
        "MACAddress"
      ],
      "MessageId": "Base.1.4.0.PropertyUnknown",
      "Resolution": "Remove the unknown property from the request body and resubmit the request if the operation failed.",
      "Severity": "Warning"
    }
  ]
}bash-4.1$ cat patch.txt
HTTP/1.1 400 Bad Request
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Content-Type: application/json
Server: iBMC
Date: Fri, 15 Feb 2019 10:53:14 GMT
Content-Length: 481

**Comment by ratagupt** [comment]
Hoping @prkatti1 you are using the local admin mac to change the mac address, I digged in the code and find that we don't have the support for PATCH of MAC Address.

**Comment by prkatti1** [comment]
@edtanous could you Pls take a look at it.

**Comment by edtanous** [comment]
The code is available to you.  Are you having trouble understanding it?  Having trouble putting together a patch to fix it?  I think ratagupt gave you some basic triage and his explanation seems to make sense to me.

I don’t know what’s going on here off the top of my head, if that’s what you were looking for.

**Comment by ratagupt** [comment]
@edtanous seems bmweb doesn't have support for PATCH of MAC address(even for local admin mac), we would be pushing the code for review next week.

**Comment by prkatti1** [comment]
working on latest master, closing this issue
