### ISSUE TITLE
Why Software Inventory

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#45]
Hi,

In the Firmware inventory, the firmware fo the bmc is named 'Software Inventory' (in update_service.hpp).
Is there any reason why the firmware for an open BMC is hard-coded ?
What would be the "Name=" for BIOS/CPLD/FPGA.... firmwares ?

Regards,
Francine

**Comment by geissonator** [comment]
I've got a commit up here (https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18270/) to fill in the Description field. I was also wondering if some improvements to the Name field would make sense as well.

**Comment by frsauvage** [comment]
Thank a lot , [geissonator](/geissonator), I hope it will be soon improved !

**Comment by edtanous** [comment]
18270 was merged.  Resolving.
