### ISSUE TITLE
Error about "AX_CXX_COMPILE_STDCXX_17(noext)"

### ISSUE THREAD

**Issue by theoneofjohnny** [openbmc/bmcweb#46]
Hi,

I am a newbie on Bmcweb. I am trying to build Bmcweb along without OpenBMC but fail. I get these errors.

`johnny is not in the sudoers file.  This incident will be reported.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/johnny/projects/bmcweb/3rdparty
[  2%] Performing update step for 'tinyxml2'
[  5%] Performing configure step for 'tinyxml2'
CMake Deprecation Warning at CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/johnny/projects/bmcweb/tinyxml2-build
[  7%] Performing build step for 'tinyxml2'
[ 50%] Built target tinyxml2
[100%] Built target xmltest
[ 10%] Performing install step for 'tinyxml2'
[ 50%] Built target tinyxml2
[100%] Built target xmltest
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/lib/libtinyxml2.so.6.0.0
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/lib/libtinyxml2.so.6
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/lib/libtinyxml2.so
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/include/tinyxml2.h
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/lib/pkgconfig/tinyxml2.pc
-- Installing: /home/johnny/projects/bmcweb/prefix/lib/cmake/tinyxml2/tinyxml2Config.cmake
-- Up-to-date: /home/johnny/projects/bmcweb/prefix/lib/cmake/tinyxml2/tinyxml2Targets.cmake
-- Installing: /home/johnny/projects/bmcweb/prefix/lib/cmake/tinyxml2/tinyxml2Targets-noconfig.cmake
[ 12%] Completed 'tinyxml2'
[ 20%] Built target tinyxml2
[ 22%] Performing update step for 'sdbusplus-project'
[ 25%] No configure step for 'sdbusplus-project'
[ 27%] Performing build step for 'sdbusplus-project'
+ AUTOCONF_FILES='Makefile.in aclocal.m4 ar-lib autom4te.cache compile         config.guess config.h.in config.sub configure depcomp install-sh         ltmain.sh missing *libtool test-driver'
+ case $1 in
+ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -Im4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/local/bin/autoconf --force
autoreconf: running: /usr/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:26: installing 'build-aux/compile'
configure.ac:7: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
autoreconf: Leaving directory `.'
Run "./configure ${CONFIGURE_FLAGS} && make"
+ echo 'Run "./configure ${CONFIGURE_FLAGS} && make"'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/local/gcc-8.2/bin/g++-7.4 accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of /usr/local/gcc-8.2/bin/g++-7.4... gcc3
checking for gcc... /usr/local/gcc-8.2/bin/gcc-7.4
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/gcc-8.2/bin/gcc-7.4 accepts -g... yes
checking for /usr/local/gcc-8.2/bin/gcc-7.4 option to accept ISO C89... none needed
checking whether /usr/local/gcc-8.2/bin/gcc-7.4 understands -c and -o together... yes
checking dependency style of /usr/local/gcc-8.2/bin/gcc-7.4... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether make sets $(MAKE)... (cached) yes
checking for a Python interpreter with version >= 2.7... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SYSTEMD... yes
checking how to run the C++ preprocessor... /usr/local/gcc-8.2/bin/g++-7.4 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking systemd/sd-bus.h usability... yes
checking systemd/sd-bus.h presence... yes
checking for systemd/sd-bus.h... yes
./configure: line 5702: syntax error near unexpected token `noext'
./configure: line 5702: `  AX_CXX_COMPILE_STDCXX_17(noext)'
CMakeFiles/sdbusplus-project.dir/build.make:111: recipe for target '/home/johnny/projects/bmcweb/sdbusplus-project/src/sdbusplus-project-stamp/sdbusplus-project-build' failed
make[2]: *** [/home/johnny/projects/bmcweb/sdbusplus-project/src/sdbusplus-project-stamp/sdbusplus-project-build] Error 2
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/sdbusplus-project.dir/all' failed
make[1]: *** [CMakeFiles/sdbusplus-project.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at /usr/share/cmake-3.14/Modules/FindBoost.cmake:2124 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.66 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)

OPENSSL_INCLUDE_DIR /usr/include
CMAKE_BUILD_TYPE=
-- Configuring incomplete, errors occurred!
See also "/home/johnny/projects/bmcweb/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.`

First error:
`./configure: line 5702: syntax error near unexpected token `noext'
./configure: line 5702: `  AX_CXX_COMPILE_STDCXX_17(noext)'`
I think the error relate to ".m4" files incomplete in sdbusplus source code therefore I clone autoconf and move all of .m4 to "bmcweb/sdbusplus-src" and "bmcweb/build/sdbusplus-src" both. Actully, I added one more file "ax_cxx_comoile_stdcxx_17.m4" that is downloaded from [GNU](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx_17.m4) but they don't helpful for this issue. 

Second error:
`CMake Error at /usr/share/cmake-3.14/Modules/FindBoost.cmake:2124 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0
[CMakeOutput.log](https://github.com/openbmc/bmcweb/files/2887441/CMakeOutput.log)
[CMakeOutput.log](https://github.com/openbmc/bmcweb/files/2887442/CMakeOutput.log)

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.66 (or
  newer).`
I downloaded boost 1.68. How can I redefine the path for Boost?

Thank you for reply and help!

**Comment by edtanous** [comment]
You are trying to compile the project, but don't have a compiler with c++17 support, and you are on an old version of boost.  Update both, and your error should go away.

Alternatively, this project is part of the main OpenBMC project, so compiling it within yocto is recommended.

**Comment by edtanous** [comment]
Closing due to lack of response from submitter.  Feel free to reopen if required.
