### ISSUE TITLE
Redfish(Systems): Unnecessary code is there for CPU and Dimm interface(Empty Interface)

### ISSUE THREAD

**Issue by ratagupt** [openbmc/bmcweb#49]
I saw that bmcweb code is referring to some properties which is not there in the meta-phosphor/phosphor-dbus-interfaces.

I could have seen that the dimm or cpu are empty interfaces but in the code, we are expecting the following properties

```           
 for (const std::pair<std::string, VariantType>
                                                 &property : properties)
  {
     if (property.first == "MemorySizeInKb") >>>>>>> we don't have this property under Dimm inetrface(https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Dimm.interface.yam)
                        
  connection.first, path,
  "org.freedesktop.DBus.Properties", "GetAll",                                     "xyz.openbmc_project.Inventory.Item.Dimm"
```

```
 if (property.first == "ProcessorFamily") >>>> same here I don't see this property under (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Cpu.interface.yaml)
           
 connection.first, path,
  "org.freedesktop.DBus.Properties", "GetAll", 
  "xyz.openbmc_project.Inventory.Item.Cpu");
```
I am not getting why we are expecting this property here?

@edtanous ^^^^

**Comment by gtmills** [comment]
MemorySizeInKb was added to https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Dimm.interface.yaml

Still don't see ProcessorFamily in the CPU inventory item

**Comment by feistjj** [comment]
@ratagupt @edtanous is no longer on the project, @cyang29 can you upstream this property?

**Comment by gtmills** [comment]
@cyang29 Do you mind upstreaming ProcessorFamily ?

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-dbus-interfaces/commit/259f49e0c40b287d9ea79f77db1654da47161340 added Family. Thanks! 
bmcweb still isn't looking for the right property names though: 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35949/5/redfish-core/lib/systems.hpp#340

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/36379/2/redfish-core/lib/systems.hpp fixed this. Closing. Please reopen if anyone thinks there is more work here.
