### ISSUE TITLE
Patch command on eth0 - IPv4Addresses crashed the bmcweb

### ISSUE THREAD

**Issue by sunharis** [openbmc/bmcweb#55]
$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://9.3.185.161/redfish/v1/Managers/bmc/EthernetInterfaces/eth0{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_2_0.EthernetInterface",
  "Description": "Management Network Interface",
  "IPv4Addresses": [
    {
      "Address": "9.3.185.161",
      "AddressOrigin": "Static",
      "Gateway": "9.3.185.1",
      "SubnetMask": "255.255.255.0"
    },
    {
      "Address": "169.254.53.121",
      "AddressOrigin": "IPv4LinkLocal",
      "SubnetMask": "255.255.0.0"
    }
  ],
  "Id": "eth0",
  "MACAddress": "52:e1:72:9f:2e:b4",
  "Name": "Manager Ethernet Interface",
  "SpeedMbps": 0,
  "VLAN": {
    "VLANEnable": false,
    "VLANId": 0
  }
$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"IPv4Addresses": [{ "Address": "9.3.185.161", "AddressOrigin": "Static", "Gateway":"9.3.185.1", "SubnetMask": "255.255.255.0"},{"Address": "169.254.53.121","AddressOrigin":"IPv4LinkLocal","SubnetMask":"255.255.0.0"}]}' https://9.3.185.161/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
curl: (52) Empty reply from server

root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.6.0-rc1"
VERSION_ID="2.6.0-rc1-200-ge4ba8cc-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.6.0-rc1"
BUILD_ID="2.6.0-rc1"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~#

**Comment by edtanous** [comment]
Review in progress that I suspect resolves this:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/16596
Please pull it down and verify it it does what you need.

**Comment by sunharis** [comment]
I pulled down this commit. The bmcweb does not crash anymore.

**Comment by edtanous** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/16596 was merged.  Closing.
