### ISSUE TITLE
Redfish: OemManager.Oem' is not of type 'object'

### ISSUE THREAD

**Issue by maximyep** [openbmc/bmcweb#58]
Execution of the https://github.com/DMTF/Redfish-JsonSchema-ResponseValidator
returns the following errors:

> /redfish/v1/Managers/bmc
>   schema: Manager.v1_3_0.json
> >>>'#OemManager.Oem' is not of type 'object'
> 
> /redfish/v1/Managers/bmc
>   schema: Manager.v1_3_0.json
> >>>'/redfish/v1/$metadata#OemManager.Oem' is not of type 'object'
> 
> /redfish/v1/Managers/bmc
>   schema: Manager.v1_3_0.json
> >>>'/redfish/v1/Managers/bmc#/Oem' is not of type 'object'

Full log:
[DMTF-RedfishJsonSchemaResponseValidator-full-logs.txt](https://github.com/openbmc/bmcweb/files/2919197/DMTF-RedfishJsonSchemaResponseValidator-full-logs.txt)

**Comment by gkeishin** [comment]
```
$ cat logs/*


/redfish/v1/Managers/bmc
  schema: Manager.v1_3_0.json
>>>'#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/$metadata#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/Managers/bmc#/Oem' is not of type 'object'

/redfish/v1/Chassis/motherboard
  schema: Chassis.v1_4_0.json
>>>'BuildDate' does not match any of the regexes: '^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message|Privileges)\\.[a-zA-Z_][a-zA-Z0-9_.]+$'

/redfish/v1/Managers/bmc#/Oem
  schema: Manager.v1_3_0.json
>>>'#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc#/Oem
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/$metadata#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc#/Oem
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/Managers/bmc#/Oem' is not of type 'object'

/redfish/v1/Managers/bmc#/Oem/OpenBmc
  schema: Manager.v1_3_0.json
>>>'#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc#/Oem/OpenBmc
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/$metadata#OemManager.Oem' is not of type 'object'

/redfish/v1/Managers/bmc#/Oem/OpenBmc
  schema: Manager.v1_3_0.json
>>>'/redfish/v1/Managers/bmc#/Oem' is not of type 'object'

/redfish/v1/Systems/system
  schema: ComputerSystem.v1_5_1.json
>>>'' is not valid under any of the given schemas

/redfish/v1/Systems/system
  schema: ComputerSystem.v1_5_1.json
>>>'BuildDate' does not match any of the regexes: '^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\\.[a-zA-Z_][a-zA-Z0-9_.]+$'
```

**Comment by edtanous** [comment]
@feistjj Have you seen this?

**Comment by feistjj** [comment]
Nope, was working for me if you make sure to pull down the OemManager schema

**Comment by edtanous** [comment]
@gkeishin can you try what James suggested and report back?

**Comment by gkeishin** [comment]
@edtanous sure will do..  Will keep posted

**Comment by maximyep** [comment]
> Nope, was working for me if you make sure to pull down the OemManager schema, looks like they didn't pull down all the schemas from the bmc. It's looking for this: https://github.com/openbmc/bmcweb/blob/master/static/redfish/v1/schema/OemManager_v1.xml#L24

I'm not sure, but this **check is done against the http://redfish.dmtf.org/schemas/v1/** 
Please take a look into diff (QEMU vs DMTF Simulator). Seems we are having issues:
![59c73-clip-92kb](https://user-images.githubusercontent.com/3142364/54264686-51ac0500-457c-11e9-9ea2-335f4f597299.png)

**Comment by feistjj** [comment]
> everything will be OK, then doesn't that beats what is the check own software - vs - own schemas

How else could you do an OEM schema?

I was using RedfishServiceValidator.py, I tried using our json but it seems to not be versioned in a way the tool likes. We probably need to update the way it is versioned if we are going to use our own.

**Comment by maximyep** [comment]
Let's do a summary:
* DMTF has JsonSchema-ResponseValidator;
* It would be good to do a test using this code.

Some links returns errors (see start-post):
* bad style: do not check this links;
* good style: to do some coverage in order to check all links.

I've saved all resources which is downloaded by python-code (attached)
[schema.tar.gz](https://github.com/openbmc/bmcweb/files/2966955/schema.tar.gz)

**What is needed to be added into Schema folder in case to receive PASS?**

Some additional info:
Test with /redfish/v1/Managers/ - PASSED, in test used and checked:
```
http://redfish.dmtf.org/schemas/v1/ManagerCollection.json

data:  {'@odata.context': '/redfish/v1/$metadata#ManagerCollection.ManagerCollection', '@odata.id': '/redfish/v1/Managers', '@odata.type': '#ManagerCollection.ManagerCollection', 'Members': [{'@odata.id': '/redfish/v1/Managers/bmc'}], 'Members@odata.count': 1, 'Name': 'Manager Collection'}
```

Test with /redfish/v1/Managers/bmc/ - FAILED, in test used and checked:
```
http://redfish.dmtf.org/schemas/v1/Manager.v1_3_0.json

data:  {'@odata.context': '/redfish/v1/$metadata#Manager.Manager', '@odata.id': '/redfish/v1/Managers/bmc', '@odata.type': '#Manager.v1_3_0.Manager', 'Actions': {'#Manager.Reset': {'ResetType@Redfish.AllowableValues': ['GracefulRestart'], 'target': '/redfish/v1/Managers/bmc/Actions/Manager.Reset'}}, 'DateTime': '2019-03-14T14:30:42+00:00', 'Description': 'Baseboard Management Controller', 'EthernetInterfaces': {'@odata.id': '/redfish/v1/Managers/bmc/EthernetInterfaces'}, 'FirmwareVersion': '2.7.0-dev-65-g645ef29', 'Id': 'bmc', 'Links': {'ManagerForServers': [{'@odata.id': '/redfish/v1/Systems/system'}], 'ManagerForServers@odata.count': 1}, 'LogServices': {'@odata.id': '/redfish/v1/Managers/bmc/LogServices'}, 'ManagerType': 'BMC', 'Model': 'OpenBmc', 'Name': 'OpenBmc Manager', 'NetworkProtocol': {'@odata.id': '/redfish/v1/Managers/bmc/NetworkProtocol'}, 'Oem': {'@odata.context': '/redfish/v1/$metadata#OemManager.Oem', '@odata.id': '/redfish/v1/Managers/bmc#/Oem', '@odata.type': '#OemManager.Oem', 'OpenBmc': {'@odata.context': '/redfish/v1/$metadata#OemManager.OpenBmc', '@odata.id': '/redfish/v1/Managers/bmc#/Oem/OpenBmc', '@odata.type': '#OemManager.OpenBmc'}}, 'PowerState': 'On', 'Status': {'Health': 'OK', 'State': 'Enabled'}, 'UUID': 'b97afe65-8435-4189-a09b-36ec69b973e7'}
```

**Comment by feistjj** [comment]
Have you tried adding https://github.com/openbmc/bmcweb/tree/master/static/redfish/v1/JsonSchemas/OemManager to the downloaded schema?

**Comment by gtmills** [comment]
@maximyep @gkeishin Still a problem or can we close ?

**Comment by maximyep** [comment]
I can't check or verify current behavior. Could be closed.

**Comment by gkeishin** [comment]
loaded the latest 
```
root@witherspoon-Y230UF71K02J:~# cat /etc/os-release
ID=openbmc-openpower
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.10.0-dev"
VERSION_ID=2.10.0-dev-995-g43a03d276
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.10.0-dev"
BUILD_ID="2.10.0-dev"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon-Y230UF71K02J:~#
```

```
['/redfish/v1/UpdateService/SoftwareInventory', '/redfish/v1/UpdateService/FirmwareInventory']}}, 'owningEntity': 'DMTF', 'title': '#SoftwareInventoryCollection.SoftwareInventoryCollection'}



1 resources validated.
0 errors
schemas returned from GET   1
schemas returned from cache 0
#(UTC) 2021/04/28 02:59:12.709215 -    1.422492 - Issuing: cat validate_errs
[32m.[0m[32m.[0m
                                                                              
Test BMC Redfish Using Redfish JsonSchema ResponseValidator :: Che... | [32mPASS[0m |
```

and its clean now.. Thanks

**Comment by gtmills** [comment]
George Keishing
 — 
Today at 9:47 PM
@GunnarM https://github.com/openbmc/bmcweb/issues/58 this now looks clean with latest build upstream.. we can close this i guess..
