### ISSUE TITLE
Redfish for openBMC

### ISSUE THREAD

**Issue by jinneal** [openbmc/bmcweb#6]
I find the version of schema is latest in static folder, but it can not support the Composable System and the version of redifsh is 1.1 according to the hard code of RootService, I guess if the current implement of Redfish just following the OCP Redfish Profile, dont care the new Composable  Service? or It will be supported later? and I can not find where  handle with the schema json, just hardcode following the schema files?

**Comment by edtanous** [comment]
The immediate priority has been the OCP profile.  I do not believe anyone has looked into composition service yet, nor have I seen any requirements for it.  Do you have requirements, or suggestions on how it should be done?  I'd recommend taking them to the mailing list.
