### ISSUE TITLE
Upload image always gives 400 error

### ISSUE THREAD

**Issue by mine260309** [openbmc/bmcweb#60]
Do image upload, bmcweb always gives below 400 error, even when the upload is actually sucessful.
```json
{
  "data": {
    "description": "Version already exists or failed to be extracted"
  },
  "message": "400 Bad Request",
  "status": "error"
}
```

**Comment by mine260309** [comment]
Likely it's caused by a short timeout (10s), if I understand the code correctly.
And it's introduced by c900850
^ @spinler

**Comment by spinler** [comment]
When I fixed up bmcweb to get image upload working, i got the timeout value from here: https://github.com/openbmc/phosphor-rest-server/blob/master/module/obmc/wsgi/apps/rest_dbus.py#L850

What is the timeout that should be used?

**Comment by mine260309** [comment]
> When I fixed up bmcweb to get image upload working, i got the timeout value from here: https://github.com/openbmc/phosphor-rest-server/blob/master/module/obmc/wsgi/apps/rest_dbus.py#L850

The loop in above code happens **after** the file is written, which is after the upload is done.
So basically the python code does upload, and waits 10 seconds for the version id to be extracted.

Now in bmcweb, the code looks like it has a 10s timeout and returns 400 error on timeout while the file is being uploaded, if I understand correctly.

**Comment by spinler** [comment]
I'm sure we could rearrange where we start the timer.  Could you investigate to see where in the handler all of the time is being taken?

**Comment by mine260309** [comment]
With more testing, it turns out that:
1. If we upload a tar without compression, the code runs well. The upload actually takes about 20 seconds.
2. If we upload a tar.gz, we get the above error.

So it looks like I did not understand the code correctly, the timeout is run after the file is uploaded... just BMC takes more time to decompress the tar.gz and parse the manifest to create the version object.

On Romulus, decompression of PNOR.tar.gz takes about 8.5 seconds; on Palmetto, it takes about 10 seconds.
The services need more time to parse manifest and create version object, so I think we should increase the timeout a bit, e.g. to 15 seconds, to support tar.gz tarball

**Comment by mine260309** [comment]
Did an experiment on Romulus, it turns out that it took 16~17 seconds for `Manager::processImage()` (in phosphor-bmc-code-mgmt) to extract the tarball and create version object.

The "bad" part is that the above functions actually runs two `tar -xf` command, the first one is to extract the manifest, and the second one to extract the whole tarball.

That part of code needs to refactor, then 10 seconds should be enough on P9, and it is close for P8.

So I would suggest:
1. Change the timeout value to 12~15 seconds;
2. Refactor `phosphor-bmc-code-mgmt` to improve the performance.

**Comment by gtmills** [comment]
@mine260309 Still a problem ? Should this be tracked elsewhere?

**Comment by mine260309** [comment]
> @mine260309 Still a problem ? Should this be tracked elsewhere?

If we upload .tar or small .tar.gz, which could be "untar"-ed in short time.
If we upload a large image with `.tar.gz` the issue still remains, but I assume that is not an upstream issue.

So I would say we could close this issue.
