### ISSUE TITLE
Improper error message upon trying to login with redfish user which is not enabled

### ISSUE THREAD

**Issue by sansomas** [openbmc/bmcweb#68]
Expected behavior:
===============
Error message shown for login attempt with Redfish user which is not enabled should be as or similar to below message

"Redfish user not enabled"

Actual behavior:
===============
Error message shown for login attempt with Redfish user which is not enabled is as below

"Message": "While accessing the resource at /redfish/v1/SessionService/Sessions, the service received an authorization error Invalid username or password."

Steps to reproduce:
=============
1) Create redfish user with any privilege , but it should not be enabled 
=============================================
```
curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${bmc}/redfish/v1/AccountService/Accounts -d '{
>
>     "UserName":"testop1",
>     "Password":"TestPwd123",
>     "RoleId":"Operator",
>     "Enabled":false}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "The resource has been created successfully",
      "MessageArgs": [],
      "MessageId": "Base.1.4.0.Created",
      "Resolution": "None",
      "Severity": "OK"
    }
  ]
```
2) Try to login with username created in step 1
===============================
```
-bash-4.1$ curl --insecure -X POST -D headers.txt https://${bmc}/redfish/v1/SessionService/Sessions -d '{"UserName":"testop1", "Password":"TestPwd123"}'
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "While accessing the resource at /redfish/v1/SessionService/Sessions, the service received an authorization error Invalid username or password.",
        "MessageArgs": [
          "/redfish/v1/SessionService/Sessions",
          "Invalid username or password"
        ],
        "MessageId": "Base.1.4.0.ResourceAtUriUnauthorized",
        "Resolution": "Ensure that the appropriate access is provided for the service in order for it to access the URI.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.ResourceAtUriUnauthorized",
    "message": "While accessing the resource at /redfish/v1/SessionService/Sessions, the service received an authorization error Invalid username or password."
  }
```

3) Enable that user 
===============
```
-bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH https://${bmc}/redfish/v1/AccountService/Accounts/testop1 -d '{"Enabled":true}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.4.0.Success",
      "Resolution": "None",
      "Severity": "OK"
    }
  ]
```

4) Try login after enabling
======================
```
-bash-4.1$ curl --insecure -X POST -D headers.txt https://${bmc}/redfish/v1/SessionService/Sessions -d '{"UserName":"testop1", "Password":"TestPwd123"}'
{
  "@odata.context": "/redfish/v1/$metadata#Session.Session",
  "@odata.id": "/redfish/v1/SessionService/Sessions/t1t5dCqcgr",
  "@odata.type": "#Session.v1_0_2.Session",
  "Description": "Manager User Session",
  "Id": "t1t5dCqcgr",
  "Name": "User Session",
  "UserName": "testop1"
```

**Comment by edtanous** [comment]
Marking this as an enhancement.  The error string being provided at this time is still correct, even if it may not be as specific as you'd prefer.  The credentials were in fact invalid, even if it was because the user was disabled, and not because one of the individual fields was incorrect.

One thing to keep in mind here, is we are limited to provide messages available in the Redfish message registry.  There is no registry message relating to a resource being disabled.  We could certainly improve the error string, but given that this is still correct, this is a low priority for me.

Feel free to send a PR that fixes this, and I'd be happy to review.

**Comment by edtanous** [comment]
No progress on this in 3 years.  Closing.
