### ISSUE TITLE
Unknown service for  xyz.openbmc_project.EntityManager

### ISSUE THREAD

**Issue by jinneal** [openbmc/bmcweb#7]
I find getChassis try to get instances from the service "xyz.openbmc_project.EntityManager", but I can not find the service in "busctl list", who know the service name of process?

**Comment by edtanous** [comment]
https://github.com/openbmc/entity-manager

**Comment by jinneal** [comment]
How to add it into my openbmc? is it in common layer?

**Comment by jinneal** [comment]
Change 10474 - Needs Code-Review Label (Work in Progress), I close it now
