### ISSUE TITLE
Redfish: Provide additional Thermal properties

### ISSUE THREAD

**Issue by smccarney** [openbmc/bmcweb#70]
The Redfish Thermal schema defines a large number of properties, most of which are optional.  Right now bmcweb returns a subset of those properties based on data available on DBus.

This issue will be used to define which additional Redfish Thermal properties bmcweb can provide in the near term based on data already available in DBus.

Only properties considered to be important for customer use will be included.

Properties that require new DBus data or complex implementation details will be deferred to a future enhancement.

A Google Docs spreadsheet is being used to track this work:
* The first sheet shows all the Redfish Thermal properties.  For those currently being set by bmcweb, it also shows the value being returned.
* The second sheet shows DBus properties that are currently used or could be used in the future to set Redfish Thermal properties.

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1bAlM3clyDUWACzyi2qjNwYfI58GYqOx2EjmFVeLf2hI/edit?usp=sharing

The spreadsheet is a work in progress.  All the Redfish properties and their current values are included.  However, which Redfish properties to begin setting in the future is not yet filled in.  Also, there may be additional DBus properties that can be added to sheet 2.

**Comment by edtanous** [comment]
We already have a documented way to track supported Redfish properties in a controlled, code reviewed manner in the Developing.md document in the root of bmcweb.  Please avoid inventing your own, unless it's your intention that the spreadsheet becomes the new standard, in which case, propose it as such in another review.

I'm having a lot of trouble reading this "enhancement" because it doesn't really say anything, aside from "we might want more thermal properties".  Which ones?  What features are missing to enable them?  The relevant detail isn't present.  I'm really tempted to close this with a "not enough detail" explanation, but I will give you some time to try to come up with the list of things you're requesting.

Note, in a lot of cases, you're not really asking for support from bmcweb.  To my knowledge, a majority, if not all of the thermal properties are exposed one way or another, and already have code implementations behind them.  A lot of what you're asking for here needs to be pushed to the fan control daemons themselves, but we can't know that until we understand exactly what you're looking for.

**Comment by smccarney** [comment]
Hi Ed.

Sorry for the confusion.  I am responsible for making sure that a key, minimum required set of Redfish Thermal properties work on IBM systems.  I am hoping to do that in a general way so it is useful for everyone.

I found the number of Redfish Thermal properties to be a bit overwhelming, and I don't believe we have the necessary firmware (at least on our systems) to fill them all out.  So I was trying to define which ones were really necessary and possible to return.  I have some meetings set up to work on this.

Brad Bishop (radsquirrel) suggested I open a GitHub issue and post a link to my spreadsheet to give the community a chance to see what I'm up to and give feedback.

I am definitely not trying to replace the information in Developing.md.  This issue was intended to just track my work over the next 1-2 months.  I'm not asking anyone else to do any work for me.

I can close the issue if it is causing confusion.

Thanks!
Shawn

**Comment by edtanous** [comment]
I think it would really help if you could lay out, in certain terms, what you're looking for in terms of Redfish changes.  I think it's great you're doing an analysis, but when you submit bugs, they need to be actionable, and of an appropriate size.  Based on the above description, and the abstract title, I don't see anything actionable.  If you're trying to plan work, I know that IBM tends to use the openbmc-ibm project for that.  Maybe that's what @bradbishop meant?

There are _some_ actionable things in the spreadsheet, like the Range properties returning zero, but I think each one needs to be called out in its own bug, unless it's somehow related to some underlying feature, like fan redundancy support.  If you're looking to share your spreadsheet with others on the project, the mailing list is probably a better bet than a github bug.

I know in the case of thermal, a lot of the features were initially written against dbus-sensors and entity-manager, which I know IBM systems don't use, so it's very likely there are some interface discrepancies between the two that you're likely running into.

Lets see if we can get your spreadsheet down to a list of things actionable, then lets get the bugs filed where appropriate.

**Comment by bradbishop** [comment]
> but when you submit bugs
This wasn't meant to be interpreted as a bug.

>  If you're trying to plan work, I know that IBM tends to use the openbmc-ibm project for that. Maybe that's what @bradbishop meant?

Indeed, I just wanted us to be transparent in the work that we plan on doing.  openbmc-ibm is our downstream development PM area so I don't think that is the appropriate place to track the work Shawn is doing, as Shawn intends to upstream his work, whatever repository that winds up being in.

@krtaylor did we document somewhere, where exactly we should be opening issues to track enhancements?  All the issues with Release2.7 tags seem to be on the openbmc/openbmc repo - should we move this issue to that repository?  Does that work for you @edtanous ?

**Comment by edtanous** [comment]
I do appreciate the transparency, and I think the work planning is probably better done on the openbmc/openbmc github.  Once it's down to the level of detail needed, I'm happy to host the open bmcweb sections here, I just want to avoid the open-ended never ending bug types, and keep it explicit about what we're hoping to accomplish.

**Comment by smccarney** [comment]
Moved to https://github.com/ibm-openbmc/dev/issues/356.

**Comment by smccarney** [comment]
I had an ibm-openbmc issue already open that I could use for this work.  Brad thought moving it there was fine.  Sorry for the confusion/inconvenience.
