### ISSUE TITLE
org.freedesktop.DBus.Error.FileNotFound: path or object not found" 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/bmcweb#72]
We have been seeing this lately on CI runs. 

```

Post Request using : alias=openbmc, uri=/org/open_power/control/gard/action/Reset,
data={"data": []}, 
headers={u'Content-Type': u'application/json', u'X-Auth-Token': u'L5iSpHiFS2aEnbc6X11p'}, 
files=None, allow_redirects=True

${ret} = <Response [404]>

```

```
${msg} = Response code:404, Content:{ "data":
 { 
"description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found"
 }, 
"message": "404 Not Found", 
"status": "error"
 }
```

```
# mapper get-service /org/open_power/control/gard
org.open_power.Software.Host.Updater
```
so looks like the bmcweb stopped looking (or handling) org.open_power dbus interfaces ?

**Comment by geissonator** [comment]
Note we're seeing this with all the recent bmcweb meta-phosphor bumps.

First bump I can find where this started was in https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/19978

```
Ed Tanous (2):
      bmcweb: avoid move in error conditions
      bmcweb: return 405 when a method is not supported

Tanous (1):
      Allow multiple registrations
```

**Comment by edtanous** [comment]
That’s very likely an issue with the first patch in that series.  Will take a look in the next couple hours and fix or revert if necessary.

**Comment by edtanous** [comment]
And I already found it on my phone while waiting for my coffee.
https://github.com/openbmc/bmcweb/blob/4ed69245822e548763e7d4ba7bdb9f5cdba75c22/include/openbmc_dbus_rest.hpp#L2033
That line and the one a few lines down needs to be /org not /xyz.  Sorry about that, I don’t have any org interfaces left on my system to test.  Will get a patchset pushed up for review once I’m on a computer

**Comment by edtanous** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20080
