### ISSUE TITLE
bmcweb does not fully implement OCPServerHardwareManagement and OCPBaselineHardwareManagement profiles

### ISSUE THREAD

**Issue by maximyep** [openbmc/bmcweb#73]
- [ ] Base: 12 problems found
- [ ] Server: 17 problems found
Base execution logs:

[InteropLog_04_04_2019_163621.txt](https://github.com/openbmc/bmcweb/files/3043752/InteropLog_04_04_2019_163621.txt)

[qemu.base-log1.txt](https://github.com/openbmc/bmcweb/files/3043755/qemu.base-log1.txt)

Server execution logs:
[InteropLog_04_04_2019_163822.txt](https://github.com/openbmc/bmcweb/files/3043753/InteropLog_04_04_2019_163822.txt)

[qemu.server-log1.txt](https://github.com/openbmc/bmcweb/files/3043757/qemu.server-log1.txt)

Html logs:
[interop-html-logs.tar.gz](https://github.com/openbmc/bmcweb/files/3043768/interop-html-logs.tar.gz)

Test was done using https://github.com/DMTF/Redfish-Interop-Validator
Profiles taken from: https://www.opencompute.org/wiki/Hardware_Management/SpecsAndDesigns#Baseline_and_Server_profile

Execution string:
```
RedfishInteropValidator.py --ip 192.168.122.52 --nochkcert --forceauth -u root -p 0penBmc --logdir /home/max/ ~/profiles/OCPServerHardwareManagement.v0_2_3.json | tee qemu.server-log1.txt
RedfishInteropValidator.py --ip 192.168.122.52 --nochkcert --forceauth -u root -p 0penBmc --logdir /home/max/ ~/profiles/OCPBaselineHardwareManagement.v1_0_0.json | tee qemu.base-log1.txt
```

**Comment by gtmills** [comment]
@maximyep What qemu model was this?

**Comment by edtanous** [comment]
Agreed that we should support these.  There has been some work done and pushed to gerrit to implement these in some fashion.  I would recommend using some of @hcleepinga patches as a base to start this, as I believe she is attempting the same test, and working through the missing features.

**Comment by maximyep** [comment]
> @maximyep What qemu model was this?

```
root@romulus:~# uname -a
Linux romulus 5.0.4-8b3439b5b1608d580628af573000faa7d7db4b48 #1 Wed Mar 27 20:22:55 UTC 2019 armv6l GNU/Linux

Welcome to Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.7.0-dev!
Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 romulus ttyS4

```
