### ISSUE TITLE
fail to set {     "SerialConsole": {         "ServiceEnabled": false     } }

### ISSUE THREAD

**Issue by kuiyingw** [openbmc/bmcweb#74]
could get     
"SerialConsole": {
        "ConnectTypesSupported": [
            "IPMI",
            "SSH"
        ],
        "ServiceEnabled": true
    },
via GET https://${bmc}:${port}/redfish/v1/Managers/bmc
but fail to set by
PATCH https://${bmc}:${port}/redfish/v1/Managers/bmc
{
    "SerialConsole": {
        "ServiceEnabled": false
    }
}

**Comment by edtanous** [comment]
SerialConsole is not disablable at this point.  Marking as enhancement.

**Comment by edtanous** [comment]
No effort put in on this in 4 years, and code has significantly changed. 
 Closing.
