### ISSUE TITLE
Unable to configure MAC address

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#78]
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"MACAddress": "x6:xx:xx:xx:xx:xx"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```
{
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "DHCPv4": {
    "DHCPEnabled": false
  },
  "HostName": "witherspoon",
  "IPv4Addresses": [
    {
      "Address": "169.254.xx.x0",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "",
      "SubnetMask": "255.255.0.0"
    },
    {
      "Address": "x.x.xx.xx",
      "AddressOrigin": "Static",
      "Gateway": "x.x.xx.1",
      "SubnetMask": "255.xx.xx.0"
    }
  ],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "LinkStatus": "NoLink",
  "MACAddress": "xx:xx:xx:xx:xx:xx",
  "NameServers": [],
  "SpeedMbps": 0,
  "StaticNameServers": [],
  "Status": {
    "Health": "OK",
    "State": "Disabled"
  },
  "VLANs": {
    "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/VLANs"
  },
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.InternalError",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}bash-4.1$cat patch.txt
HTTP/1.1 500 Internal Server Error
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'; img-src 'self' data:
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Content-Type: application/json
Server: iBMC
Date: Wed, 24 Apr 2019 06:42:10 GMT
Content-Length: 1391```

**Comment by ratagupt** [comment]
@prkatti1  In latest master it is working fine.
We are using the following release 
```
cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.8.0-dev"
VERSION_ID="2.8.0-dev-89-g911f50f61"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.8.0-dev"
BUILD_ID="2.8.0-dev"
OPENBMC_TARGET_MACHINE="witherspoon"
```
curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"MACAddress": "a6:e2:84:14:16:6c"}' https://${BMC_IP}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

-bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0                      {
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_4_1.EthernetInterface",
  "DHCPv4": {
    "DHCPEnabled": false,
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
  "Description": "Management Network Interface",
  "HostName": "witherspoon-YL10UF76W015",
  "IPv4Addresses": [
    {
      "Address": "9.3.185.33",
      "AddressOrigin": "Static",
      "Gateway": "9.3.185.1",
      "SubnetMask": "255.255.254.0"
    },
    {
      "Address": "169.254.172.85",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "0.0.0.0",
      "SubnetMask": "255.255.0.0"
    }
  ],
  "IPv4StaticAddresses": [
    {
      "Address": "9.3.185.33",
      "Gateway": "9.3.185.1",
      "SubnetMask": "255.255.254.0"
    }
  ],
  "IPv6Addresses": [
    {
      "Address": "fe80::a4e2:84ff:fe14:166c",
      "AddressOrigin": "LinkLocal",
      "PrefixLength": 64
    }
  ],
  "IPv6DefaultGateway": "",
  "IPv6StaticAddresses": [],
  "Id": "eth0",
  "InterfaceEnabled": true,
  "LinkStatus": "NoLink",
  "MACAddress": "a6:e2:84:14:16:6c",
  "Name": "Manager Ethernet Interface",
  "NameServers": [],
  "SpeedMbps": 0,
  "StaticNameServers": [],
  "Status": {
    "Health": "OK",
    "State": "Disabled"
  },
  "VLANs": {
    "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/VLANs"
  }
}`

**Comment by prkatti1** [comment]
Working on latest build, so closing this.
