### ISSUE TITLE
POST request session response 405

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/bmcweb#8]
I am trying test redfish interface with test_redfish_interfaces.robot in openbmc-test-automation
 
But it fail when Test Setup at the beginning.

It will POST a session and return 405.

![image](https://user-images.githubusercontent.com/15260220/46340961-9b0d3580-c669-11e8-95ef-0fe42ed56721.png)

Using curl command got the same result.
![image](https://user-images.githubusercontent.com/15260220/46341106-f7705500-c669-11e8-943d-a57e88eecf8c.png)

405 is Method Not Allowed response status code indicates that the request method is known by the server but is not supported by the target resource.

Does the POST session not support yet?

I also did test_rest_interfaces.robot test.

There is also POST test, but 405 is expected.

![image](https://user-images.githubusercontent.com/15260220/46341399-8e3d1180-c66a-11e8-816d-952a7c74fca6.png)

Does that related to this issue?

Thanks.

**Comment by edtanous** [comment]
Looking at the responses you're getting, it's pretty clear you're not talking to bmcweb.  When I try your command (plus a --noproxy addition specific to me) against bmcweb I get the following response.

```JSON
➜  ~ curl --noproxy "*" -c cjar -k -X POST -H "Content-Type: application/json" -d '{"data": [ "root","0penBmc"]}' https://10.243.48.30/redfish/v1/SessionService/Sessions
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "The request body submitted was malformed JSON and could not be parsed by the receiving service.",
        "MessageId": "Base.1.2.0.MalformedJSON",
        "Resolution": "Ensure that the request body is valid JSON and resubmit the request.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.2.0.MalformedJSON",
    "message": "The request body submitted was malformed JSON and could not be parsed by the receiving service."
  }
}%
```
The above is an error message I would expect to see if I were talking to redfish.

First thing, make sure you're talking to bmcweb.  I'm not sure what platform you're on, or what packages you have turned on/off, but make sure that bmcweb is enabled, and that nginx, and phosphor-rest-server are disabled.  Looking at your error message, your message is getting routed to phosphor-rest-server, which doesn't know how to deal with it.

Once that is resolved, your curl example also has a few issues.  The payload appears to be a phosphor-rest login payload, not a Redfish payload.

Below is a working example of your command that I ran against my system.
```JSON
➜ ~ curl --noproxy "*" -k -X POST -d '{"UserName": "root", "Password": "0penBmc"}' https://10.243.48.30/redfish/v1/SessionService/Sessions/
{
  "@odata.context": "/redfish/v1/$metadata#Session.Session",
  "@odata.id": "/redfish/v1/SessionService/Sessions/9yel6M5afl",
  "@odata.type": "#Session.v1_0_2.Session",
  "Description": "Manager User Session",
  "Id": "9yel6N6afl",
  "Name": "User Session",
  "UserName": "root"
}% 
```

**Comment by Kenthliu** [comment]
Hi Ed

Thank you very much!

It looks I sent the wrong command.

The command you list is also work by my side.

But it needs to indicate the port 883.

![image](https://user-images.githubusercontent.com/15260220/46450115-3ca79a80-c7c2-11e8-8995-ebd967299cbd.png)

Thank you again and issue can be closed.
