### ISSUE TITLE
BMC does not switch to next address when DNS sends multiple IP address to A record

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#81]
BMC does not switch to next address when DNS sends multiple IP address to DNS A record.
Steps:
1. Configure DNS server on BMC
2. Configure DNS server to send 2 IP addresses (IP1 and IP2) to DNS A record. (Exa: test1.bmc.com)
4. Make 1st IP address IP1 down.
3. Try to access or ping test1.bmc.com

BMC only try IP1 and it does not time out and try to reach 2nd IP.

**Comment by ratagupt** [comment]
Seems this defect should be opened against systemd-networkd not here.

**Comment by prkatti1** [comment]
yep, opening a defect in systemd networkd and closing this.

**Comment by prkatti1** [comment]
will be tracked via https://github.com/systemd/systemd/issues/13275
