### ISSUE TITLE
Certificate Signature validation fails for RSA type Keys.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/bmcweb#82]
Signature validation fails for RSA type self signed certificate Keys in the bmcweb code.

Created self signed certificate using RSA algorithm and copy the file to certificate path . bmcweb.service restarts reports failure and creating new self signed certificate.

systemctl restart bmcweb.service

May 10 12:31:03 xxxx systemd[1]: Stopped Start bmcweb server.
May 10 12:31:03 xxxx  systemd[1]: Started Start bmcweb server.
May 10 12:31:04 xxxx  bmcweb[1580]: Checking certs in file /etc/ssl/certs/https/server.pem
May 10 12:31:04 xxxx  bmcweb[1580]: Found an RSA key
May 10 12:31:04 xxxx  bmcweb[1580]: Error in verifying signature, regenerating
May 10 12:31:04 xxxx  bmcweb[1580]: Generating new keys
May 10 12:31:04 xxxx  bmcweb[1580]: Generating EC key
May 10 12:31:04 xxxx  bmcweb[1580]: Generating x509 Certificate

**Comment by ojayanth** [comment]
Looking at the bmcweb/include/ssl_key_handler.hpp  inline bool verifyOpensslKeyCert(const std::string &filepath)  function   “ privateKeyValid” value is  not initialized in the “RSA” path. So always, this functions return false for RSA type. This could be fixed .

**Comment by edtanous** [comment]
This is not a bug.

This is the intended behavior, to allow replacing old autogenerated RSA keys with more modern RSA keys.  Considering that before your series, bmcweb didn't allow uploading a certificate at all, marking RSA certificates as errors was reasonable.

Now that we allow upload, the RSA keys function properly, and anyone using openbmc is unlikely to have the old key style, fixing this behavior should be fine.

**Comment by ojayanth** [comment]
@edtanous It will be good to support RSA. 
Review link related to this change .https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21450
