### ISSUE TITLE
The rule of user password is not clear.

### ISSUE THREAD

**Issue by shannonliang312** [openbmc/bmcweb#90]
Hello:
     Through ‘/redfish/v1/AccountService’ , we can get the 'MaxPasswordLength' and 'MinPasswordLength' of user password, but no other restrictions.
     When create/edit user from WEBUI, some password which matches the rule of length, like '1234abcd', '11111abc', '12345678a', still get the error message of invalid password from backend.
      In the /etc/pam.d/common-password, I find some pam modules  and there are some limitations about user password.
```
password	[success=ok default=die]	pam_ipmicheck.so spec_grp_name=ipmi
password	[success=ok default=die]	pam_cracklib.so debug enforce_for_root reject_username minlen=8 difok=0 use_authtok
password	[success=ok ignore=ignore default=die]	pam_pwhistory.so debug enforce_for_root remember=0 use_authtok
password	[success=ok default=die]	pam_unix.so sha512 use_authtok
password	[success=1 default=die] 	pam_ipmisave.so spec_grp_name=ipmi spec_pass_file=/etc/ipmi_pass key_file=/etc/key_file
password	requisite			pam_deny.so
password	required			pam_permit.so
```
But none of them could explain  why the passwords mentioned above are invalid. 
So I want to know where to find those definition of user password rules.
THANKS!(please forgive my poor English)

**Comment by edtanous** [comment]
Pay close attention to the “pam_cracklib” module in the settings you linked.  This is likely the rules you are looking for.

**Comment by edtanous** [comment]
Can this bug be closed?

**Comment by shannonliang312** [comment]
@edtanous yes，thanks for your advise！
