### ISSUE TITLE
BMC dump download failed via REST

### ISSUE THREAD

**Issue by ojayanth** [openbmc/bmcweb#96]
Steps to recreate :

root@xxxx:/var/lib/phosphor-debug-collector/dumps# ls -larth *
10:
-rw-r--r--    1 root     root      171.4K Jul  3 10:45 obmcdump_10_1562150658.tar.xz
drwxr-xr-x    2 root     root         248 Jul  3 10:45 .
drwxr-xr-x    4 root     root         288 Jul  3 13:49 ..

11:
drwxr-xr-x    4 root     root         288 Jul  3 13:49 ..
-rw-r--r--    1 root     root      180.7K Jul  3 13:50 obmcdump_11_1562161636.tar.xz
drwxr-xr-x    2 root     root         248 Jul  3 13:50 .
root@xxxx:/var/lib/phosphor-debug-collector/dumps#

-bash-4.2$ curl -O -J -c cjar -b cjar -k -H "X-Auth-Token: $bmc_token" https://$BMC_IP/download/dump/10
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  171k  100  171k    0     0   284k      0 --:--:-- --:--:-- --:--:--  284k
-bash-4.2$ curl -O -J -c cjar -b cjar -k -H "X-Auth-Token: $bmc_token" https://$BMC_IP/download/dump/11
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  180k  100  180k    0     0   399k      0 --:--:-- --:--:-- --:--:--  398k
-bash-4.2$ ls -larth
total 362K
drwxrwxrwx 108 xxxxx 8.0K Jul  3 09:48 ..
-rw-rw-r--   1 xxxx 172K Jul  3 09:48 10
drwxrwxr-x   2 xxxx  512 Jul  3  2019 .
-rw-rw-r--   1 xxx 181K Jul  3  2019 11
-bash-4.2$

Should have downloaded by dump name instead of dump id.

**Comment by ojayanth** [comment]
Looks like existing code  deoesn't support to download file with original file name.

**Comment by ojayanth** [comment]
@edtanous   @spinler 
 fix is available  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23338

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23338 merged. Can we close?

**Comment by feistjj** [comment]
Looks like it was closed already.. Not sure how it reopened.
