### ISSUE TITLE
Redfish(Chassis):ChassisCollection has no members

### ISSUE THREAD

**Issue by vic-lin-accton** [openbmc/bmcweb#99]
We are porting openbmc and have this issue. Wondering which step we missed.  Thanks

We also downloadand use qemu run the "obmc-phosphor-image-romulus-20190711181621.static.mtd"  to check and got the same result as below

curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}:2443/redfish/v1/Chassis
{
  "@odata.context": "/redfish/v1/$metadata#ChassisCollection.ChassisCollection",
  "@odata.id": "/redfish/v1/Chassis",
  "@odata.type": "#ChassisCollection.ChassisCollection",
  "Members": [],
  "Members@odata.count": 0,
  "Name": "Chassis Collection"
}

**Comment by edtanous** [comment]
without knowing more about your system, it isn't clear how you configured it.  If no chassis are detected, or the association information was not filled in, it doesn't suprise me that you'd have an empty chassis collection.

**Comment by vic-lin-accton** [comment]
Yes, it seems we need to fill some info to describe our system. Thanks
